### ISSUE TITLE
Upload web-site directly to Amazon S3 / CloudFront

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/doc#1]
Use Travis CI to upload the web-site to Amazon S3 / CloudFront.

**Comment by rtsisyk** [comment]
It is also possible to upload to GitHub pages and use tarantool.org name instead of tarantool.github.io.

**Comment by bigbes** [comment]
Undecided

**Comment by lenkis** [comment]
@rtsisyk is it still of interest for us?

**Comment by kostja** [comment]
No.
