### ISSUE TITLE
Update 'connectors' docs to include space and index creation

### ISSUE THREAD

**Issue by ichuev** [tarantool/doc#100]
Current documentation (for example [here](https://tarantool.org/doc/book/connectors/index.html)) misses space and index creation, so that example fails with (for python driver):

`tarantool.error.SchemaError: There's no space with name 'examples'`

Workaround (again, for python) is to use:

```
import tarantool
tnt = tarantool.connect('127.0.0.1', 3301)
tnt.eval("box.schema.space.create('examples', {if_not_exists=true})")
tnt.eval("box.space.examples:create_index('primary', {if_not_exists=true})")
result = tnt.insert("examples",(99999,'Value', 'Value'))
print result
```

It would be better to include all steps, required to successfully execute example script, to avoid confusion.

**Comment by pgulutzan** [comment]
The recommendation in the Python section is:
"Before trying to run, check that the server is listening at
localhost:3301 and that the space examples exists, as described earlier"
with a link to
(https://tarantool.org/doc/book/connectors/index.html#index-connector-setting)/
6.3. Setting up the server for connector examples.
If one follows these instructions, the example works without problems.
