### ISSUE TITLE
Improve TDG main page

### ISSUE THREAD

**Issue by v-izmalkov** [tarantool/doc#1017]
Наряду с тикетом на исправление неточности позиционирования -  https://github.com/tarantool/doc/issues/909 . Я бы хотел предложить расширить и улучшить страницу описания TDG. 
Больше текста даст больше информации о продукте конечным пользователям, например добавить use-case примеры и описать сильные стороны продукта (не для разработчиков, но для лиц, принимающих решения на первоначальном этапе). Все это позволит читателям с большей вероятностью представить применимость продукта в их случае. Кроме того, Большее количество текста позволит его лучше оптимизировать для SEO - больше ключевых слов для продвижения в поиске.

**Comment by arctic-dreamer** [comment]
Seems like it can be solved by https://github.com/tarantool/tdg-doc/issues/188 and https://github.com/tarantool/tdg-doc/issues/187
