### ISSUE TITLE
Добавить описание map_reduce

### ISSUE THREAD

**Issue by v-izmalkov** [tarantool/doc#1019]
В продолжение https://github.com/tarantool/doc/issues/948 - у map_reduce есть необязательные параметры, которые описаны тут - https://gitlab.com/tarantool/tdg/tdg/issues/192#note_240224736

Кроме того, там же описан механизм (видимо новый, с combine), который надо описать в документации.

**Comment by arctic-dreamer** [comment]
Seems like the `map_reduce` chapter was updated: https://www.tarantool.io/en/tdg/1.6/dev/map-reduce/#combine
