### ISSUE TITLE
Document box.session.su()

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/doc#102]
I can't find box.session.su() documentation.

https://tarantool.org/doc/book/box/box_session.html
- `box.session.su(user)` - changes the login  user of current session to `user`.
- `box.session.su(username, function)` - changes login user of current session to `user`, executes `function` and then reverts user back (like sudo).

**Comment by bigbes** [comment]
It, also, accepts vararg for passing into function:
```
tarantool> box.session.su('guest', function(...) return ... end, 1, 2, 3)
---
- 1
- 2
- 3
...
```
