### ISSUE TITLE
Add releases lifetime table

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#1025]
**Epic: [Release notes](https://github.com/tarantool/doc/issues/2570)**

**Product:** Tarantool
**Audience/target:** anyone who is choosing the right Tarantool release for their project
**Root document:** TBA, maybe around release notes?
**SME:** @ Totktonada

Like this one: https://wiki.ubuntu.com/Releases

Can be included in https://github.com/tarantool/doc/issues/2218

Mention that support of 1.10 will be dropped with the 2.10–2.11 release (@ kyukhin's words).

**Comment by Totktonada** [comment]
@artembo also [suggested](https://github.com/tarantool/doc/issues/1420#issuecomment-671327610) to add a diagram similar to [Django](https://www.djangoproject.com/download/)'s:

![image](https://user-images.githubusercontent.com/92749/89840450-f323f580-db78-11ea-993d-a260a289fcee.png)

**Comment by rybakit** [comment]
> @artembo also suggested to add a diagram similar to Django's

Also, check https://www.php.net/supported-versions.php and https://symfony.com/releases.

**Comment by veod32** [comment]
I see the label "site", so what are we going to do:
- to add this diagram to the release page in documentation https://www.tarantool.io/en/doc/latest/dev_guide/release_management/
- or to place the diagram on some of the site page?
