### ISSUE TITLE
[3pt] Cleanup Tarantool C Style Guide

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#1031]
https://www.tarantool.io/en/doc/1.10/dev_guide/c_style_guide/

The following characters look inapplicable in context of tarantool:

* Chapter 10: Kconfig configuration files
* Chapter 13: Printing kernel messages
* Chapter 14: Allocating memory

Chapters that should be adjusted:

* Chapter 17: Don’t re-invent the kernel macros
  - Update it with macros from `src/trivia/util.h`.

[veod32]: The issue estimation of 48pt is subject to changed if we understand the scope of work is bigger than the current one above.

**Comment by Onvember** [comment]
After discussing this issue with @Totktonada and the core team, we found out that the problem is deeper than just removing inapplicable chapters. We need to refactor the Code style Guide and to add some Tarantool code style features which are missing now.

**Comment by LeonidVas** [comment]
Please, on https://www.tarantool.io/en/doc/latest/dev_guide/c_style_guide/ replace https://www.kernel.org/doc/Documentation/CodingStyle with https://www.kernel.org/doc/Documentation/process/coding-style.rst
