### ISSUE TITLE
installing a specific package version with tarantoolctl rocks install

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#1042]
Say that with `tarantoolctl rocks install` you can install a specific version of a package, e.g. 
`tarantoolctl rocks install http://rocks.tarantool.org/cartridge-1.2.0-1.rockspec`

https://www.tarantool.io/en/doc/2.2/reference/tarantoolctl/#commands-for-managing-tarantool-modules

**Comment by lenkis** [comment]
конкретную версию можно ставить rocks install foobar 1.0.0

с рокспекой есть проблемы на старом луароксе (тарантул 1.10)

**Comment by olegrok** [comment]
> с рокспекой есть проблемы на старом луароксе (тарантул 1.10): tarantool/tarantool#4704

- Not only 1.10, 2.1 is also affected

- It's not a problem with ".rockspec" - it's a problem with ".rock" - packed tarantool module via `tarantoolctl rocks pack`. We use it only for tagged versions (not scm) of two modules - "cartridge" and "frontend-core"

**Comment by p7nov** [comment]
Closing: tarantoolctl is replaced with tt CLI.
