### ISSUE TITLE
Сделать вёрстку понагляднее

### ISSUE THREAD

**Issue by cerevra** [tarantool/doc#105]
Сейчас некоторые страницы выглядят как сплошное полотно. Неясно, где конец описания одной фичи и начало другой
Например:
https://tarantool.org/doc/dev_guide/reference_capi/box.html
https://tarantool.org/doc/book/box/box_schema.html

Сделайте читабельно, пожалуйста

**Comment by bigbes** [comment]
Need Feedback, имхо. 
Непонятно что мешает, чего хочется и как это представляется.

**Comment by cerevra** [comment]
https://tarantool.org/doc/book/box/box_schema.html
Мешает то, что тяжело найти конец одного раздела и начало другого
Хочется, чтобы так не было
Представляется так, что если хотя бы после каждого раздела добавить две пустые строки, то станет уже лучше. А там уж как дизайнерская душа захочет

Вот есть ```box.schema.user.grant```, сразу после первой строки есть еще пара сигнатур, еще какое-то барахло, example. А потом ```box.schema.user.revoke```. И так далее.
Для того, чтобы узнать список имеющихся фич или найти конкретную, мне надо искать глазами блок Example, чтобы сразу после него прочесть имя очередной фичи. На других станицах у фич бывает по несколько примеров, и такой "поиск" работает только на этой странице.
Т.е. мне как пользователю пришлось придумать какой-то подход к отдельной станице докуменации.

**Comment by mejedi** [comment]
#80 dup
