### ISSUE TITLE
Add a copy-pasteable version of user input to examples

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#107]
In python docs, they have a very nice option in examples to show a copy-pasteable version of user's input, e.g. see here:
https://docs.python.org/3/howto/functional.html#data-types-that-support-iterators
Click >>> in the upper right corner of the example to see a copy-pasteable version.
Can we add such an option to our manual?

**Comment by lenkis** [comment]
@kostja can we put this on LT todo list?

**Comment by kostja** [comment]
* Elena Shebunyaeva <notifications@github.com> [17/06/22 15:24]:
> @kostja can we put this on LT todo list?

Yes.


-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by lenkis** [comment]
Closed with PR merge https://github.com/tarantool/doc/pull/243
