### ISSUE TITLE
Active navigation menu item is incorrect when browsing built-in modules

### ISSUE THREAD

**Issue by RunsFor** [tarantool/doc#1073]
![Screenshot 2020-01-20 at 15 06 11](https://user-images.githubusercontent.com/2008930/72725668-63e0d180-3b97-11ea-8515-1be9f99e34e5.png)

To reproduce, just go to [`box` module](https://www.tarantool.io/en/doc/2.2/reference/reference_lua/box/) documentation and click on one of the submodules (i.e. box.space)

**Comment by artembo** [comment]
The box submodules was moved into built-in reference section in e5402bd60475c95f3c5806793282c645919445e4
