### ISSUE TITLE
JSON.cfg description is wrong

### ISSUE THREAD

**Issue by eljashm** [tarantool/doc#1085]
As was previously stated in https://github.com/tarantool/doc/issues/994 serializers configuration option encode_load_metatables is said to be set to false by default, which is not the case. 

There are also wrong default values for the following options:
encode_max_depth is not 32 but 128,
decode_max_depth - same.

Also, these options are non-existent: decode_load_metatables, decode_sparse_convert and decode_use_tostring.

It's all in src/lua/utils.c

Description of cfg.decode_save_metatables states: "it is like encode_load_metatables" which is not exactly the case. But it seems the issue of description is more relevant to https://github.com/tarantool/doc/issues/976

**Comment by olegrok** [comment]
> There are also wrong default values for the following options:
> encode_max_depth is not 32 but 128,

https://github.com/tarantool/tarantool/issues/4670

https://github.com/tarantool/tarantool/commit/bf20a7cedd9e7394197dff18a0d4afd8f0368559

**Comment by Onvember** [comment]
fixed in https://github.com/tarantool/doc/pull/1124
