### ISSUE TITLE
Enhance documentation of box.prepare's metadata

### ISSUE THREAD

**Issue by rybakit** [tarantool/doc#1094]
Please update the documentation explaining the `metadata` parameter from the [box.prepare](https://www.tarantool.io/en/doc/2.3/book/box/box_sql/#lua-function.box.prepare) result. Playing with `box.prepare()` I found out that this property contains information about the columns of the returned result set. However, I'm not sure I fully understand how it gets constructed. For example, why in the following example `?` marked as `boolean`:

```lua
unix/:/var/run/tarantool/tarantool.sock> box.prepare([[ SELECT ? ]])
---
- stmt_id: 3016011286
  execute: 'function: 0x40a89c08'
  params:
  - name: '?'
    type: ANY
  unprepare: 'function: 0x40a89c30'
  metadata:
  - name: '?'
    type: boolean
  param_count: 1
...
```
Also, please add a note that the `metadata` property will only be present for `select` (and `pragma`) statements, for other ones this property will be omitted.

**Comment by pgulutzan** [comment]
Okay, except for the question why ? is boolean. That is not an exceptional matter related to box.prepare(), it just happens to be the type, which is unknown. This is not official, but unknown often means the same thing as NULL, and for NULL we say elsewhere in the manual: "If the data type of NULL cannot be determined from context, it is BOOLEAN."
