### ISSUE TITLE
Introduce box.ANY

### ISSUE THREAD

**Issue by denesterov** [tarantool/doc#1097]
There are (well) known problem using `nil` / `box.NULL` in select.
Sometimes they interpreted as a equivalent of 'nil' i. e.  'ANY' statement, sometimes - as 'NO DATA' statement:

```
S = box.schema.create_space('S', {format = {{name='k', type='string'}, {name='x', type='integer', is_nullable = true}, {name='y', type='integer', is_nullable = true}}})
S:create_index('pk', {parts={1}})
S:create_index('i', {unique=false, parts={{2, is_nullable = true}, {3, is_nullable = true}}})

S:insert({'a',1,1})
S:insert({'b',1,2})
S:insert({'c',2,1})
S:insert({'d',1,5})
S:insert({'e',2,2})
S:insert({'f',1,box.NULL})
S:insert({'g',box.NULL,2})
S:insert({'h',1,box.NULL})
```

No Data statement:
```
tarantool> S.index.i:select({1, box.NULL})
---
- - ['f', 1, null]
  - ['h', 1, null]
...
tarantool> S.index.i:select({box.NULL, 2})
---
- - ['g', null, 2]
...
```

Any statement:
```
tarantool> S.index.i:select(box.NULL, {limit=3})
---
- - ['g', null, 2]
  - ['f', 1, null]
  - ['a', 1, 1]
...
```
Introduction of `box.ANY` special value can bring more clarity to select calls.

**Comment by knazarov** [comment]
Please don't. It will only further complicate the already complicated API.

**Comment by lenkis** [comment]
@kyukhin I need your "don't" to close this issue. Or "do" -- to continue the discussion.

**Comment by kyukhin** [comment]
Frankly speaking, I don't quite understand, what this new type supposed to be? What its difference w.r.t `box.NULL`?
I agree that things are complicated here. Maybe just prepare a KB entry for documentation with extensive examples?

As a single line: Currently I don't like `box.ANY` idea.
