### ISSUE TITLE
Добавить пример использования Токена приложения

### ISSUE THREAD

**Issue by v-izmalkov** [tarantool/doc#1100]
В документации уже описано, как создать токен приложения, но вот пример его корректного использования - отсутствует.

Предлагается добавить в документацию простейший пример на python:

```
header = {'auth-token' : 'ee7fbd80-a9ac-4dcf-8e43-7c98a969c33c'}
r = requests.post(url = "http://localhost:8080/http", json = object, headers = header)
```

**Comment by arctic-dreamer** [comment]
Now we use 'Authorization: Bearer'

The following examples were added:
https://www.tarantool.io/en/tdg/1.6/requests/settings/#project-name
https://www.tarantool.io/en/tdg/1.6/requests/data-access/http/#http-auth
https://www.tarantool.io/en/tdg/1.6/requests/data-access/graphql/#mutations-insert-example
https://www.tarantool.io/en/tdg/1.6/requests/data-access/json/#json-request
