### ISSUE TITLE
feedback: Installation guide

### ISSUE THREAD

**Issue by dimoffon** [tarantool/doc#1119]
Проводя установку TDG по инструкции https://www.tarantool.io/ru/tdg/1.5/deployment/, встретил следующие неточности:
- неочевидно откуда должен браться дистрибутив tdg для установки
- какая минимальная версия tdg должна использоваться в примере (если это важно)
- не написано, что файл конфигурации кластера надо назвать deploy.json
- нужно указать, что tdgctl.py находится в /deploy
- дополнительно нужна установка модулей из requirements.txt

**Comment by v-izmalkov** [comment]
> * не написано, что файл конфигурации кластера надо назвать deploy.json

Это не обязательно, параметры запуска tdgctl.py указаны в документации - https://www.tarantool.io/ru/tdg/1.5/admin_appendix/#id2 .



> * дополнительно нужна установка модулей из requirements.txt

requirements.txt из папки test? Он нужен только для запуска тестов и упоминается в документации - https://www.tarantool.io/ru/tdg/1.5/writing_tests/

**Comment by v-izmalkov** [comment]
Остальное устранено вот тут - https://gitlab.com/tarantool/tdg/doc/-/merge_requests/8

**Comment by dimoffon** [comment]
> > * не написано, что файл конфигурации кластера надо назвать deploy.json
> 
> Это не обязательно, параметры запуска tdgctl.py указаны в документации - https://www.tarantool.io/ru/tdg/1.5/admin_appendix/#id2 .
> 
> > * дополнительно нужна установка модулей из requirements.txt
> 
> requirements.txt из папки test? Он нужен только для запуска тестов и упоминается в документации - https://www.tarantool.io/ru/tdg/1.5/writing_tests/

Да, requirements нужен не весь, а модуль requests из него (для работы tdgctl)

**Comment by v-izmalkov** [comment]
Ок, внёс и эти правки - https://gitlab.com/tarantool/tdg/doc/-/merge_requests/8/diffs?commit_id=8c2156092dcfe63600df1b4b289d3cdc6c4b5a35

**Comment by lenkis** [comment]
По этому тикету всё поправили. Дима, Володя, большое спасибо!
