### ISSUE TITLE
feedback: QuickStart guides

### ISSUE THREAD

**Issue by dimoffon** [tarantool/doc#1121]
Из всех гайдов в примерах запросов на чтение/запись данных нужно убрать префиксы json и graphql

guide_2
- заменить "XML via SOAP» -> «SOAP via HTTP»
- предлагаю добавить в пример запроса поиск по индексу `{ Person(id: 1) { id name } }` 

guide_3
- лучше поправить в примере возвращаемое значение вызова delete_inactive_persons, т.к. возвращается json в виде строки (либо вообще убрать возвращение удаляемых данных, так обычно не делают):
`{ "data": { "delete_inactive_persons": "[{\"lastActivityDate\":\"2020-01-12\",\"name\":\"Adam Sanders\",\"id\":2},{\"lastActivityDate\":\"2020-01-11\",\"name\":\"John Smith\",\"id\":1}]" } `

guide_5
- "в использованием хэш-функции" -> "c использованием хэш-функции"
- текст (см ниже) из гайда неясен, т.к. понятие бакета является абстракцией, к которой в гайде не приведено ссылок или определений.
> Теперь, если нам нам потребуется найти все книги, которые взял пользователь с заданным user_id, будут выбраны записи из одного из "бакетов", вместо обхода кластера (при котором используется функция программного интерфейса репозитория "map_reduce") с поиском записей с данным значением поля user_id.

**Comment by v-izmalkov** [comment]
> Из всех гайдов в примерах запросов на чтение/запись данных нужно убрать префиксы json и graphql

Это не "префиксы" а параметры отображения (подсветки) исходного кода. Их видно в редакторе, но при рендеринге они исчезают:

<img width="1808" alt="Снимок экрана 2020-02-14 в 16 29 53" src="https://user-images.githubusercontent.com/54984326/74535688-6b518b80-4f47-11ea-8543-03351f175ad3.png">

**Comment by v-izmalkov** [comment]
> * предлагаю добавить в пример запроса поиск по индексу `{ Person(id: 1) { id name } }`

не требуется, в примере уже есть подобный запрос
