### ISSUE TITLE
[websocket] Add an intro to readme

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#1126]
Когда следует использовать https://github.com/tarantool/websocket ?

когда хотите сразу из браузера ходить в тарантул:
  - без переподключений
  - двунаправленно

например,
- чат можно сделать
- можно котировки слать
- можно пуши на страницу
- бекенд для rich internet application

**Comment by Onvember** [comment]
fixed with https://github.com/tarantool/websocket/commit/f24cfd4ca47f294598b97b9f5bb883f380b52143
