### ISSUE TITLE
Localize tarantool.org website

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#121]

**Comment by lenkis** [comment]
Russian texts here: https://docs.google.com/document/d/1pqUx4SEwJg_O7AFU91w4VGHEvdZ49hOmY7x7Rgc5kJA/edit?usp=sharing

**Comment by lenkis** [comment]
@bigbes we have all Ru texts (except vacancies, but this waits). please help to publish.

**Comment by lenkis** [comment]
@kostja doing it for the current .org site?

**Comment by kostja** [comment]
Postponed.
