### ISSUE TITLE
Add documentation on the new Tarantool release repository at S3

### ISSUE THREAD

**Issue by avtikhon** [tarantool/doc#1218]
We already have 'live' repositories of Tarantool packages for all the pushed patches to release branches, which can be downloaded as described in:
  https://www.tarantool.io/en/download/
For now we created the new 'release' repositories of Tarantool packages, but only for tagged Tarantool versions in all release branches. These repositories are used for upgrading Tarantool not for all pushed patches, but only for released stable versions. We need some new part/entry of the instruction on the Tarantool web site which will help the users to use these repositories.
As an example lets check how 'live' repositories are used from here:
  https://www.tarantool.io/en/download/os-installation/ubuntu/
```
echo "deb https://download.tarantool.org/tarantool/2.2/ubuntu/ ${release} main" > /etc/apt/sources.list.d/tarantool_2_2.list
echo "deb-src https://download.tarantool.org/tarantool/2.2/ubuntu/ ${release} main" >> /etc/apt/sources.list.d/tarantool_2_2.list
```
The new 'release' repository will be available the same, except the head link will be changed from
  https://download.tarantool.org
to
  https://download-release.tarantool.org
like this:
```
echo "deb https://download-release.tarantool.org/tarantool/2.2/ubuntu/ ${release} main" > /etc/apt/sources.list.d/tarantool_2_2.list
echo "deb-src https://download-release.tarantool.org/tarantool/2.2/ubuntu/ ${release} main" >> /etc/apt/sources.list.d/tarantool_2_2.list
```

**Comment by avtikhon** [comment]
After discussion in the team decided to change the paths. The new 'release' repository will be available at the main domain:
https://download.tarantool.org

like this:
echo "deb https://download.tarantool.org/tarantool/release/2.2/ubuntu/ ${release} main" > /etc/apt/sources.list.d/tarantool_2_2.list
echo "deb-src https://download.tarantool.org/tarantool/release/2.2/ubuntu/ ${release} main"

**Comment by Totktonada** [comment]
@avtikhon Is this resolved now? I see 'Release' and 'Live' instructions on the website.

**Comment by avtikhon** [comment]
Closing, due to all correctly done.
