### ISSUE TITLE
Improvements for PDF version

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#123]
It's great that a PDF version of the Tarantool manual is available!
Yet there are some improvements to make:

[ ] No TOC generated under the "Contents" heading in the beginning
[ ] Cross-references within the manual exported as plain text, not hyperlinks
[ ] Formatting for inline ``code_samples`` not applied
... to be continued

**Comment by bigbes** [comment]
No way to do that in PDF generation. We may split this thing into multiple
PDF files..

With best regards, Eugene.

2016-11-17 16:40 GMT+03:00 Elena Shebunyaeva <notifications@github.com>:

**Comment by lenkis** [comment]
Check this article: https://habrahabr.ru/post/328182/
The guys have a TOC in sphinx-generated PDF + hyperlinks.

**Comment by lenkis** [comment]
@kostja delegate to LT?

**Comment by lenkis** [comment]
We have much nicer PDF output for Bastida docs. Let's troubleshoot why PDF output looks so poor for Tarantool.
