### ISSUE TITLE
Improve search for Russian doc

### ISSUE THREAD

**Issue by ligurio** [tarantool/doc#1234]
https://www.tarantool.io/ru/doc/2.3/search/?q=%D1%80%D0%B5%D0%BF%D0%BB%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F

-->
"Результаты поиска: 0
Ничего не найдено."

but there is a whole chapter about replication - https://www.tarantool.io/ru/doc/2.3/book/replication/

**Comment by lenkis** [comment]
We need to set up a custom elasticsearch engine for our doc.

**Comment by artembo** [comment]
The problem does not exist, the Russian search engine is working. Anyway, see the next steps regarding the search engine [here](https://github.com/tarantool/tarantool.io/issues/631).
