### ISSUE TITLE
Translate section with functional index

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/doc#1239]
We forgot to translate this piece of text about the functional index [here](https://www.tarantool.io/ru/doc/2.2/reference/reference_lua/box_space/#box-space-index-func).

Due to missed translation, I can't find this piece of documentation in Russian via Google.

**Comment by lenkis** [comment]
2.x translation is in progress

**Comment by NickVolynkin** [comment]
Will be fixed in #1850
