### ISSUE TITLE
Reformulate description box.slab.info()

### ISSUE THREAD

**Issue by IlyaMarkovMipt** [tarantool/doc#124]
Description of arena_used says that it shows the efficient memory used for tuples and indexes. User can understand it as memory only tuples and indexes occupy, no free memory.

**Comment by lenkis** [comment]
Current `arena_used` description looks valid (https://tarantool.org/en/doc/book/box/box_slab.html#lua-function.box.slab.info):

      * arena_size is the total memory used for tuples and indexes together
        (including allocated, but currently free slabs);
      * arena_used is the efficient memory used for storing tuples and indexes
        together (omitting allocated, but currently free slabs).

That said:
* `arena_used` = tuples+indexes
* `arena_size` = tuples+indexes+allocated_but_unused_mem
