### ISSUE TITLE
Implement onboarding email at the site

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/doc#1258]
We have a default text for **"Welcome letter"** and backend link with the SendGrid account. 
**The next actions:**
- grammar and logic check of the Russian text and hyperlinks
- translate it in English
- implement language detection in the site backend
- link all hyperlinks with Google Analytics
- create redirect link in the Telegram chats instead of teleg.run (Russian/English versions)
- availability test of support@tarantool.io inbox 
- test this configuration

**Russian text:**

> Мы рады, что вы с нами!
> 
> **С чего стоит начать:**
> 
> - Первое знакомство с Tarantool [https://www.tarantool.io/en/doc/1.10/book/getting_started/](https://www.tarantool.io/en/doc/1.10/book/getting_started/)
> 
>     Запустите ваш первый инстанс Тарантул, создайте первую таблицу и добавьте данные.
> 
>     Настройте доступ к базе данных из вашего языка программирования.
> 
> **Уже знакомы с Tarantool?**
> 
> - Попробуйте Tarantool Cartridge — бесплатное кластерное решение для распределенных систем.
> 
>     Поднимите локально кластер, автоматически настройте шардирование и репликацию, напишите пару строк кода и запустите их на кластере. 
> 
> - Посчитайте сайзинги по данным и нагрузке тут: [https://www.tarantool.io/en/sizing_calculator/](https://www.tarantool.io/en/sizing_calculator/)
> 
> **Нужна помощь?**
> 
> - Наше сообщество в Телеграм: https://[teleg.run/tarantoolru](http://teleg.run/tarantoolru)
> - Поддержка с гарантиями для любого бизнеса: support@tarantool.io

**Comment by lenkis** [comment]
Мы рады, что вы с нами!

С чего стоит начать?
- Запустите ваш первый инстанс Тарантул, создайте первую таблицу и добавьте данные.
  https://www.tarantool.io/ru/doc/latest/getting_started/getting_started_db/
- Настройте доступ к базе данных из вашего языка программирования.
  https://www.tarantool.io/ru/doc/latest/getting_started/getting_started_connectors/ 

Уже знакомы с Tarantool?
- Попробуйте Tarantool Cartridge — бесплатное кластерное решение для распределенных систем.
  https://www.tarantool.io/ru/doc/latest/getting_started/getting_started_cartridge/
  Поднимите локальный кластер, напишите пару строк кода и запустите их на кластере.
- Посчитайте сайзинги по данным и нагрузке.
  https://www.tarantool.io/ru/sizing_calculator/

Нужна помощь?
- Наше сообщество в Телеграм: https://teleg.run/tarantoolru
- Поддержка с гарантиями для любого бизнеса: support@tarantool.io

-----------------

Welcome to Tarantool!

Where to start?
- Launch your first Tarantool instance, create your first database and experiment with data.
  https://www.tarantool.io/en/doc/latest/getting_started/getting_started_db/
- Connect to the database from your favorite programming language.
  https://www.tarantool.io/en/doc/latest/getting_started/getting_started_connectors/

What's next?
- Try Tarantool Cartridge — an opensource cluster solution for distributed systems.
  https://www.tarantool.io/en/doc/latest/getting_started/getting_started_cartridge/
  Deploy a local cluster, add some code and launch it as a cluster app.
- Estimate physical resources required for your data sizing and load profile.
  https://www.tarantool.io/en/sizing_calculator/

Need help?
- Your community in Telegram: https://teleg.run/tarantool
- Support with SLA for all businesses: support@tarantool.io
