### ISSUE TITLE
Automate check for broken links

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#126]

**Comment by lenkis** [comment]
@kostja delegate to LT?

**Comment by kostja** [comment]
* Elena Shebunyaeva <notifications@github.com> [17/06/22 16:21]:
> @kostja delegate to LT?

OK.


-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by lenkis** [comment]
The logic is implemented by @bigbes. We need to decide at which point to call it as we build/deploy the site + how critical the results are (warning/abort).

**Comment by patiencedaur** [comment]
There is `make linkcheck` (see README). Closing.
