### ISSUE TITLE
Update box.cfg default values

### ISSUE THREAD

**Issue by Korablev77** [tarantool/doc#1268]
At least I see that [doc](https://www.tarantool.io/en/doc/1.10/reference/reference_lua/box_cfg/#box-cfg-default) says `vinyl_write_threads` by default is 2, meanwhile in fact default value of `vinyl_write_threads` is 4. Please check other default values as well.

**Comment by lenkis** [comment]
please check for 1.10 + 2.2 + 2.3 + 2.4

say `box.cfg` to see defaults for a particular tarantool version

**Comment by ImeevMA** [comment]
Looks like the changes are missing in one place: https://www.tarantool.io/en/doc/latest/reference/configuration/#cfg-storage-vinyl-write-threads

**Comment by p7nov** [comment]
The value is also outdated in https://www.tarantool.io/en/doc/latest/concepts/engines/vinyl/#unpredictable-write-speed

The occurrence in https://www.tarantool.io/en/doc/latest/how-to/sql/improving_mysql/ doesn't need an update - `2` is the value we set explicitly.
