### ISSUE TITLE
Optimise documentation webpage load speed

### ISSUE THREAD

**Issue by artembo** [tarantool/doc#1273]
The loading speed of the documentation pages is too slow. Especially on slow computers.
There are several reasons of this:
- The TOC tree builds and transforms by the jquery script every time the page loads. Solution: compile and convert toc-tree once when importing documentation.
- get rid of unused JavaScript and combine all the scripts into one compact file. The same goes for CSS.
- optimize SQL queries that are used to retrieve documentation content from a database
- configure the application cache for frequently used parts of the page and database queries.

The current profiling test indicates the major problem in scripting which is extremely long. The test was performed for https://www.tarantool.io/ru/doc/2.2/reference/reference_sql/sql/
<img width="319" alt="Снимок экрана 2020-04-27 в 14 45 38" src="https://user-images.githubusercontent.com/23726173/80368732-dac3ef80-8895-11ea-874d-986197cdebb3.png">
The network data:
<img width="659" alt="Снимок экрана 2020-04-27 в 14 56 36" src="https://user-images.githubusercontent.com/23726173/80369694-5d997a00-8897-11ea-8aa5-24a8315bc362.png">

**Comment by rybakit** [comment]
> get rid of unused JavaScript and combine all the scripts into one compact file. The same goes for CSS.

Or switch to HTTP/2?

**Comment by artur-barsegyan** [comment]
Done. The page loading time was decreased by three times.
