### ISSUE TITLE
Fix EN/RU switch

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#128]
Due to the recent directory changes in our doc project, the language switch at all Russian pages returns invalid paths when you try switching back to the English version.

**Comment by bigbes** [comment]
It's not a bug in EN/RU switch (appears only on multiple slashes paths). Explanation is [here](https://www.slightfuture.com/webdev/relative-double-slashes-url):

> The problem here is that the author’s expectations are not guaranteed: web servers take it on themselves to do non-standards compliant (as I understand RFC-2396) “smart” matching of locations where multiple forward slashes are interpreted internally a single forward slash. Web browsers stick to standards and don’t do any such smart character deduplication. For example, URLs containing base64 encoded paths may explicitly require support for multiple forward slashes in a row, so browsers can’t just copy the web servers default behavior on this one.

I've fixed (as I think) origin of this behaviour - It'll be seen in a couple of days, when google will rescan tarantool.org.
