### ISSUE TITLE
[8pt] Improve release notes: workflow and user experience

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#1285]
**Epic: [Release notes](https://github.com/tarantool/doc/issues/2570)**

Problems with OS Tarantool release notes (RN):

1. No style guide for RN, so writers need to brush up the draft a lot (e.g. RN items are phrased differently).
TODO: Introduce a simple style guide for all RN contributors.

2. No automatic integration of RN into the manual, so writers need to do it manually.
TODO: If we continue mirroring RN in the manual, automate md-to-rst import.

3. Too wordy RN section in the manual, which adds no value beyond RN text at GH.
TODO: Think of making the most of RN as a community communication tool. Here is an article for inspiration: https://uxdesign.cc/the-art-of-writing-great-release-notes-6607e22efae1

**Comment by patiencedaur** [comment]
Draft Notion document with ideas: https://www.notion.so/tarantool/WIP-Release-notes-workflow-b4292dbf8fbd41d58a1983546de4a879

**Comment by patiencedaur** [comment]
Duplicate: https://github.com/tarantool/doc/issues/2111
