### ISSUE TITLE
Adjust the size of preview icon for tarantool repo

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#1293]
In telegram, links to github.com/tarantool generate a huge-size preview.

These links look fine:
github.com/tarantool/avro-schema
github.com/tarantool/queue

Please adjust the preview size for tarantool repo at GH.

-------------

Elena Shebunyaeva, [6 May 2020, 19:53:27]:
а что на размер превью влияет?

Alexander Turenko, [6 May 2020, 19:54:04]:
https://github.com/tarantool/tarantool/wiki/Feature-specifications
Размер картинки м. б. как-то подобрать.
Или загрузить несколько разных.
Я не знаю, на основе чего github генерит opengraph-разметку.

**Comment by lenkis** [comment]
![preview](https://user-images.githubusercontent.com/16703423/81207055-a5c24600-8fd5-11ea-8d85-a5c311d08fcd.png)

**Comment by artembo** [comment]
Сейчас выглядит хорошо
