### ISSUE TITLE
How do I store binary data in Tarantool?

### ISSUE THREAD

**Issue by kostja** [tarantool/doc#13]
The manual says nothing about storing binary data, it only mentions that we support messagepack data types. Perhaps be more explicit when listing supported data types? 

https://tarantool.org/doc/book/box/index.html#data-types

**Comment by pgulutzan** [comment]
It is on our wishlist to support the separate MessagePack type for binary: https://github.com/tarantool/tarantool/issues/1629. This of course does not mean that Tarantool doesn't store binary data, since the string type (as documented) can be any sequence of bytes.
