### ISSUE TITLE
box.cfg.rows_per_wal was deprecated and removed

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#1311]
https://github.com/tarantool/tarantool/commit/c7a382af0d35a36f8e2b05a09faeb9d877df947c

It is on 1.10.3-138-gd52e90601+, 2.1.2-173-gb60872023+, 2.2.1-49-ge59b34353+, 2.3.0-94-gc7a382af0+, all 2.4+.

https://github.com/tarantool/tarantool/commit/c60129200caa47bae87098a88f0bc7e0bb0ec3a6

It is on 2.2.1-86-gb2b6eb546+, 2.3.0-148-gc60129200+, all 2.4+.

**Comment by Totktonada** [comment]
https://github.com/tarantool/tarantool/issues/3762

**Comment by Onvember** [comment]
fixed in https://github.com/tarantool/doc/pull/1339
