### ISSUE TITLE
Add details to prometheus documentation

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#1327]
https://github.com/tarantool/metrics/tree/master/metrics/plugins/prometheus

The readme is too concise. It's not enough for a beginner to set up prometheus metrics.

**Comment by kokh-an** [comment]
Working sample for prometheus metrics:

```
metrics = require('metrics')
metrics.enable_default_metrics()

prometheus = require('metrics.plugins.prometheus')
metrics = require('http.server').new('0.0.0.0', 8080)
router = require('http.router').new({charset = "utf8"})
metrics:set_router(router)
router:route( { path = '/metrics' }, prometheus.collect_http)
metrics:start()
```

**Comment by lenkis** [comment]
https://github.com/tarantool/metrics/pull/68

**Comment by patiencedaur** [comment]
Done
https://www.tarantool.io/en/doc/latest/book/monitoring/plugins/
