### ISSUE TITLE
Provide a getting started doc for using metrics

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#1328]

**Comment by lenkis** [comment]
https://grafana.com/grafana/dashboards/12341

https://github.com/tarantool/metrics

**Comment by artur-barsegyan** [comment]
The idea sounds good. 

I have looked for metrics examples or descriptions at the site and get nothing. We absolutely need it. 

Sometimes I get feedback from clients about missed metrics documentation, missed Grafanfa dashboard. Some of those clients who had found the tarantool/metrics repo are not understood, how to use it via README.

**Comment by lenkis** [comment]
https://www.tarantool.io/en/doc/2.4/book/monitoring/
