### ISSUE TITLE
Luarocks on Centos

### ISSUE THREAD

**Issue by zloidemon** [tarantool/doc#133]
Please add a bit more information about installation luarock to centos like [this](http://www.tecmint.com/how-to-enable-epel-repository-for-rhel-centos-6-5/) in main installation guide.

**Comment by lenkis** [comment]
@zloidemon I've recently revised documentation on installing Tarantool modules. Info that concerns LuaRocks usage now resides in this README: https://github.com/tarantool/rocks/blob/gh-pages/README.md 

I see nothing CentOS-specific in LuaRocks native docs: https://luarocks.org/#quick-start

Please say which kind of info re CentOS is missing in our docs.

**Comment by zloidemon** [comment]
CentOS actually hasn't luarocks on board repositories. Our workflow will contain a few actions:

1. Added extra repository to correct version of CentOS/RHEL
2. Update repositories
3. Install luarocks from the repository

All CentOS machines required to install one extra package which in that case deploys configuration EPEL repository.

Activation repository on CentOS 7
```
## RHEL/CentOS 7 64-Bit ##
# wget http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm
# rpm -ivh epel-release-7-9.noarch.rpm
# yum update
```

Install luarocks loks like standard installation of package `yum install luarocks`.
