### ISSUE TITLE
Improve doc search experience

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#1346]
We need Google-search features in our local doc/site search:
- [x] Highlight search keywords in doc text
- [x] Show 1-2 lines of context for each search result
- [x] Make it possible to search for an exact substring (like only "too long" entries, not all of "too" + "long" + "too long" + "long too")
- [x] Enable Russian search

**Comment by artur-barsegyan** [comment]
The tasks were done. The result of that is not obvious convenient and therefore we need research. This ticket should be closed and will be related with a new one.
