### ISSUE TITLE
Cartridge rpm/deb deployment doc is not clear

### ISSUE THREAD

**Issue by knazarov** [tarantool/doc#1347]
There is currently a section that describes configuration of rpm/deb based deployment:

https://www.tarantool.io/en/doc/1.10/book/cartridge/cartridge_dev/#deploying-as-an-rpm-or-deb-package

In this section there is step (4) that references another section describing configuration in every possible detail. This confuses new users.

What I suggest is rewrite step (4), and tell the user that they need to create a file called /etc/tarantool/conf.d/instances.yml and put and example of that file inline. Then you can give a link that describes the structure of instances.yml in detail.

**Comment by lenkis** [comment]
Same for other sections on that page (deploy from targz, from sources).
