### ISSUE TITLE
Document that fiber.yield and fiber.sleep may raise an exception

### ISSUE THREAD

**Issue by RunsFor** [tarantool/doc#1364]
There is a frequent [misunderstanding](https://stackoverflow.com/questions/62262458/tarantool-fiber-behavior-with-fiber-yield-and-fiber-testcancel) in tarantool community with how `fiber.yield`, `fiber.testcancel` and `fiber.cancel` works. I believe it happens, because documentation says nothing about `yield` and `sleep` may actually raise an exception. This may form wrong assumptions about how fiber model works.

I suggest add an "exception" section to `yield` and `sleep` functions documentation. Some examples would be nice to have.

**Comment by pgulutzan** [comment]
I will add this in section "Module fiber" if nobody objects in the next few days.

Warning: yield() and sleep() can fail (return an error).
For example, this function has a loop which repeats until cancel() happens.
The last thing that it will print is 'before yield', which demonstrates
that yield() failed, the loop did not continue until testancel() failed.
fiber = require('fiber')
function function_name()
  while true do
    print('before testcancel')
    fiber.testcancel()
    print('before yield')
    fiber.yield()
  end
end
fiber_object = fiber.create(function_name)
fiber.sleep(.1)
fiber_object:cancel()

**Comment by olegrok** [comment]
But no only yield and sleep could raise. All operations that yield implicitly could raise such error as well.

**Comment by RunsFor** [comment]
> I will add this in section "Module fiber" if nobody objects in the next few days.

I would also point it out in the function documentation in "Exception" section. As an example, [fiber.kill](https://www.tarantool.io/en/doc/2.3/reference/reference_lua/fiber/#fiber-kill) has such section.
