### ISSUE TITLE
[2pt] Update coding guidlines

### ISSUE THREAD

**Issue by kyukhin** [tarantool/doc#1406]
It was decided to increase number of columns in comments from 66 to 80 columns.Please update https://www.tarantool.io/en/doc/1.10/dev_guide/c_style_guide/

**Comment by lenkis** [comment]
@kyukhin can't spot the document to fix, please clarify

**Comment by kyukhin** [comment]
Done. Link updated.

**Comment by veod32** [comment]
Is it OK? Please review https://github.com/tarantool/doc/pull/1449
