### ISSUE TITLE
[60pt] Highlight box.cfg parameters origin version 

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/doc#1415]
## Motivation
Tarantool evolves and new features have come. When a user reads about the needed feature, he looks at the version where that feature is available. Now, the user first needs to check all supported versions at the site and find the last mention about that feature. In the case of 1.10.0 — 1.10.latest minor releases, the user can't have the ability to find the feature origin. 

Brief motivation list:

1. New features are not marked about origin version
2. Sometimes users don't see the version marker at the documentation page/URL link.

> Vadim, [12:23:57 PM]:
Спасибо. А есть пример использования где-то?
Eugene, [12:28:05 PM]:
https://www.tarantool.io/en/doc/2.3/reference/reference_lua/box_sql/
Vadim, [12:39:08 PM]:
А с какой версии это? У меня 2.2. сейчас и box.prepare там нет

3. Tarantool's 1.10 users don't have any mentions about changes in API or behavior at all. Only through release notes.

## What need to do
Mark all box and Cartridge's parameters with mentioning about origin version

**For example:**
```lua
box.prepare(sql-statement)
```
*New in version 2.3*

**Comment by Totktonada** [comment]
I vote for exact four-digit versions to overcome any possible ambiguity.

**Comment by Totktonada** [comment]
The following features should help the Documentation Team to obtain tarantool versions, which corresponds to a particular feature or behaviour change:

* https://github.com/tarantool/docbot/issues/6
* https://github.com/tarantool/docbot/issues/7
