### ISSUE TITLE
cartridge: Broken link in configuration basics

### ISSUE THREAD

**Issue by RunsFor** [tarantool/doc#1416]
I accidentally found broken links in [configuration basics](https://www.tarantool.io/en/doc/2.3/book/cartridge/cartridge_dev/#configuration-basics) section and then ran a simple online test at validator.w3.org:

<img width="821" alt="Screenshot 2020-07-21 at 10 33 08" src="https://user-images.githubusercontent.com/2008930/87999246-94e99100-cb3d-11ea-9b8d-27f2cb868348.png">

**FYI**: There are also various link-checker tools. Quick googling gives [django-linkchecker](https://pypi.org/project/django-linkcheck/). Besides, its nice to have CI reports, which regularly scans website for broken links.

**Comment by artembo** [comment]
@lenkis just fix the broken links in the corresponding source repositories:  
1. https://github.com/tarantool/cartridge/blame/master/rst/topics/clusterwide-config.rst#L27  
3. https://github.com/tarantool/cartridge/blame/master/rst/topics/clusterwide-config.rst#L28  
4. https://github.com/tarantool/cartridge/blob/master/rst/cartridge_dev.rst#installing-tarantool-cartridge  

2. Is not related to the rst. https://gitlab.com/tarantool/tarantool.io/tarantool.io/-/issues/200  

@RunsFor Thanks for django-linkchecker, i'll definitely include this or similar tool in the website testing pipeline.
