### ISSUE TITLE
[1pt] Instruction for releasing a docker container is not actual

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#1427]
https://www.tarantool.io/en/doc/2.5/dev_guide/release_management/#how-to-release-a-docker-container

We should either update it or remove. @avtikhon knows the actual process.

**Comment by veod32** [comment]
@Totktonada @avtikhon 
>We should either update it or remove. 
Does this refer only to the 2.5 release? if not, pls specify the versions the doc update should be done for.

**Comment by Totktonada** [comment]
It is about processes. I don't know why it is present in per-release sections on the website, not as some common acritcle.

**Comment by veod32** [comment]
> It is about processes. I don't know why it is present in per-release sections on the website, not as some common acritcle.

Ok, we can decide later how to re-organise the content if necessary.

**Comment by veod32** [comment]
Reviewed & discussed with @Totktonada:
- description in the topic ```/dev_guide/release_management/#how-to-release-a-docker-container```  is really outdated; new process is still under development;
- so, decided to remove the topic for the time being and get back to updating the content when the new process will be settled up (approx. September 2020)

**Comment by kyukhin** [comment]
It was decided to remove it from public.

**Comment by veod32** [comment]
The issue will be closed upon completion of https://github.com/tarantool/doc/issues/1420
