### ISSUE TITLE
"html" instead of "http"

### ISSUE THREAD

**Issue by Satbek** [tarantool/doc#1439]
<img width="566" alt="Screenshot 2020-08-06 at 15 20 14" src="https://user-images.githubusercontent.com/26044679/89531095-553ace80-d7f8-11ea-88de-046b46331eb7.png">
https://www.tarantool.io/en/download/rocks#networking

**Comment by lenkis** [comment]
Duplicate of https://github.com/tarantool/doc/issues/1440
