### ISSUE TITLE
Some chapters of dev guideline should be version independant

### ISSUE THREAD

**Issue by kyukhin** [tarantool/doc#1442]
We have a guideline for developers for each supported version, e.g
https://www.tarantool.io/en/doc/1.10/dev_guide/

Some chapters should be stuck to version, like C Module API or snapshot format (it might change theoretically). However there're chapters which existence under version is confusing:
- "Build and contribute"."Release management"
-  "Guidelines".*

Let's extract them from within any versions in URL and doc hierarchy.

**Comment by lenkis** [comment]
It's hard to implement within the current documentation paradigm. The best we can do is to move version-agnostic doc sources away to another repo, but this will make the doc even harder to maintain. Let's drop the initiative for now.
