### ISSUE TITLE
Don't redirect from a "latest" URL

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#1452]
A "latest" URL (say, https://www.tarantool.io/en/doc/latest/) [redirects](https://github.com/tarantool/doc/issues/453) to the corresponding version specific URL (https://www.tarantool.io/en/doc/2.3/). I propose to keep /latest/ in the URL (don't redirect, but have a page copy), because it is intuitive for a user (don't require knowledge about our releases), it eases copying of "latest" URL (which is most actual) and it is how others work (say, readthedocs).

We should not confuse Google and Yandex crawlers, so I propose to add `<link rel="canonical" href="<...>/latest/<...>"/>` to our webpages. We can also add the `og:url` OpenGraph tag, which (I guess) serves the same purpose. The relevant search engines documentation:

* https://support.google.com/webmasters/answer/139066?hl=en
* https://yandex.ru/support/webmaster/robot-workings/canonical.html?lang=en

`/latest/` should be canonical URL (not `/2.5/` or so), because of several reasons:

* Search engines will show a canonical URL in search results.
* The latest page is most actual and provide more information; it is good to point users here.
* It seems readthedocs doing something similar.

**Comment by Totktonada** [comment]
@artembo Asked me whether it worth to implement this issue (and #1453) if we'll going the way proposed in #1415 (give versions where a feature or a parameter is present).

I guess #1415 is more like continuing effort and even if we'll decide to squash all documentation versions into one, it'll happen in some non-near future. But with this proposal we can resolve existing problems now, not in a future.

@lenkis You added the label 'raw idea'. Whether it assumes some actions from me to make it an 'accepted idea' or kinda? Or it requires internal dicussion within the Documentation Team (and you'll update us with results later)?

**Comment by artur-barsegyan** [comment]
Also, we should edit current URLs to the new one from the landing page.

**Comment by artur-barsegyan** [comment]
@artembo has implemented this ticket. 

I see that the current label **"latest"** isn't sufficient for understanding: "What is exactly the version of Tarantool is described?". Maybe we should add the reminder like "latest (2.6)"?

**Comment by Totktonada** [comment]
In the dropping list 'version' at left-top corner? I don't mind.

**Comment by artur-barsegyan** [comment]
> In the dropping list 'version' at left-top corner? I don't mind.

Yep, in that list.

**Comment by Totktonada** [comment]
Google search on "ibuf tarantool" (without quotes) directs me to the [1.10 page](https://www.tarantool.io/ru/doc/1.10/reference/reference_lua/buffer/). So I checked what is canonical link for this page:

```
$ curl -s https://www.tarantool.io/ru/doc/1.10/reference/reference_lua/buffer/ | grep canonical
$ curl -s https://www.tarantool.io/ru/doc/1.10/reference/reference_lua/buffer/ | grep og:url
<meta property="og:url"         content="https://www.tarantool.io/">
```

No canonical link, strange OpenGraph URL tag. Is it intentional (please give a reason if so) or the task is implemented partially ATM (and the remaining work is planned)?

**Comment by artembo** [comment]
@Totktonada check it up again please.

```bash
$ curl -s https://www.tarantool.io/ru/doc/1.10/reference/reference_lua/buffer/ | grep canonical
<link rel="canonical" href="https://www.tarantool.io/ru/doc/latest/reference/reference_lua/buffer/" />
```
Is it an expected behaviour?

As for opengraph, it is not implemented yet but there's an issue for the refactoring all the metatags across the website pages.
https://gitlab.com/tarantool/tarantool.io/tarantool.io/-/issues/197

**Comment by Totktonada** [comment]
Nice, thanks! And now Google search for "ibuf tarantool" shows the [latest page](https://www.tarantool.io/ru/doc/latest/reference/reference_lua/buffer/) (in Russian, but it is how Google search often works).

From USA IP Google search gives [2.3 page](https://www.tarantool.io/en/doc/2.3/reference/reference_lua/buffer/). I looked over the cached version and it does not contain the canonical link. It seems, Google's crawler does not collect it yet. Can we [ask Google](https://developers.google.com/search/docs/advanced/crawling/ask-google-to-recrawl?hl=en) to refetch the website?

**Comment by Totktonada** [comment]
The English search now gives the latest page for "ibuf tarantool". So it seems we can mark the issue as resolved.
