### ISSUE TITLE
Consider deploying the latest documentation

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#1453]
This is follow up for #1452.

My proposal is simple:

* Create `master` branch (and set it as default on GitHub).
* Deploy it to https://www.tarantool.io/en/doc/latest/
* Merge PRs to master and cherry-pick downward.

It is how we work in tarantool itself (we moved from upward merges to downward cherry-picks).

Why I think it is neat:

* Fast deliver the new documentation to a user; keep it aware of the new cool features.
* No those weird git log graphs (which nobody actually undestand) and disgusting merge conflicts (which should be no-op, but sometimes hide real changes).
* It would be more intuitive how to contribute to the documentation via GitHub PR.
* `Closes #xxx` / `Fixes #xxx` will work automatically on GitHub (because `master` is default and because most of changes will go through `master`).

Any downsides? I see no one.

Note for maintainers: please, use 'git cherry-pick -x` when cherry-picks changes downward from master: it allows to track what is going from here.

**Comment by kyukhin** [comment]
We definitely should implement that.

**Comment by NickVolynkin** [comment]
Looks like we've done it.
