### ISSUE TITLE
NoSQLBench needs clear instructions how to run it

### ISSUE THREAD

**Issue by kyukhin** [tarantool/doc#1455]
Title page of our main benchmark [1] contains short feature list.
I guess it'll be much more useful to have instructions on how to actually
run it against a given Tarantool and acquire nice-formatted results.

[1] - https://github.com/tarantool/nosqlbench

**Comment by lenkis** [comment]
@kyukhin please say what result you expect: more detailed readme in the nosqlbench repo?

**Comment by kyukhin** [comment]
Yes, something like that. I need clear step-by-step instructions on how can I run the benchmark against tarantool I have.

**Comment by pgulutzan** [comment]
@kyukhin, on August 12 I emailed a draft to @lenkis along with a few notes and questions. Subject line = Issue#1455 NoSQLBench needs clear instructions how to run it. CC line = K. Yukhin, V. Shpilevoy.

**Comment by Totktonada** [comment]
@pgulutzan Please, add me too.

**Comment by pgulutzan** [comment]
@lenkis: As you can see, I submitted a pull request. There has been no reply yet, and I do now know who owns or maintains this repository. So we might have to wait for a long time.

**Comment by pgulutzan** [comment]
Thanks to @Totktonada who arranged permission for docs folks to https://github.com/tarantool/nosqlbench.
I made the README.md change there.
I have not yet closed this issue but I will now remove the "need feedback" tag.

**Comment by pgulutzan** [comment]
@kyukhin: https://github.com/tarantool/nosqlbench now has a README.md with "step-by-step instructions as you requested.  If there are no objections then I will close his issue after 10 more days.

**Comment by Totktonada** [comment]
I looked over the new README several days ago and (despite we all have our own preferences) it answers the question 'how to run it against given tarantool'. So I think the issue can be closed.
