### ISSUE TITLE
Add link to the current version of documentation on doc pages for previous versions

### ISSUE THREAD

**Issue by ligurio** [tarantool/doc#1459]
The problem: google shows links to the old documentation in a search results and due to this users will read outdated docs.
Would be good to add block with warning and link to the current version. Something like: "This documentation is for an unsupported version of Tarantool. You may want to view the same page for the current version, or one of the supported versions listed above instead."

For example:
- postgresql https://www.postgresql.org/docs/9.1/index.html
- cmake https://cmake.org/cmake/help/v3.15/

**Comment by Totktonada** [comment]
The block with the warning for outdated (not supported) tarantool versions is the good idea per se.

However I hope that #1452 will resolve the main problem with search engines.

**Comment by lenkis** [comment]
To discuss with @artembo

**Comment by NickVolynkin** [comment]
Won't fix, will merge versions to get 1.x and 2.x branches.
