### ISSUE TITLE
nothing about synchronous replication in introduction

### ISSUE THREAD

**Issue by ligurio** [tarantool/doc#1469]
> Tarantool supports asynchronous replication, locally or to remote hosts. The replication architecture can be master-master, that is, many nodes may both handle the loads and receive what others have handled, for the same data sets.

We support synchronous replication too.

Source: https://www.tarantool.io/en/doc/2.5/intro/

**Comment by artur-barsegyan** [comment]
This paragraph will be rewritten totally in the nearest future.

**Comment by lenkis** [comment]
Part of https://github.com/tarantool/doc/issues/1467

**Comment by patiencedaur** [comment]
The section has been rewritten. Closing.

**Comment by patiencedaur** [comment]
@ligurio The section is a practical workshop. Unless there is a replication exercise included in Getting Started, I don't see a place where replication could be mentioned in this section. Perhaps you have another vision—would you like an entry-level tutorial to be included in the Getting Started pages?

**Comment by ligurio** [comment]
> The section is a practical workshop. Unless there is a replication exercise included in Getting Started, I don't see a place where replication could be mentioned in this section. Perhaps you have another vision—would you like an entry-level tutorial to be included in the Getting Started pages?

Thanks for explanation! Well, let's keep it as is.
In a current "Getting started" cluster is something that can be managed by Cartridge and provides CRUD interface. "Getting started" says nothing about low-level things like async/sync replication, leader election and other.
