### ISSUE TITLE
document buffer.static_alloc

### ISSUE THREAD

**Issue by olegrok** [tarantool/doc#1486]
Initially it was introduced here: https://github.com/tarantool/tarantool/commit/7fd6c8096343ca254fec10c2ce8a8233ebe47028

But our doc (https://www.tarantool.io/ru/doc/2.3/reference/reference_lua/buffer/) doesn't contain any information

**Comment by lenkis** [comment]
Please double-check the version of origin.

**Comment by olegrok** [comment]
It's a 2.2 feature

**Comment by Gerold103** [comment]
Please, don't do that. It is not a public API. If something wasn't documented, it is likely it was done intentionally. Also please, double check such things with the core team before documenting them.

**Comment by olegrok** [comment]
It could be useful for some FFI bindings where we allocate some memory. And I hope it could be a public function.

But ok, seems it should be discussed separately - let's close this issue.
