### ISSUE TITLE
New doc structure: scripting

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#1490]
Need to set up conf.py according to the new structure. We need to keep the old structure as well.

In a discussion with @veod32 and @lenkis we decided to rename the old index.rst files as index_old.rst.

So, we need two conf.py sphinx-doc files with settings which will allow to build the new structure with existing make commands. The new make commands for building the documentation with old structure will get `-old` suffix.

Also we have to set `excluded_patterns` in both conf.py files to not include unused index files.

**Comment by artembo** [comment]
After the structure modifications we have some new issues. Need to fix them:

- [ ] fix broken image paths
- [ ] fix cartridge and vshard doc
- [ ] fix "getting started" and "replication"
- [ ] fix duplicated "Application server"
- [ ] leave only first level chapters on main page
- [ ] fix breadcrumbs and toctree for Reference
