### ISSUE TITLE
Mark deprecated releases in the table

### ISSUE THREAD

**Issue by kyukhin** [tarantool/doc#1509]
Looking at the table [here](https://www.tarantool.io/en/doc/2.5/dev_guide/release_management/#release-list) I feel like any of releases mentioned is actual, but this is not true. Please mark actual (or deprecated) releases. We also need to keep it actual when new releases are out.

**Comment by Totktonada** [comment]
See also #1025.

**Comment by patiencedaur** [comment]
Related issue: https://github.com/tarantool/doc/issues/749

**Comment by patiencedaur** [comment]
There is no such table. A releases lifetime table is in development in #1025, and the page "How to make a minor release" has been removed in https://github.com/tarantool/doc/pull/2690. Closing.
