### ISSUE TITLE
mopinion: tarantoolctl doc get worse since 1.10

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#1512]
https://app.mopinion.com/dashboard/inbox/detail/3100937

Почему текст стал хуже с версии 1.10? Вообще ничего не понятно по командам tarantoolctl rocks, особенно для тех, которые нужны для сборки роков.

https://www.tarantool.io/ru/doc/2.5/reference/tarantoolctl/

**Comment by patiencedaur** [comment]
Inconstructive feedback. Closing.
