### ISSUE TITLE
[4pt] mopinion: Warn that a select may freeze tarantool

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#1513]
https://app.mopinion.com/dashboard/inbox/detail/3083780

space_object:select([key[, options]]) напишите, что это может повесить тарантул. Дайте ссылку на space:pairs

https://www.tarantool.io/en/doc/1.10/reference/reference_lua/box_space/#box-space-select

**Comment by Onvember** [comment]
My solution is based on the part of discussion from Tarantool Sever chat:

Igor Munkin, [18.09.20 12:29]
Я просто не понимаю насколько это правильно, такие вещи выносить прям в доку. Да, это полезно, но как-то странно, мол "У нас есть select, но он может забрать всю базу на время, поэтому используйте pairs". У пользователя встает резонный вопрос: и нахера такой select нужен?

Igor Munkin, [18.09.20 12:42]
У нас, кстати, есть секция (первый раз попользовал поиск на сайте) вот тут: https://www.tarantool.io/en/doc/latest/book/box/atomic/#cooperative-multitasking.

> Cooperative multitasking
> 
> Cooperative multitasking means: unless a running fiber deliberately yields control, it is not preempted by some other fiber. But a running fiber will deliberately yield when it encounters a “yield point”: a transaction commit, an operating system call, or an explicit “yield” request. Any system call which can block will be performed asynchronously, and any running fiber which must wait for a system call will be preempted, so that another ready-to-run fiber takes its place and becomes the new running fiber.
> 
> This model makes all programmatic locks unnecessary: cooperative multitasking ensures that there will be no concurrency around a resource, no race conditions, and no memory consistency issues.
> 
> When requests are small, for example simple UPDATE or INSERT or DELETE or SELECT, fiber scheduling is fair: it takes only a little time to process the request, schedule a disk write, and yield to a fiber serving the next client.
> 
> However, a function might perform complex computations or might be written in such a way that yields do not occur for a long time. This can lead to unfair scheduling, when a single client throttles the rest of the system, or to apparent stalls in request processing. Avoiding this situation is the responsibility of the function’s author.

Kirill Yukhin, [18.09.20 12:55]
можно просто написать простоя предложение: Селект не илдает. Что такое илдает - см. пасту Игоря

**Comment by artur-barsegyan** [comment]
@Onvember бегло посмотрел содержание коммитов. 

Давай сделаем так, чтобы там явно было написано, что это может повесить Tarantool на больших спейсах.
