### ISSUE TITLE
[1pt] mopinion: Document missing fio flags

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#1518]
https://app.mopinion.com/dashboard/inbox/detail/3081522

Для версии 2.2 в модуле fio отсутствует часть заявленных флагов, например, нет O_TMPFILE.

https://www.tarantool.io/ru/doc/2.3/reference/reference_lua/fio/

**Comment by lenkis** [comment]
TODO: check if this must be also fixed for earlier versions

**Comment by Onvember** [comment]
[fio.open()](https://www.tarantool.io/ru/doc/2.2/reference/reference_lua/fio/#lua-function.fio.open) contains all the flags described in [fio.c](https://github.com/tarantool/tarantool/blob/98e29c0f0c8e563fa3e95bfb0affd1a5a5cd85e6/src/lua/fio.c), including O_TMPFILE.
