### ISSUE TITLE
[8pt] mopinion: Remove local dir mount from docker instructions in GS

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#1519]
https://app.mopinion.com/dashboard/inbox/detail/3075526

В команде запуска контейнера для нового пользователя предлагается сразу смонтировать папку с хоста. Я бы не стал для новичков это предлагать, потому что во-первых докер создает волюм по умолчанию если этого не указать, а во-вторых пользователю еще нужно найти где создать эту папку на хосте, и поставить правильные пермишены на ней (что не указано тут вообще).

https://www.tarantool.io/en/doc/latest/getting_started/getting_started_db/

**Comment by tsafin** [comment]
Не очень понимаю о чем речь, о каком "томе, который создает докер по умолчанию"? Все данные, которые сохраняются в контейнере, эфемерны. И будут удалены сразу после останова контейнера. Ничего не персистится вне контейнера. 

Рекомендуемый подход с пробрасыванием томов на хостовой системе - _стандартная_ идиома при работе с базами данных под Dockerом, чтобы базы данных и журналы сохранялись между запусками контейнеров, переживая их.

**Comment by artur-barsegyan** [comment]
Я предлагаю сделать как в Redis:

**start a redis instance**
```$ docker run --name some-redis -d redis```

**start with persistent storage**
```$ docker run --name some-redis -d redis redis-server --appendonly yes```

If persistence is enabled, data is stored in the VOLUME /data, which can be used with --volumes-from some-volume-container or -v /docker/host/dir:/data (see docs.docker volumes).

For more about Redis Persistence, see http://redis.io/topics/persistence.

**Comment by tsafin** [comment]
(тут уже начинается вкусовщина) мне кажется (кажеься), что начинающему пользователю надо делать проще и надежней. И именно запуск с персистентными томами через `-v` в докере - самый правильный способ не потерять данные от незнания всех специфик работы докера с виртуальной файловой системой.

То есть текущий рекомендуемый способ - хороший

**Comment by artur-barsegyan** [comment]
> (тут уже начинается вкусовщина) мне кажется (кажеься), что начинающему пользователю надо делать проще и надежней. И именно запуск с персистентными томами через `-v` в докере - самый правильный способ не потерять данные от незнания всех специфик работы докера с виртуальной файловой системой.
> 
> То есть текущий рекомендуемый способ - хороший

А что делать с тем, если у человека не выставлены permissions нужные на текущую папку? Т.е. Tarantool не сможет записать снапы в текущую дирректорию.

По идее в подходе с Volume таких проблем не должно быть

**Comment by tsafin** [comment]
> А что делать с тем, если у человека не выставлены permissions нужные на текущую папку? Т.е. Tarantool не сможет записать снапы в текущую дирректорию.
> 
> По идее в подходе с Volume таких проблем не должно быть

Не понимаю, почему подход с (внешне созданными?) томами должен лечить проблему с правами доступа? Это ровно тот же механизм, что и при пробросе из командной строки. Просто для него нужно сделать больше подготовительных манипуляций.

Я, таки предлагаю, оставить в нашей документации самый первый рецепт, самым простым? С минимальными подготовительными шагами, и в тоже время обеспечивающий персистентность данных.
