### ISSUE TITLE
[3pt] mopinion: Add an overview for instances.yml features

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#1520]
https://app.mopinion.com/dashboard/inbox/detail/3033859

Добавьте описание instances.yml, что там доступно . Как оно использовать cartridge start , если непонятно как его настроить.

https://www.tarantool.io/en/doc/1.10/book/cartridge/cartridge_cli/#starting-stopping-an-application-locally

**Comment by veod32** [comment]
Besides the link in the description, there are some other places where this topic is discussed:
https://www.tarantool.io/en/doc/latest/book/cartridge/topics/clusterwide-config/#configuration-basics
https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_dev/#starting-stopping-instances
https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_admin/#deploying-the-cluster
https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_api/modules/cartridge.argparse/

Proposal is to collect the info on the topic and organise it in a more structured way (possibly, cross-refer. in diff. guides)

**Comment by veod32** [comment]
branches with updates
https://github.com/tarantool/cartridge-cli/tree/veod-gh-1520-cli

**Comment by artur-barsegyan** [comment]
Договорились раздробить на несколько тикетов. Первый — замержить, второй положить в беклог.

**Comment by veod32** [comment]
Follow-up issue: https://github.com/tarantool/doc/issues/1651
