### ISSUE TITLE
tarantool/index.html improvements

### ISSUE THREAD

**Issue by kostja** [tarantool/doc#153]
![screenshot from 2017-01-29 19-21-45](https://cloud.githubusercontent.com/assets/482910/22405753/a9424e80-e658-11e6-8286-fcd817ae0c42.png)

* make sure we have our tagline in the site title
* update meta keywords on all pages.

**Comment by bigbes** [comment]
* Tagline is in the site title
* Meta keywords [aren't used anymore](http://convertmonster.ru/blog/seo-blog/meta-keywords-kljuchevye-slova-znachenie/)

  > Ключевые слова meta keywords изначально существенно влияли на релевантность страниц сайта, что активно пользовались для SEO оптимизации сайта и его вывода по необходимым ключевым запросам в топ поисковой выдачи. В результате, поисковые системы либо вовсе перестали учитывать meta тег keywords при индексации, либо свели его значение к минимуму.
