### ISSUE TITLE
mopinion: Add warnings re using fiber-modifying funcs via ffi

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#1531]
https://app.mopinion.com/dashboard/inbox/detail/2994327

очется видеть предупреждение большими буквами что использование функций меняющих файбер через ffi крашит тарантул -- https://github.com/tarantool/tarantool/issues/1700

https://www.tarantool.io/ru/doc/2.3/book/app_server/cookbook/#ffi-printf-lua

**Comment by igormunkin** [comment]
Well, now switching fibers via LuaJIT FFI doesn't lead to platform failure. As a result of tarantool/tarantool@2711797 the platform either proceed running or stops to prevent further misexecution.

**Comment by patiencedaur** [comment]
The problem is fixed in the code. No changes in the doc are needed. Closed.
