### ISSUE TITLE
mopinion: Missing info in what's new for 2.5

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#1533]
https://app.mopinion.com/dashboard/inbox/detail/2998493

если это версия 2.5 - где абзац с описанием изменений от версии 2.4.1 ? даже урл намекает - тут страница с тем что изменилось с версией 2.5!

https://www.tarantool.io/ru/doc/2.5/whats_new/

**Comment by patiencedaur** [comment]
We now have the Major features pages: https://www.tarantool.io/en/doc/latest/release/major-features/
Closed
