### ISSUE TITLE
mopinion: Add details on conn:eval

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#1534]
https://app.mopinion.com/dashboard/inbox/detail/2999141

В conn:eval не описана работа с обычными именованными аргументами (или факт того, что их применять нельзя и надо пользоваться '...')

https://www.tarantool.io/ru/doc/2.2/reference/reference_lua/net_box/#net-box-eval

**Comment by Onvember** [comment]
This note is pointless because in Lua it is obligatory to wrap named parameters into maps. See https://www.lua.org/pil/5.3.html
