### ISSUE TITLE
mopinion: Restructure authentication text

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#1537]
https://app.mopinion.com/dashboard/inbox/detail/3010910

Очень много текста и не понятно что из этого нужно тебе, а что нет. Сложной найти информацию.

https://www.tarantool.io/ru/doc/2.2/book/box/authentication/#owners-and-privileges

**Comment by patiencedaur** [comment]
The text in the section is split into quite manageable blocks. There are examples for three use cases. I think this is closed.
