### ISSUE TITLE
Multi-version manual

### ISSUE THREAD

**Issue by kostja** [tarantool/doc#154]
We need a separate manual for Tarantool 1.6, 1.7, 1.8.
Hence we need to switch our manual/web-site building system to support multiple versions. 

I propose we have a configuration file  for each branch which tells the build system which parts of the web site to build from that branch, so that we can push to doc branch 1.6 and expect only the 1.6 manual to be rebuilt and published at tarantool.org/doc/1.6, while for 'master' branch the entire web site is rebuilt and published.

**Comment by bigbes** [comment]
Pushed
