### ISSUE TITLE
[40pt] Document new transactional manager

### ISSUE THREAD

**Issue by alyapunov** [tarantool/doc#1558]
In [0018398](https://github.com/tarantool/tarantool/commit/0018398db632b3d0131ca8dcc1f65315039bbf98) (in master) a new important feature was added to tarantool, and it should be documented. I'm not sure I'm doing the documentation request properly, please correct me.
I would describe the feature in the following words (but I don't know which part of documentation it must be added to):

Now there is an options `memtx_use_mvcc_engine` in `box.cfg`, false by default. If set to true it enables transactional manager. It allows yielding inside a memtx transaction (that was explicitly phohibited before).
The transactional manager is designed for isolation of concurrent transactions. It consists of two parts - MVCC engine and conflict manager. MVCC engine provides personal read views for transactions (if necessary) and conflict manager tracks transactions' changes and determines their correctness in serialization order. Of course, once yielded, a transaction could interfere with other transactions and could be aborted due to conflict.

**Comment by veod32** [comment]
The ticket can be related to https://github.com/tarantool/doc/issues/1422 in a sense of replacing the description of the previous implementation in 2.5 documentation. Needs research on this point.
