### ISSUE TITLE
[8pt] Make a new section called "Contributing"

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/doc#1571]
After structure refactoring, we need a parent section for pages:
- [Build and Contribute](https://www.tarantool.io/en/doc/latest/dev_guide/build_contribute_index/
)
- [Guidelines](https://www.tarantool.io/en/doc/latest/dev_guide/guidelines_index/)

I suggest creating the "Contributing" section. The main text for that section will be a new Contributing page with important links and intros. [Check it out.](https://docs.google.com/document/d/1FvmF1zlQNoGzBJQii_Fc2JmilwjEqyZjefuECdPTdv4/edit#heading=h.g059z2tqecxy)

Lost pages should be hosted here.

**Important:** Of course, old links should work.

**Comment by lenkis** [comment]
+ added a new topic "How to be involved"

**Comment by lenkis** [comment]
Closed via https://github.com/tarantool/doc/pull/1585
