### ISSUE TITLE
mopinion: Clarify metrics output endpoint

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/doc#1587]
https://app.mopinion.com/survey/inbox/detail/3341548

Не понятно при использовании роли катриджа по какому url можно получить метрики.

https://www.tarantool.io/en/doc/latest/book/monitoring/getting_started/#cartridge-role

**Comment by Onvember** [comment]
fixed in https://github.com/tarantool/metrics/commit/563d012ec7d1962e64f069904abf10532026831e
