### ISSUE TITLE
Remove space:inc() and space:dec()

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/doc#16]
Functions inc() and dec() were removed from tarantool by https://github.com/tarantool/tarantool/issues/1289. Please remove this functions from 1.7 documentation and deprecate in 1.6:

- https://tarantool.org/doc/book/box/box_space.html#lua-function.space_object.inc
- https://tarantool.org/doc/book/box/box_space.html#lua-function.space_object.dec

**Comment by bigbes** [comment]
Also, add that `upsert` (+ `get` if you need retval) is replacement for this operations, that works fine on async master-master cluster and have comparable perfomance.

**Comment by pgulutzan** [comment]
Functions inc() and dec() are removed from documentation, I added nothing about upsert.
