### ISSUE TITLE
Make an attention note for Docker Getting Started

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/doc#1603]
All steps are described here:
https://stackoverflow.com/questions/64178499/tarantool-does-not-start-due-to-disk-write-error

We need to make an attractive note at Docker GS because users can't launch Tarantool at Docker now.

**Comment by Onvember** [comment]
According to the discussion here https://github.com/docker/for-mac/issues/4964#issuecomment-711878496, this issue has been fixed. Do we still need this note, @artur-barsegyan?
