### ISSUE TITLE
Разделить референс box.schema, box.space, box.index на атомарные страницы

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/doc#1605]
Речь про страницы: box.schema, box.space, box.index. Вот [ссылка](https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_space/) на референс.

## Проблемы

1. Google и другие поисковики не поддерживают якори

Когда пользователь вводит в Google запрос: "tarantool create index", он получает выдачу на страницу с [box.index](https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_index/), однако сама функция создания находится далеко внизу на странице. И чтобы ее найти, нужно искать ее на странице через Ctrl-F, либо мотать до нее, либо найти через TOC. 

2.  Недружелюбные страницы

Текущие разделы написаны так, что новичок, который будет искать информацию о том, как создать спейс в разделе [box.space](https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_space/) не сможет ее найти. На этой странице нет описания того, как можно это сделать. 
  
## Как предлагаю решить

Разделить весь референс из box.schema, box.space и box.index на набор раздельных страниц. 
1 страница — 1 функция.

Пример можно посмотреть [тут](https://docs.mongodb.com/manual/reference/method/db.collection.insertOne/).

Перед финальной выкаткой на прод, мы поместим обновленные разделы на тестовый сервер и проведем интервью с пользователями.

3. Сложно читать референс на весь модуль

При добавлении нового материала на текущих страницах их с каждым разом становится тяжелее воспринимать. При разделенных страницах будет удобнее их читать, и будет логичная структура поддерживаться: в начале описания, в конце примеры использования.

## F.A.Q

- Где в структуре будут эти страницы?

    **Пример:**
    Будут в Reference -> Built-in modules reference -> box.space -> box.space.select 

-  Какие будут заголовки у этих страниц?

        box.space.**space_object**:create_index()
        box.space.**space_object**:insert()
    ---
        box.space.**space_object**.index.**index_object**:select()
    ---
        box.schema.create_space()  

- Что будет с текущими Reference страницами box.schema, box.space, box.index ?
   
    Для раздела `CRUD Operations` нужно будет либо вставить текущую, либо написать новую страницу, которая будет содержать самые важные моменты перед работой с базой и ссылки на рефернс функции. Вот [пример](https://docs.mongodb.com/manual/crud/) для вдохновления.

    Для раздела `Indexes` нужно будет написать примерно [такую](https://docs.mongodb.com/manual/indexes/) страницу (или собрать из текущих готовых). Она должна содержать первичные описания для самых важных действий с ссылками на соотв. референс функции.

**Comment by patiencedaur** [comment]
Done
