### ISSUE TITLE
'SQL beginners’ guide' vs 'SQL user guide' - what's the difference?

### ISSUE THREAD

**Issue by msiomkin** [tarantool/doc#1613]
What's the difference between these two sections/captions?

SQL beginners’ guide
SQL user guide

The latter redirects one line below (!!!) 'Getting Started' section. May be it should be renamed to 'Running SQL queries in Tarantool'.

And the first section is just an SQL tutorial as I understand. Do we really need it in our docs?

**Comment by pgulutzan** [comment]
If I go to the "SQL reference" page
https://www.tarantool.io/en/doc/latest/reference/reference_sql/sql/
I see five divisions:
SQL beginners' guide
SQL user guide
SQL statements and clauses
SQL PLUS LUA -- Adding Tarantool/NoSQL to Tarantool/SQL
SQL features


Originally SQL user guide was a separate document
https://docs.google.com/document/d/13okP75I6hFKm9fX2HOaEAExQ_WeftZQzuTChbd3zIwE/edit#
with heading
"SQL User Guide
[SQL user guide begins]
The User Guide describes how users can start up with SQL with Tarantool, and necessary concepts.
Getting started
"
Somewhere / somehow some lines were lost and headings were not marked.
So you are right, That's easy to see and easy to fix.

Originally there were four separate docs.google.com documents:
beginners' guide, user guide, reference, SQL Plus Lua. The idea was that there
would be a separate SQL manual divided into those four parts.
Eventually, though, it was decided to make it part of the main manual
in the place where you see it now, and so there is an
"SQL Reference" which is split into those parts (the fifth part had
a different origin).
You are right, it is not appropriate to have some non-reference
in something with that title. But that is just a matter of naming.

The SQL tutorial is a different thing in a different place
https://www.tarantool.io/en/doc/latest/tutorials/sql_tutorial/
which was added before the docs.google.com documents.
There were, of course, arguments that we didn't need the
introductory section at all -- and arguments that it should
be many times larger with everything that is found in
textbooks about databases and about SQL.
What we have now is a compromise.

**Comment by pgulutzan** [comment]
@msiomkin: Due to the change for issue#1612 SQL Reference: too long page without subsections, clicking SQL user guide no longer causes a redirect to SQL beginners' guide, so I think that takes care of the main part of this issue. As for the question "Do we really need it [i.e. SQL beginners' guide] in our docs?": I think so. Are you willing and able to persuade others that we should destroy it? If not, I hope we can close this issue.

**Comment by msiomkin** [comment]
Yes, it's ok when it's on a separate page. Let's close the issue.
