### ISSUE TITLE
[13pt] mopinion: describe more about memtx at Engines section

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/doc#1632]
Page 'Storage engines' tells about vinyl only. Either memtx should be added here or the title should be changed

https://www.tarantool.io/en/doc/latest/book/box/engines/

- [x] Restructure the [Storage engines](https://www.tarantool.io/en/doc/latest/book/box/engines/) page: make it the starting page with the brief intro on both engines -- memtx and vinyl; place the detailed description of each engine into a separate page.
- [x] Adapt the info about memtx to make an overview with highlighting the following:  #1705

**Comment by veod32** [comment]
To estimate the issue we need to decide first what we are going to do according to the analysis in https://github.com/tarantool/doc/issues/1635

1. Either we add more info about memtx and what kind of info
2. Or just restructure the content and put the vynil description on the separate page

These are two different pieces of work in terms of LOE (Level of Effort).

**Comment by veod32** [comment]
The section definitely should be restructured to separate vinyl and memtx description and the content about memtx should be added.  Discussed with @Mons in https://github.com/tarantool/doc/issues/1705
