### ISSUE TITLE
[8pt]research: Найти информацию про движок memtx

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/doc#1635]
[Тут](https://www.tarantool.io/en/doc/latest/book/box/engines/) подробна описана информация только про vinyl. Memtx упоминается только высокоуровнево и есть таблица сравнения 2х движков.

Нужно проверить: есть ли подобная информация/страница про memtx? И какая?
Ссылки можно комментом оставить

Связан с #1632

**Comment by veod32** [comment]
https://www.tarantool.io/en/doc/latest/book/box/engines/#differences-between-memtx-and-vinyl-storage-engines
https://www.tarantool.io/en/doc/latest/book/box/data_model/
https://www.tarantool.io/en/doc/latest/book/box/indexes/

**Comment by olegrok** [comment]
See also http://kostja.github.io/misc/2017/02/23/tarantool-data-structures.html
