### ISSUE TITLE
Verify installation instructions against Debian Buster

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#1638]
In the Russian Telegram chat a user reports a problem with enabling Tarantool repositories on Debian Buster. The reason is not clear, but it somewhere around gpg keys installation. `installer.sh` was used, but we anyway should verify both ways to install the repository.

@artembo said that he able to reproduce the problem.

**Comment by artembo** [comment]
It's weird, but i can not reproduce the problem again.  
The steps I do:

```
vagrant init debian/buster64
vagrant up
vagrant ssh

sudo su
apt update && apt install curl -y
curl -L https://tarantool.io/release/2.4/installer.sh | bash
```

The installation failed on November 2nd, but now everything works fine. I checked on the versions: 1.10, 2.4-2.6.

It didn't actually fail, but the Tarantool version was 1.9 whatever the version was specified in the installer link. So now it works fine anyway.

**Comment by Totktonada** [comment]
Okay, thanks!
