### ISSUE TITLE
C tutorial bug: extra mp_decode_array in harder.c

### ISSUE THREAD

**Issue by mary3000** [tarantool/doc#1645]
Tarantool version:  

2.5

OS version:

Ubuntu 20.04

Bug description:

Code in [harder.c](https://www.tarantool.io/en/doc/latest/tutorials/c_tutorial/#f-c-tutorial-harder) example in documentation contains extra decode logic: 
```c
  uint32_t arg_count = mp_decode_array(&args);
  printf("arg_count = %d\n", arg_count);
  uint32_t field_count = mp_decode_array(&args);
  printf("field_count = %d\n", field_count);
```
`arg_count` should be removed.

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by Totktonada** [comment]
Transferred from tarantool/tarantool to tarantool/doc.

**Comment by pgulutzan** [comment]
It looks like I somehow lost the braces after writing the example.
Thank you both. It will be {passable_table} in 2.3, 2.4, 2.5, 2.6.
