### ISSUE TITLE
[5pt] Cartridge failover: cartridge-cli option to start stateboard

### ISSUE THREAD

**Issue by srgkvlv** [tarantool/doc#1646]
Please describe how to launch cartridge with stateboard for stateful failover:

cartridge start --stateboard

https://www.tarantool.io/ru/doc/latest/book/cartridge/cartridge_dev/#failover-architecture

**Comment by veod32** [comment]
Possible place to write the content in the Cartridge documentation: https://www.tarantool.io/ru/doc/latest/book/cartridge/cartridge_dev/#stateboard-configuration

Also Cartridge CLI doc should be updated accordingly.

**Comment by patiencedaur** [comment]
Check this page: https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_cli/commands/start/
