### ISSUE TITLE
Bug Reports: 404: Page Not Found

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#1653]
https://www.tarantool.io/en/doc/2.5/book/admin/bug_reports/

The link is from our internal SOP document. It seems, it was working in the past. Let's setup appropriate redirect.

The actual location: https://www.tarantool.io/en/doc/latest/book/admin/bug_reports/

**Comment by Onvember** [comment]
There was a temporary problem with docs version 2.5. The location is OK now.

**Comment by Totktonada** [comment]
Confirmed, it works now. Thanks!
