### ISSUE TITLE
Unclear difference of Tarantool versions

### ISSUE THREAD

**Issue by ligurio** [tarantool/doc#1659]
There are several versions of Tarantool in support. See https://www.tarantool.io/ru/doc/latest/whats_new/.
It is unclear for Tarantool newbies and users with old versions what is the difference for these versions. It would be helpful to add feature matrix for supported Tarantool versions.

**Comment by Totktonada** [comment]
I forgot about this issue and filed #2226 with idea to collect notable features from our release notes and fill a per-version table with them.

**Comment by ligurio** [comment]
Duplicate of #2226
