### ISSUE TITLE
Settle on consistently calling a single tarantool instance "instance"

### ISSUE THREAD

**Issue by kostja** [tarantool/doc#166]
We have /etc/tarantool/instances.enabled. However, in the documentation we sometimes use "server" rather than "instance":

"Replication allows multiple Tarantool servers to work on copies of the same databases."

https://tarantool.org/search.html?q=server

@lenkis we need documentation writing guidelines where this is clarified

**Comment by lenkis** [comment]
Peter, I've updated the guidelines. Please update the manual.

**Comment by kostja** [comment]
I fixed tarantool/gh-2086, the patch is attached to the ticket.
