### ISSUE TITLE
Make sure that fiber.yield() is prohibited from within GC

### ISSUE THREAD

**Issue by kyukhin** [tarantool/doc#1667]
It looks like there is no mentions in the docs that it is prohibited to switch fibers() from withtin GC call.

Need to document that.

Ask @igormunkin for details

**Comment by igormunkin** [comment]
@kyukhin, we have published [howto document](https://www.tarantool.io/en/doc/latest/book/admin/troubleshoot/#problem-fiber-switch-is-forbidden-in-gc-metamethod) regarding the issue in scope of #1664. If yours request is not resolved, feel free to reopen this issue.
