### ISSUE TITLE
[2pt] Release Management: add explicit note what Tarantool version is considered a release

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#1674]
https://www.tarantool.io/en/doc/latest/dev_guide/release_management/

To mention explicitly that Tarantool release is only the following: X.Y.Z-**1**-HASH
Other versions X.Y.Z-**N**-HASH where N !=1 are NOT releases.

**Comment by Totktonada** [comment]
Since https://github.com/tarantool/tarantool/issues/3745 was finally resolved, there is no need to push extra dummy commit after a tag. So let's consider x.y.z.0 as a release. It is just easier to understand: it points to exactly same commit as one that is marked by the corresponding tag (x.y.z).

**Comment by veod32** [comment]
@kyukhin @Totktonada Please take a look if it's OK.

**Comment by Totktonada** [comment]
Commented, approved (only by me ATM).
