### ISSUE TITLE
Add box.session.user

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#168]
Add box.session.user() function to reference (https://tarantool.org/en/doc/book/box/box_session.html). This function returns the name of the current Tarantool user.

**Comment by bigbes** [comment]
Please, also, replace `old-function-name` with `old-function` in every `on_auth`/.. callback setters, since they obtain function pointers, not their names.

**Comment by lenkis** [comment]
Comments from @bigbes ignored. Peter, please amend the manual as requested.
