### ISSUE TITLE
Refer to awesome-tarantool

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/doc#1684]
Due to issue#1571 we have a section "Contributing"
http://www.tarantool.io/en/doc/latest/contributing/
and due to recent commits we have an updated "awesome-tarantool"
https://github.com/tarantool/awesome-tarantool

I propose to make the following changes:

For "How to contribute?" add something like:

If you have a tool that might go well in our curated
"awesome Tarantool" list https://github.com/tarantool/awesome-tarantool
you can read the guide for contributors there
https://github.com/tarantool/awesome-tarantool/blob/master/CONTRIBUTING.md
and submit a pull request.

For "Tarantool Ecosystem" change "Applied tools" to something like:
"Applied tools. See a selection including external tools in the
awesome-tarantool list https://github.com/tarantool/awesome-tarantool.

The tricky parts are:
is the awesome-tarantool contributing guide too strict?
will somebody really look at pull requests from the Tarantool side?

I ping people who participated in an earlier discussion re contributing:
@artur-barsegyan @kyukhin @Totktonada @tsafin

**Comment by Totktonada** [comment]
> The tricky parts are:
> is the awesome-tarantool contributing guide too strict?

I like the idea it advertises: build a solid ecosystem of tarantool modules and tools.

To be honest, I don't feel the ecosystem solid now. So I think we should apply some common sense when propose changes and review proposals.

> will somebody really look at pull requests from the Tarantool side?

I'm interested, at least. I hope @Mons too.

**Comment by pgulutzan** [comment]
Since there is at least slight interest, and since the 44 watchers
https://github.com/tarantool/awesome-tarantool/watchers
include about a dozen Tarantool people, I guess it is okay.
Also: the "How to contribute to tools" section
http://www.tarantool.io/en/doc/latest/contributing/contributing/#how-to-contribute-to-tools
only mentions contributions from "the Tarantool team".
I will replace the last sentence with:
"To propose a tool for the awesome-tarantools curated list,
see our guide for contributors." i.e.
https://github.com/tarantool/awesome-tarantool/blob/master/CONTRIBUTING.md
If there are no objections in the next few days, I will make
the suggested changes for version 2.6, and perhaps for earlier versions.

**Comment by Totktonada** [comment]
I don't mind.
