### ISSUE TITLE
Requirements for new modules

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#169]
We have some basic requirements for new modules here:
https://github.com/tarantool/rocks#contributing
These requirements are probably too basic. Need the team's feedback to refine them.

**Comment by racktear** [comment]
I assume that if a person managed to write a useful Tarantool module, they are familiar with Tarantool itself. They might not know how to:
- have their module built with Travis (we should at least link to the PackPack repo for explanation)
- how to version their module (PackPack versioning convention and version tagging)

**Comment by lenkis** [comment]
@kostja agree? ^^

**Comment by kostja** [comment]
Yes, I agree.

**Comment by lenkis** [comment]
@rtsisyk will this procedure change when luarocks gets integrated into tarantoolctl?

**Comment by rtsisyk** [comment]
> @rtsisyk will the procedure of adding new modules/rocks change when luarocks gets integrated into tarantoolctl?

No, .rockspecs are 100% compatible. Our package manager is just LuaRocks wrapped by tarantoolctl tool.
