### ISSUE TITLE
[8pt] mopinion: replica's heartbeat description are ambiguous

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/doc#1698]
На этой [странице](https://www.tarantool.io/en/doc/2.3/book/replication/repl_monitoring/) сказано: 

A replica sends heartbeat messages to the master every second, and the master is programmed to reconnect automatically if it does not see heartbeat messages within replication_timeout seconds. Therefore, in a healthy replication setup, idle should never exceed replication_timeout: if it does, either the replication is lagging seriously behind, because the master is running ahead of the replica, or the network link between the instances is down. В то же время https://www.tarantool.io/ru/doc/2.6/reference/configuration/#cfg-replication-replication-timeout Since version 1.8.2. If the master has no updates to send to the replicas, it sends heartbeat messages every replication_timeout seconds, and each replica sends an ACK packet back. Both master and replicas are programmed to drop the connection if they get no response in four replication_timeout periods. If the connection is dropped, a replica tries to reconnect to the master. Разные части доки противоречат друг другу, где же правда? -- Author: @rosik

**Comment by pgulutzan** [comment]
If nobody objects within a few days, I intend to change from:
"A replica sends heartbeat messages to the master every second,
and the master is programmed to reconnect automatically if it does
not see heartbeat messages within replication_timeout seconds."
to:
"A master sends heartbeat messages to a replica every second,
and the master is programmed to disconnect if it does
not see acknowledgments of the heartbeat messages within replication_timeout * 4 seconds."

I do not intend to change the other statement, although I know that the version number "1.8.2" is bad, as described by gh-1718.

Also there is a possible problem with the description of replication_connect_timeout
https://www.tarantool.io/en/doc/2.3/reference/configuration/#cfg-replication-replication-connect-timeout
"This parameter is different from replication_timeout, which is only used to automatically reconnect replication when it gets no heartbeats."
I intend to change to:
"This parameter is different from replication_timeout, which a master uses to disconnect a replica when the master receives no acknowledgments of heartbeat messages."
