### ISSUE TITLE
Usage examples of connectors 

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/doc#17]
Stage 1. Design primitive data-oriented application which should show "the great power" (c) of Tarantool 1.6 (Google for "Northwind Database" for inspiration)

Stage 2. Implement client examples using connector libraries for supported languages (PHP/Perl/Python/C/etc.). Update repositories, README and packages. The end user should be able to understand how to perform basic requests to Tarantool using his favorite language. (Please open a separate ticket for each language in the corresponding repository).

**Comment by lenkis** [comment]
@kostja let's elaborate on this.

**Comment by lenkis** [comment]
@rtsisyk please post details here

**Comment by rtsisyk** [comment]
I propose to add some basic examples  how to connect to Tarantool, request some data, update some data and so on for every programming language we support. This ticket requires coding, i.e. you need somebody who will make some examples in C, PHP, Python, Perl and other languages. I think that @bigbes is the best candidate here, at least for C, PHP and Python. Other connector authors will follow.

**Comment by rybakit** [comment]
For the record, the alternative PHP connector has README [examples](https://github.com/tarantool-php/client#data-manipulation) for the most operations, as well as an ["examples"](https://github.com/tarantool-php/client/tree/master/examples) directory where one can directly run those examples without bothering themselves with copy-pasting code from README. Moreover, those examples are part of the test suite and get executed automatically by CI to ensure that they are always correct.

**Comment by artur-barsegyan** [comment]
We already have some first variant of this manual. This variant passed four pieces of UX researches and all that we need at now is just fix some issues and merge 2 sections in one: "Creating the first Tarantool instance" and "Connect to Tarantool from <language>".

**Comment by artur-barsegyan** [comment]
Here it is the final state: https://www.tarantool.io/en/doc/1.10/getting_started/getting_started_connectors/
