### ISSUE TITLE
Document https://github.com/mailru/quotas

### ISSUE THREAD

**Issue by kostja** [tarantool/doc#170]
Document the distributed quota management module at https://github.com/mailru/quotas

**Comment by lenkis** [comment]
Requested basic info from @GeorgyKirichenko.

**Comment by lenkis** [comment]
*General info from @GeorgyKirichenko*

A distributed RPS quota manager for Tarantool 1.6+

Depends on other modules:
- `connpool` (http://github.com/tarantool/connpool)

With this module, you can set usage limit for some resource used by a distributed cluster of several Tarantool nodes (e.g. 5 Tarantool nodes cannot exceed the total limit of 30 RPS for a specific resource). To propagate current resource usage information among the nodes, this module uses a GOSSIP-like protocol.

The quota manager splits a second into slices (by default, 10). For each slice, it stores the actual RPS per resource made within the slice. Time tracking is implemented using the "sliding window" method, where statistics for the old slice are abandoned over time and the quota manager starts tracking resource usage for a new slice.

Every Tarantool node in a cluster stores the complete resource usage statistics for that node. This enables local decisions about the possibility to use a resource. If the decision is positive, the quota manager records it in a state table and applies the changes to a specified number (`p_neighbour_count` parameter in `init_lease()` function) of random nodes in the cluster.

When the cluster's quota manager gets a state update from some node, it checks whether this change was tracked (a short check algorithm is to match the node's local resource usage statistics for the specified time slice versus the statistics from the update -- we assume that resource usage can only grow) and updates the node's local state table. After that, the update is propagated to other nodes.

To speed up quota management, a resource can be leased in a batch. As more resource requests arrive, the quota manager leases the resource until the batch is up (in terms of time or RPS) without changing the cluster state. If the batch is timed out, but its RPS quota is not fully used, the cluster quota manager issues another request -- to release the resource -- and so makes it possible to use it in new slices and/or lease it for other nodes.

A quota manager is initialized with `init_lease()` function. It takes the following parameters:
- pool of connections
- number of neighboring nodes for propagating the updates at each GOSSIP loop
- maximal batch size that can be requested (in RPS)

After the quota manager is initialized, you can use `get_lease()` function to request a resource. It takes the following parameters:
- user, domain and op -- to identify the resource (that's how identification is done in BASTIDA, a Tarantool-based frontend for telecom services, for which this module was originally developed)
- quota (in RPS)
