### ISSUE TITLE
[16pt] Update the template for module/class/method reference

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/doc#1703]
Пройтись по всем функциям и убедиться, что в каждой функции присутствуют нужные секции и они все описаны в одном предсказуемом формате.

Необходимо, чтобы в каждой функции были:

- параметры функции
- наличие возвр. значение, его тип и описание
- пример использования (необходимо написать для функций из раздела box.space, box.index, box.schema)
- complexity factors
- поведение при ошибке (исключение, типы ошибок)

### TODO:
- [ ] Предложить шаблон описания функции
    * свериться с разработчиками, что им всё понятно и достаточно 
- [ ] Обновить [шаблон](https://www.tarantool.io/en/doc/latest/dev_guide/documentation_guidelines/#module-and-function) в Contributor's guide/Documentation:
    * какую разметку rST использовать
    * как правильно и понятно описать всё

**Comment by veod32** [comment]
Я бы разбил на подзадачи:

1. [8pt] Сделать шаблон и согласовать его (кор тим + продакты) 
2. [TBD] Пройтись по всем функциям и сделать апдейт в соответствие с шаблоном. Тут имхо надо оценить, ск-ко времени уйдет на 1 функцию, и соответственно посчитать оценку (даже в упомянутых 3х модулях кол-во функций 90+).
3. [TBD] Надо подумать про автоматизацию процесса в плане поиска новых функций и depricated функций. Сейчас все в ручном режиме - полнота скоупа функций в документации зависит от того, завели разработчики док тикет на новую или depricated функцию или нет. Как идея - какой-то скрипт, который можно прогнать по репе и который будет выдавать отчет по сравнению имеющегося в документации и что есть реально в коде. Может и более продвинутую автоматизацию можно сделать - когда при добавлении новой функции или удаления старой будет автоматически апдейтиться документация в соотвествии с шаблоном. Нужно участие программиста.

**Comment by artur-barsegyan** [comment]
Это довольно ясная задача и объем описан в тикете. Ее суть в том, чтобы причесать текущие разделы в рамках работ в тикете #1685.

Модуль "box" изменяется крайне редко, но в дальнейшем необходимо настроить автоматизацию проверки шаблонов и вообще генерацию Reference раздела из кода.

**Comment by Totktonada** [comment]
+как выбрасываются / возвращаются ошибки и какие именно (как в описании модуля popen). Емнип, присутствует некоторая разножопица.
