### ISSUE TITLE
Broken links, again... now for the space index reference

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#1711]
The following URL gives 404 now.

https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_space_index/#box-space-before-replace

It really worth to going toward #1678.

**Comment by Totktonada** [comment]
NB: The given link works now, but https://www.tarantool.io/en/doc/2.5/reference/reference_lua/box_space_index/#box-space-before-replace does not (the same for 1.10 and 2.6).

**Comment by artembo** [comment]
Fixed for all versions
