### ISSUE TITLE
Remove rst, po and pot files coming from submodules

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#1740]
We have a few  files committed in this repo, which are also committed in some of the submodules. They should be removed from the repo, and the corresponding directories added in .gitignore.

Blocks #1685 and #1742

DoD:

* [ ] Files are removed from the repo. Make sure that the original files are present in the submodules.
* [ ] `.gitignore` updated.
* [ ] Running `update_submodules.sh` does not result in any changes in the repo, shown by `git status`
* [ ] Changes are done in branches `2.6` and `1.10`.

**Comment by Totktonada** [comment]
Where you want to store the Russian translation?

**Comment by NickVolynkin** [comment]
@Totktonada in the same repo where the sources are. For generated sources — with the code they're generated from.
