### ISSUE TITLE
[2pt] Make documentation issue templates in this repository

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#1741]
https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository

* New issues should go in the Documentation project, Inbox.
* Types:
    * Update documentation content
    * Fix an error in content
    * New feature or improvement in the code part (frontend/backend/deployment/analytics)
    * Fix a bug in the code part.

**Comment by rosik** [comment]
https://github.community/t/feature-request-allow-to-add-projects-to-the-issue-template/1789

Seems that setting a project isn't supported yet. I didn't find a way in the documentation you've linked either.

**Comment by NickVolynkin** [comment]
Partially resolved by using automation on the project board.
