### ISSUE TITLE
Change a warning re calling certain Lua functions from SQL

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/doc#1754]
# Change a warning re calling certain Lua functions from SQL

**Product:** Tarantool
**Since:** 2.7.1, 2.6.2, 2.53
**Audience/target:** 
**Root document:** https://www.tarantool.io/en/doc/latest/reference/reference_sql/sql_plus_lua/
**SME:** @Korablev77 
**Peer reviewer:** @

# Details

"[SQL PLUS LUA](https://www.tarantool.io/en/doc/latest/reference/reference_sql/sql_plus_lua/)" says
"Warning: the SQL statement must not invoke a Lua function, or execute
a Lua chunk, that accesses a space that underlies any SQL table that
the SQL statement accesses. ..."
That happens to be what is done in one of the examples that was added in
https://github.com/tarantool/tarantool/issues/5427
Calling a Lua function from SQL changes the number of rows in the result!
and I fail to get crashes with simple tests, for example

```lua
box.execute([[CREATE TABLE m (s1 INTEGER PRIMARY KEY);]])
box.schema.func.create('_F',
   {language = 'LUA',
    returns = 'unsigned',
    body = [[function () box.space.M:truncate(); return box.space.M:count() end]],
    is_sandboxed = false,
    param_list = {},
    exports = {'LUA', 'SQL'},
    is_deterministic = true})
box.execute([[SELECT _f() FROM m;]])
```
So we can remove the warning entirely, or we can
change "must not" to "should not".
Unless there are objections, I will change "must not" to "should not".
I still think that conceivably it could cause trouble.

**Comment by NickVolynkin** [comment]
Hi @pgulutzan, it's good that you've noticed it. Probably we should ask devs if the warning is still right and when it is right.

**Comment by Korablev77** [comment]
Agree with proposed change ("must not" to "should not") since still this is poorly tested scenario and there can be other bugs.

**Comment by pgulutzan** [comment]
@Korablev77: Here is a new test:
box.execute([[CREATE TABLE m (s1 INTEGER PRIMARY KEY);]])
box.execute([[CREATE TABLE m2(s1 INTEGER PRIMARY KEY, s2 INT REFERENCES m);]])
box.execute([[INSERT INTO m VALUES (1);]])
box.schema.func.create('_F',
   {language = 'LUA',
    returns = 'unsigned',
    body = [[function () box.space.M:truncate(); return box.space.M:count() end]],
    is_sandboxed = false,
    param_list = {},
    exports = {'LUA', 'SQL'},
    is_deterministic = true})
box.execute([[INSERT INTO m2 VALUES (_f(), 1);]])
... It is a failure because now there are zero rows in m but there is one row in m2.
Nevertheless it will not be an official bug because we will say you should not do this.
Agreed?

**Comment by pgulutzan** [comment]
@NickVolynkin: In a Telegram chat, I and @veod32 concluded that this issue is not worth the trouble. Therefore the pull request can be ignored, and I will close this. Ping if you want a transcript of the chat.
