### ISSUE TITLE
[1pt] Python 2 is gone, need to update page "Building from source"

### ISSUE THREAD

**Issue by ligurio** [tarantool/doc#1757]
We are moving away from Python 2 to Python 3 (see https://github.com/tarantool/tarantool/issues/5652),
let's update text and package names in https://www.tarantool.io/en/doc/latest/dev_guide/building_from_source/

**Comment by NickVolynkin** [comment]
@ligurio since which Tarantool versions is this change effective? Are they 2.5.3, 2.6.2, and 2.7.1?

**Comment by ligurio** [comment]
@NickVolynkin to be honest we are still in progress with migration (relevant tasks are [1] and [2]).
I believe change will affect all supported Tarantool versions.

1. https://github.com/tarantool/tarantool/issues/5652
2. https://github.com/tarantool/test-run/pull/263

**Comment by ligurio** [comment]
We are close to moving Tarantool testing to Python 3:

- [ ] tarantool/tarantool#5652 - to be merged next week
- [x] tarantool/test-run#263

**Comment by Totktonada** [comment]
The transition to Python 3 is done.
