### ISSUE TITLE
Research: markup and translation workflow for the "Try Tarantool"

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/doc#1762]
We prepare to launch the "Try Tarantool". 

_FYI It's the service that will pass new users through the first Tarantool experience: a user create a first cluster, upload data schema, upload some code and get some data via HTTP._ 

### What should be done
Translate the tutorial because 25 percent of our daily site audience is English speaking.

At now, we have only the Russian version of the tutorial. 

[Original tutorial](https://www.notion.so/Tutorial-bb7db1c1ba4943bb82b310e0710a00ca)

**Comment by NickVolynkin** [comment]
Обсудить формат строк, чтобы их можно было отправить в CAT.

**Comment by artur-barsegyan** [comment]
Договорились с @NickVolynkin, что он скажет в каком формате хранить исходники нового туториала и как он будет переводиться.

До конца недели жду ответа.

[Ссылка на историю обсуждения.](https://www.notion.so/e70da95c62484eb8a82f48aa7518c227)

**Comment by NickVolynkin** [comment]
@artur-barsegyan эти тексты сейчас уже лежат в каком-нибудь репозитории?

**Comment by artur-barsegyan** [comment]
> @artur-barsegyan эти тексты сейчас уже лежат в каком-нибудь репозитории?

Пока нет. Это необходимо?

**Comment by NickVolynkin** [comment]
Уточнил. Лучше использовать Markdown, мы сможем включать куски текста на Markdown в доки на rST.
