### ISSUE TITLE
Build a localization prototype with Smartcat.com

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#1765]
DoD
- [ ] Make a primary Smartcat account, grant access to the team accounts
- [ ] Create a project for tarantool/doc repository, setup language and other settings
- [ ] Add configuration files
- [ ] Upload current translation sources (English strings) **and** translations, **once**.
- [ ] Write a script for updating translation sources (push)
- [ ] Write a script for updating translations (pull)

Out of scope:

* Building CI/CD pipelines
* Fixing errors in translation

**Comment by patiencedaur** [comment]
Currently translations are not the priority. Closing.
