### ISSUE TITLE
[1pt] Need to remove CentOS 6 from feather packages available list

### ISSUE THREAD

**Issue by avtikhon** [tarantool/doc#1768]
As CentOS 6 was removed from packages builds with commits to Tarantool:
https://github.com/tarantool/tarantool/commit/cb9174e7b8ce904a2897f1156d5ff234c833cbdd
https://github.com/tarantool/tarantool/commit/8b08a3ba7dc659901c829e05526328f18640301d

then need to document that CentOS 6 package are not available since 2.8.0-31-g8b08a3ba7 Tarantool version

**Comment by NickVolynkin** [comment]
Hi @avtikhon! I couldn't find any place in the docs where we have a list of supported OS versions. Do you know of any such list?

**Comment by Totktonada** [comment]
![image](https://user-images.githubusercontent.com/92749/109285284-f12e3500-7831-11eb-9f3a-9de5f98b5e99.png)

https://www.tarantool.io/en/download/os-installation/rhel-centos/

**Comment by Onvember** [comment]
removed blocks "For RHEL/CentOS 6:" from https://www.tarantool.io/en/download/os-installation/rhel-centos/
