### ISSUE TITLE
Update version-specific info in 1.8

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#177]
- [x] add SQL features to "Overview"
- [x] add SQL tutorial to "Tutorials"
- [x] update 1.7 in instructions at "Download" page
- [x] update 1.7 in links
- [ ] update 1.7 (Tarantool version) in code snippets -- NOT NECESSARY RIGHT AWAY

**Comment by bigbes** [comment]
It's more like 'Update all 1.7 information to 1.8'

**Comment by lenkis** [comment]
not exactly, I'm leaving functionality issues outside the task scope

**Comment by lenkis** [comment]
- [x] SQL features in "Overview"
- [x] SQL tutorial in "Tutorials"
- [ ] 1.7 links
- [ ] Tarantool version in code snippets
