### ISSUE TITLE
mopinion: searching for 'stateful failover'

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#1784]
При попытке найти секцию, посвящённую 'stateful failover', я вбил в поисковую строку слово 'stateful'. Первая ссылка -- https://www.tarantool.io/ru/doc/latest/book/monitoring/metrics_reference/ . На странице нет ни одного слова 'stateful'.

**Comment by patiencedaur** [comment]
Fixed in https://github.com/tarantool/tarantool.io/issues/882
