### ISSUE TITLE
Remove  space_object:inc/dec docs

### ISSUE THREAD

**Issue by Gerold103** [tarantool/doc#18]
Functions inc() and dec() were removed from tarantool by https://github.com/tarantool/tarantool/issues/1289.
Need to delete them from docs:
 - https://tarantool.org/doc/book/box/box_space.html#lua-function.space_object.inc
 - https://tarantool.org/doc/book/box/box_space.html#lua-function.space_object.dec

**Comment by rtsisyk** [comment]
Duplicate of #16
