### ISSUE TITLE
[8pt] Update formatting in "Binary protocol"

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#1801]
A follow-up of #1661. Use `code-block` to format code examples. Improve other things that can be improved.

Reference on markup syntax: https://www.tarantool.io/ru/doc/latest/contributing/docs/markup/#code-snippets

For example, change:

> IPROTO_SELECT=0x01, IPROTO_INSERT=0x02, IPROTO_REPLACE=0x03,...

to 

```ini
IPROTO_SELECT=0x01
IPROTO_INSERT=0x02
IPROTO_REPLACE=0x03
...
```

For the latter, use `..  code-block:: ini`.

**Comment by pgulutzan** [comment]
If you use a browser to look at the .html that is produced from the latest commit, and search for grave accent (backtick) `, it will show you a few errors.
