### ISSUE TITLE
[3pt] Clarify documentation regarding upgrade from 1.6 to 2.x

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/doc#1807]
Our doc states that there are no problems in upgrading 1.6 to 2.x. See [here](https://www.tarantool.io/en/doc/latest/book/admin/upgrades/#how-to-upgrade-from-tarantool-1-6-to-2-x)

However, the [paragraph above](https://www.tarantool.io/en/doc/latest/book/admin/upgrades/#upgrading-a-tarantool-instance) states that there are problems with upgrading from 1.6 to 2.x directly, and this is true.

Actually, there is no easy way to upgrade tarantool 1.6 to 2.x directly.
The recommended option is to perform a 2 step upgrade: first perform 1.6 -> 1.10 upgrade, and then 1.10 -> 2.x
Then there shouldn't be any problems.

Another option, when a direct upgrade is really needed, is to use an upgrade script. The script should be run on a 2.x instance before trying to boot the 1.6 data files (.xlog and .snap). The latest script version is in [this gist](https://gist.github.com/sergepetrenko/1e27197ca2d5995adda1a959f4627295). It'll be updated and fixed later, so do not rely on it right now.

**Comment by NickVolynkin** [comment]
What's “re upgrade”? Regarding upgrade?

**Comment by sergepetrenko** [comment]
> What's “re upgrade”? Regarding upgrade?

Yep.

**Comment by artur-barsegyan** [comment]
Вот тут [продолжение истории](https://github.com/tarantool/tarantool/issues/5894). Оно нам и нужно. Ждем пока сделают это в коре.

**Comment by patiencedaur** [comment]
Related issue: https://github.com/tarantool/roadmap-internal/issues/48

**Comment by patiencedaur** [comment]
![Screenshot from 2022-07-21 16-18-38](https://user-images.githubusercontent.com/40490252/180223658-449b8f57-78d2-4e01-84ef-10b3bb30422e.png)

**Comment by patiencedaur** [comment]
https://github.com/tarantool/doc/issues/3042#issuecomment-1191482880

## Upgrade scenario step-by-step:

Before upgrade:

1. check cluster health, it should be ok before upgrade
2. execute `box.info()` and check that replicas in operation mode
3. check replication lag, it shouldn't be too high
4. check tarantool logs for errors on each replica 

Upgrade

1. enable RPM/DEB repository for tarantool 1.10 and install tarantool package using package manager
2. replace `box.replication_source` to `box.replication` everywhere in used Lua applications
3. restart one of old instance v1.6 to run updated binary
4. make sure that restarted instance is still in a cluster and it is still in operation
5. repeat steps 3-4 for each replica in a cluster
6. restart master instance and execute `box.schema.upgrade()` on it
7. make sure cluster is healthy, there are no errors in logs and output of `box.info()` doesn't report any issues

After upgrade

1. stop one-by-one instances with old tarantool versions and each time and check that cluster continue works
2. success criteria: all instances has new tarantool version v1.10, replication lag ~= 0, no errors in logs

### References:

- https://www.tarantool.io/en/doc/1.6/book/replication/
- https://www.tarantool.io/en/doc/1.10/book/admin/upgrades/
- https://www.tarantool.io/en/doc/1.10/whats_new/#version-1-10
