### ISSUE TITLE
Bug with rendering titles

### ISSUE THREAD

**Issue by Onvember** [tarantool/doc#1808]
If a title of level 2+ contains any text rst markup: *italic*, ``literal`` or **bold**, it is rendered incorrectly:

For example, in [Data Model](https://www.tarantool.io/en/doc/latest/book/box/data_model/#options-for-box-schema-sequence-create):
![image](https://user-images.githubusercontent.com/37013254/107028422-99feec80-67be-11eb-90e4-8d5ca25fb4c0.png)

Or in [Examples for box.index](https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_index/examples/#example-showing-submodule-box-index-with-index-type-rtree-for-spatial-searches):
![image](https://user-images.githubusercontent.com/37013254/107029160-a59ee300-67bf-11eb-9266-cd5732918974.png)

**Comment by artembo** [comment]
Looks good for now
