### ISSUE TITLE
Doc page improvements

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#181]
The docs start page should look more like this:
https://docs.python.org/3.6/

We should show the TOC on the left right away, increase the font of the items and either remove the boxes or make them look nice.

**Comment by kostja** [comment]
In other words, the docs start page should look more like this:
https://docs.python.org/3.6/

We should show the TOC on the left right away, increase the font of the items and either remove the boxes or make them look nice.

**Comment by lenkis** [comment]
Done by LT
