### ISSUE TITLE
[5pt] Glossary: framework and guidelines

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#1823]
Prepare for building a Tarantool glossary:

- [x] What is concept, term, restricted term
- [ ] Place for glossary in the docs
- [ ] Add 1 term, pick any. Better find a term which has its concept already well defined.
- [ ] Add `:term:` links to this term in other documents
- [ ] Workflow for updating glossary: labels, issue template

**Comment by artur-barsegyan** [comment]
From the experience of interviewing users, newcomers often don't understand our terminology.

As part of this task, I would suggest making a mechanism that would give an understandable definition when hovering over a term. The term should be highlighted with a dotted line at the bottom and explained in a tooltip.

**Comment by NickVolynkin** [comment]
@artur-barsegyan there's standard markup for this:
```rst
:term:`index`
```
We will use it.

**Comment by artur-barsegyan** [comment]
Good. I would rename this issue into something close to my message above.
