### ISSUE TITLE
Document `tarantoolctl cat --replica` option

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/doc#183]
`tarantoolctl cat` and `tarantoolctl play` now supports new option `--replica` to filter requests by replica_id (former server_id).

https://github.com/tarantool/tarantool/issues/2301

**Comment by lenkis** [comment]
To get replica_id, say ``box.space._cluster:select{}``. This will return a table with all {server.id, server.uuid} tuples for every instance that has ever joined the replica set. you need server.id

Example:

tarantool> box.space._cluster:select{}
---
- - [1, '88580b5c-4474-43ab-bd2b-2409a9af80d2']
...

Here replica_id = 1.

**Comment by lenkis** [comment]
@kostja: now we have info about cat & play in tarantoolctl's man & --help. is that enough?

**Comment by kostja** [comment]
Let's have a chapter for tarantoocltl to the reference or the user guide.
