### ISSUE TITLE
[8pt] Guidelines: what is code and how to format it

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#1835]
What to format with `inline code`:

* data types,
* error messages,
* URL (maybe, for `localhost`, intranet and other examples because of `linkcheck`),
* port number,
* package names,
* CLI app names?

When is it better to use code-blocks?

Reviewers: @Onvember, @NickVolynkin.

---

This issue is a follow-up of reviewing #1831

See also other roles for machine-processed text: https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html?highlight=samp#other-semantic-markup

**Comment by Onvember** [comment]
should we format 'memtx' and 'vinyl' with inline code?

**Comment by Onvember** [comment]
> URL

Why URL?

**Comment by pgulutzan** [comment]
The SQL manual examples were originally code-block:: none
or :code:`..` on multiple lines but were changed to code-block:: sql.
Here are examples that show what this causes,  in
https://www.tarantool.io/en/doc/latest/tutorials/sql_tutorial/
https://www.tarantool.io/en/doc/2.3/reference/reference_sql/sql/
INSERT is coloured as a keyword but data type names are not,
integer literals are purple but string literals are brown,
the literal -1000 has a red hyphen and purple digits,
the constraint name c is blue while other names are white,
the SUM function is blue while the SUBSTR function is white,
for the literal 1e30 the 1 is purple and the e30 is white,
regular column names are white but delimited ones are brown,
size is blue as if it's a reserved word,
bracketed comments and simple comments have different colours,
for X'41' the X is white and the 41 is brown,
INDEXED is not coloured as a keyword,
in START TRANSACTION the word START is blue the word TRANSACTION is white,
SAVEPOINT is not coloured as a keyword,
RELEASE is not coloured as a keyword,

**Comment by pgulutzan** [comment]
@NickVolynkin: But if you really want to have colours,
the manual can be done without troubles like the ones in the examples above,
by inserting this in the .rst file:

.. raw:: html

    <p style='font-family:monospace; white-space:pre;'>
    text including <span style="color:color-name.">...</span> around each set of tokens
    </p>
    
Example:
    
.. raw:: html

    <p style='font-family:monospace; white-space:pre;'>
    <span style="color:blue">CREATE TABLE</span> <span style="color:red">f2</span> <span style="color:brown">(</span>
        <span style="color:red">ordinal</span> <span style="color:blue">INTEGER PRIMARY KEY</span><span style="color:brown">,</span>
        <span style="color:red">referring_planet</span> <span style="color:blue">STRING DEFAULT</span> <span style="color:green">'Earth'</span><span style="color:brown">,</span>
        <span style="color:blue">FOREIGN KEY</span> <span style="color:brown">(</span><span style="color:red">referring_planet</span><span style="color:brown">)</span> <span style="color:blue">REFERENCES</span> <span style="color:red">f1</span> <span style="color:brown">(</span><span style="color:red">referenced_planet</span><span style="color:brown">)</span>
            <span style="color:blue">ON UPDATE SET DEFAULT</span>
            <span style="color:blue">ON DELETE CASCADE</span><span style="color:brown">);</span>
    </p>

which looks like this when I use Firefox to look at singlehtml.html on my machine:

![create_table_f2](https://user-images.githubusercontent.com/5668310/108779020-832cf980-7523-11eb-8bb3-226828af7df3.png)


Indenting is correct, colouring is consistent.
I have a utility program that has a recognizer that recognizes all the SQL examples without error.
I could change it so it would generate html like the above quickly for all SQL examples.
Possibly it would cause trouble for output other than .html files, I do not know.
