### ISSUE TITLE
Support environment config options in documentation

### ISSUE THREAD

**Issue by Mons** [tarantool/doc#1838]
In https://github.com/tarantool/tarantool/issues/5602 we adding support for environment variables

It should be reflected in configuration reference

**Comment by NickVolynkin** [comment]
Source of inspiration: https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

**Comment by Onvember** [comment]
Duplicate of #2066
