### ISSUE TITLE
[4pt] Replace gitlab-ci with github actions for tarantool/doc

### ISSUE THREAD

**Issue by artembo** [tarantool/doc#1864]
Since we no longer use Gitlab CI, we need to configure Github Actions to automate the delivery of documentation to tarantool.io.

- [ ] remove gitlab-ci.yml
- [ ] update Dockerfile to use new base image to build documentation
- [ ] add Github Action pipeline which will build json, pdf and singlehtml documentation and upload it to s3. Consider using [container specifier](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer)
- [ ] remove .travis-ci and related scripts

**Comment by artur-barsegyan** [comment]
Пожалуйста, опиши мотивацию для этой задачи

**Comment by NickVolynkin** [comment]
@artur-barsegyan мы отказываемся от гитлаба, а CI нам нужен.
