### ISSUE TITLE
[3pt] Translate Connecting to Tarantool from C++

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#1868]
**Page:** https://www.tarantool.io/en/doc/latest/getting_started/getting_started_cxx/
**Crowdin:** TBD 
**Words:** 
**Reviewer:** @veod32

**Comment by ladyune** [comment]
Please provide the link to the file in Crowdin, I can't seem to find it

**Comment by patiencedaur** [comment]
Russian translations are now frozen. Closed.
