### ISSUE TITLE
Marketing materials pages

### ISSUE THREAD

**Issue by zloidemon** [tarantool/doc#187]
Need page with marketing materials and page with logos like [this](https://www.freebsdfoundation.org/about/project/) and [marketing page](https://www.freebsd.org/marketing/).

**Comment by lenkis** [comment]
@kostja we have marketing/whitepaper stuff in the new (upcoming) site design, let's include logo stuff as well

in the current .org design, we could add a link to logo downloads (e.g. a folder with logo images in several formats) from doc main page, under telegram chat on the left. ok?

**Comment by kostja** [comment]
Will be addressed by http://tarantool.io
