### ISSUE TITLE
[2pt] Add location context information in the localization files

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#1883]
# Add location context information in the localization files

Set `gettext_location = True` to make Crowdin show `path/file.pot:string_number`

**Reviewer:** @artembo 

# DoD

- [ ] Set `gettext_location = True`, update files, push to Crowdin, pull back.
- [ ] Check that there are no other changes coming with this update.

# Planning checklist

- [x] Pick label:
  - [CI/CD](https://github.com/tarantool/doc/labels/CI/CD)
  - [localization](https://github.com/tarantool/doc/labels/localization)
  - or others.  
- [x] Estimate complexity in storypoints in the title
- [x] Add to **Documentation** board → **Backlog**

> Note: issue templates are in beta. Give your feedback in #1869.

**Comment by patiencedaur** [comment]
I think this is fixed:
- Crowdin recognizes context, showing source file names
- The pull-translations job has a "false" checkbox that ensures only the right translations arrive for the PR
