### ISSUE TITLE
[8pt] Update the DEB/RPM deployment instruction

### ISSUE THREAD

**Issue by ksenobait09** [tarantool/doc#1904]
# Update the DEB/RPM deployment instruction

**Product:** Cartridge
**Audience/target:** devs going to run their project in production
**Root document:** https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_dev/#deploying-an-application
**SME:** @artur-barsegyan @rosik 
**Peer reviewer:**
**Translator:** @ainoneko 
**Proofreader:** @patiencedaur 

# Details

На боевых серверах предлагается запускать серверы через systemd, а не через cartridge. Из доки не совсем понятны такие моменты как логирование(особенность systemd, что логирование идет через journalctl, но думаю в доке стоит упомянуть). Также нигде в доке не указано, что workdir в конфиге не учитывается и выставляется самостоятельно

# Definition of done

- [x] Как перевезти проект из локального запуска впрод?
- [x] Для кого нужны RPM пакеты, для кого DEB? Не очевидно из документации
- [x] С каким названием сохранять конфиг для systemctl? 
- [x] Как смотреть логи инстансов?
- [x] Проверена правильность шагов деплоймента и описаны все пререквизиты.

**Comment by veod32** [comment]
Build on the testing env:
https://tarantool-develop.herokuapp.com/en/doc/1904-cartridge-app-deploy/book/cartridge/cartridge_dev/#deploying-an-application
