### ISSUE TITLE
[5pt] Merge version 2.5.3, 2.6.2, 2.7.1 into latest

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#1916]
# Merge versions 2.5.3, 2.6.2, 2.7.1 into latest

**Reviewer:** @NickVolynkin

See also:

- https://github.com/tarantool/tarantool/releases/tag/2.5.3
- https://github.com/tarantool/tarantool/releases/tag/2.6.2
- https://github.com/tarantool/tarantool/releases/tag/2.7.1

# Definition of done

- [x] For each element in version's changelog add a "Read more" link to the docs.
- [x] In the target docs make a "Since version 2.5.3" statement with link back to release notes.
- [x] When there are alternatives for the same action, move forward the one which is implemented in a later version. -- [@veod32] No such cases for these RN items.

**Comment by veod32** [comment]
Currently, only one feature from the scope of these releases is documented (#1650). For other RN items that affect documentation, the following doc issues have been created:

- https://github.com/tarantool/doc/issues/1737
- https://github.com/tarantool/doc/issues/1626
- https://github.com/tarantool/doc/issues/1681
- https://github.com/tarantool/doc/issues/1723
- https://github.com/tarantool/doc/issues/1724
- https://github.com/tarantool/doc/issues/1749
- https://github.com/tarantool/doc/issues/1753
- https://github.com/tarantool/doc/issues/1970
- https://github.com/tarantool/doc/issues/1650
- https://github.com/tarantool/doc/issues/1730
- https://github.com/tarantool/doc/issues/1738
- https://github.com/tarantool/doc/issues/1731
- https://github.com/tarantool/doc/issues/1671
- https://github.com/tarantool/doc/issues/1964

**Comment by NickVolynkin** [comment]
Fixed by #1961
