### ISSUE TITLE
Documentation infrastructure instructions require changes to work

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/doc#1931]
I cloned tarantool-doc-latest today on Ubuntu 20.04, cmake 3.16.3.
I read "Documentation infrastructure"
https://www.tarantool.io/en/doc/latest/contributing/docs/infra/
Those instructions didn't work for me immediately.

Initially I tried cmake . and make, which failed.

The instructions in "1. Add a submodule" apparently are redundant.
I just get error messages that they're already done, for example
"
pgulutzan@pgulutzan-VirtualBox:~/tarantool-doc-latest2/modules$ git submodule add https://github.com/tarantool/metrics.git
'modules/metrics' already exists in the index
"
Indeed .gitmodules already contains cartridge, cartridge-cli,
metrics, luatest, tarantool-operator, grafana-dashboard, tntcxx.
It is not stated whether these are the ones I need, but I have them.

The instructions in "2. Update build_submodules.sh" do not say:
am I supposed to run this? It fails.
It tries to use ldoc which doesn't exist, so I had to say
sudo apt install lua-ldoc.
It tries to use module-directory files which don't exist, so I had to say
git submodule update --init

The instructions in "metrics" and "cartridge_cli" are (I think)
redundant if I run build_submodules.sh, since the files exist.

The instructions in "3. Update .gitignore" are
"Finaly, we should add paths to the copied directories and files to the .gitignore file."
The word "Finaly" should be "Finally".
I'm not sure what "the copied dictories and files" are, so I did nothing.
Anyway .gitignore shouldn't affect my ability to build.

And after all this the build still fails. When I say make I see
"./build_submodules.sh: line 52: cd: /home/pgulutzan/tarantool-doc-latest2/modules/cartridge/build.luarocks/build.rst: No such file or directory"
So I said
cp -r ~/tarantool-doc-latest/modules/cartridge/rst ~/tarantool-doc-latest/modules/cartridge/build.luarocks
cd ~/tarantool-doc-latest/modules/cartridge/build.luarocks
mv rst build.rst
And now cmake . and make do not fail, I can build.
But I don't know whether those are the right steps.

**Comment by veod32** [comment]
>https://www.tarantool.io/en/doc/latest/contributing/docs/infra/
>Those instructions didn't work for me immediately.

@pgulutzan 
Hi Peter,
Can you please give a bit more details on what task you were trying to solve using those instructions?

**Comment by pgulutzan** [comment]
build

**Comment by veod32** [comment]
> build

To build the documentation, please follow the instructions given in the README of our ``tarantool/doc`` repository: https://github.com/tarantool/doc#how-to-build-tarantool-documentation-using-docker

The guidelines you mentioned, namely, https://www.tarantool.io/en/doc/latest/contributing/docs/infra/#adding-submodules are for the specific case when you are writing documentation content in another repository, not in the ``tarantool/doc``, and you need to add that repository as a submodule to the ``tarantool/doc``.

**Comment by pgulutzan** [comment]
I apologize for misunderstanding, and will close this.
