### ISSUE TITLE
[0pt] Push translation sources to Crowdin

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#1935]
# What needs to be done

Follow-up of #1866.
Every time when translation sources (.pot files) change, push changes to Crowdin.

**Reviewer:** @NickVolynkin 

# Definition of done

- [x] Save Crowdin token in secrets for this repository
- [ ] On changes to .pot files in `latest` branch, push changes to Crowdin

**Comment by comradekingu** [comment]
Why not just use Weblate instead? https://docs.weblate.org/no/latest/admin/continuous.html?highlight=webhooks#automatically-receiving-changes-from-github

**Comment by NickVolynkin** [comment]
@comradekingu thanks for the idea. I didn't know about Weblate yet. I've looked at other opensource localization engines, but the UX and translation capabilities weren't good enough. Translators need powerful tools, and we (the docs team) want to minimize the effort for implementing continuous localization. Crowdin seemed to satisfy both parties and we could afford the price, so we took it.

Maybe Weblate would be fine too. We'll have a look at it somewhere at the point when we'll have an established localization process.

The project https://github.com/WeblateOrg/weblate looks impressive. I've added my star. Extra kudos for using Sphinx in documentation.

**Comment by NickVolynkin** [comment]
@comradekingu oh, and Crowdin does have a GitHub integration too. We just want to start with a more manual process to be able to test translations before we merge them.

**Comment by comradekingu** [comment]
The usual way is to accept PRs once they come in. If for some reason there is anything malicious it can be fixed, producing a good version built for release. Just for documentation I don't see why the Wikipedia model wouldn't work.
Not that there aren't more stringent ways to do things, it is just that 100% of the projects I am in attempting it so far have implemented sub-par systems.

Provided the Enterprise Edition modules are also libre software you can add me as a Weblate admin. :)
