### ISSUE TITLE
Guidelines for the commit messages

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/doc#194]
I propose to introduce guidelines for the commit messages in all our repositories.

1. Separate subject from body with a blank line.
2. Try to limit the subject line to **50 characters** or so.
3. Start the subject line from a capital letter unless it prefixed with a subsystem name and semicolon:

+ memtx:
+ vinyl:
+ xlog:
+ replication:
+ recovery:
+ iproto:
+ net.box:
+ lua:

4.  Do not end the subject line with a period.
5.  Don't put "gh-xx", "closes #xxx" to the subject line.
6.  Use the imperative mood in the subject line.
   A properly formed Git commit subject line should always be able to complete the following sentence: "If applied, this commit will /your subject line here/"
7.  Wrap the body to **72 characters** or so.
8.  Use the body to explain what and why vs. how.
9.  Link GitHub issues on the lasts lines ([see how](https://help.github.com/articles/closing-issues-via-commit-messages/)).
10. Use your real name and real email address.
      **@tarantool.org** email is preferred for Tarantool Team members, but not mandatory.

A template:

```
Summarize changes in around 50 characters or less

More detailed explanatory text, if necessary. Wrap it to about 72
characters or so. In some contexts, the first line is treated as the
subject of the commit and the rest of the text as the body. The
blank line separating the summary from the body is critical (unless
you omit the body entirely); various tools like `log`, `shortlog`
and `rebase` can get confused if you run the two together.

Explain the problem that this commit is solving. Focus on why you
are making this change as opposed to how (the code explains that).
Are there side effects or other unintuitive consequences of this
change? Here's the place to explain them.

Further paragraphs come after blank lines.

 - Bullet points are okay, too

 - Typically a hyphen or asterisk is used for the bullet, preceded
   by a single space, with blank lines in between, but conventions
   vary here

Fixes: #123
Closes: #456
Needed for: #859
See also: #343, #789
```

Some real-world examples: 

- https://github.com/tarantool/tarantool/commit/2993a75858352f101deb4a15cefd497ae6a78cf7  
- https://github.com/tarantool/tarantool/commit/ccacba28f813fb99fd9eaf07fb41bf604dd341bc 
- https://github.com/tarantool/tarantool/commit/386df3d3eb9c5239fc83fd4dd3292d1b49446b89
- https://github.com/tarantool/tarantool/commit/076a842011e09c84c25fb5e68f1b23c9917a3750

Based on [1] and [2].

[1]: https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project
[2]: https://chris.beams.io/posts/git-commit/

**Comment by rtsisyk** [comment]
Test

**Comment by rtsisyk** [comment]
Test

**Comment by rtsisyk** [comment]
Hi,

Please upvote and comment [gh-194] ticket in tarantool/doc:

[gh-194]: https://github.com/tarantool/doc/issues/194

-- 
WBR,
  Roman Tsisyk < roman@tarantool.org >
  http://tarantool.org/ - an efficient in-memory data store and a Lua application server

**Comment by bigbes** [comment]
5 - I'd prefer usage of gh-***, but ofc not in the subj.
7 - why're you proposing using 72 symbols?
10 - why?

Also i'd propose to stop using user names in branch name (strict format like `gh-<issue>-short-explanation`)

**Comment by Totktonada** [comment]
2 - shouldn't be hard limit (IMO + suggested in [2] + saw in some other docs before).

**Comment by rtsisyk** [comment]
> 5 - I'd prefer usage of gh-***, but ofc not in the subj.

Currently #NNN is used more often than gh-NNN.
Shall we copy-paste the full link to the ticket instead of #NNN and gh-NNN?

> 7 - why're you proposing using 72 symbols?

80 characters per limit is the standard limit for the most texts, derived from ancient typewriters and teletypewriters. 72 is the same 80, but with some spaces at the end of lines just for visual beauty.

> 10 - why?

Because we do code review via `commits@` and you should receive review comments into your work mailbox instead of your personal mailbox. Some people forwards all emails into single mailbox, but I discourage this practice.

**Comment by rtsisyk** [comment]
> 2 - shouldn't be hard limit (IMO + suggested in [2] + saw in some other docs before).

50 characters in header is important for `git log`/`git shortlog` and GitHub interface. 
Longer messages will be truncated by the most places anyway.

**Comment by rtsisyk** [comment]
@kostja @locker @Sulverus @dedok @Gerold103 @alyapunov @kyukhin @racktear I need your feedback on this proposal. Please reply to the ticket or ask me questions privately using Telegram.

**Comment by kyukhin** [comment]
I am OK w/ the proposal.

**Comment by Gerold103** [comment]
Ok

**Comment by alyapunov** [comment]
1. What about ``vinyl:`` prefix in the subject line - should we start it with capital letter?
2. I'm sure we must add special place for obligatory reviewer's info. 
3. I can hardly understand 80 chars limit, but 72 completely confuses me.

**Comment by Totktonada** [comment]
2.

> 50 characters in header is important for git log/git shortlog and GitHub interface.
> Longer messages will be truncated by the most places anyway.

Yep, the first 50 symbols part should provide enough information for `git shortlog` and so on, but cases when shortlog readability doesn’t become worse (i.e. a long word at the end exceeds the line length limit) the limit shouldn’t be forced. The Linux kernel [documentation](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/submitting-patches.rst) suggests 70-75 limit, but most people [tries](http://stackoverflow.com/a/11993051/1598057) to fit its titles into 50.

7.

> On an 80 column terminal, if we subtract 4 columns for the indent on the left and 4 more for symmetry on the right, we’re left with 72 columns.

via http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

> 3. I can hardly understand 80 chars limit, but 72 completely confuses me.

So 76 should be okay too, but can looks worse. Vim wraps commit mesages with 72 characters limit, so for many people it’s easier just using that wrapping rule.

**Comment by rtsisyk** [comment]
> 3. I can hardly understand 80 chars limit, but 72 completely confuses me.

From https://medium.com/@preslavrachev/what-s-with-the-50-72-rule-8a906f61f09c:

The reason for wrapping your description lines at the 72nd mark is that git log adds a padding of 4 blank spaces when displaying the commit message. To center the message perfectly, and make it read well on an 80-column terminal, you’d want to leave space for 4 more blank spaces at right side. That’s where 72 comes from.

**Comment by rtsisyk** [comment]
> 1. What about vinyl: prefix in the subject line - should we start it with capital letter?
> 2. I'm sure we must add special place for obligatory reviewer's info.

I'd like to discuss these two questions outside of context of this proposal.

**Comment by alyapunov** [comment]
72 - got it

**Comment by bigbes** [comment]
> To center the message perfectly, and make it read well on an 80-column terminal, you’d want to leave space for 4 more blank spaces at right side. That’s where 72 comes from.

It wont be centered perfectly, until you use 'center spaced' in microsoft office, so it sounds.. bad

**Comment by kostja** [comment]
I'd love to see system name as the first word of the subject line.

We could have a list of appproved subsystems, such as:
vinyl:
memtx:
engine api:
xlog:
replication:
recovery: 
iproto:
lua:
Otherwise, LGTM

**Comment by Sulverus** [comment]
Looks nice, but 
```
5. Don't put "gh-xx", "closes #xxx" to the subject line
```

Why?

**Comment by locker** [comment]
> 2. Limit the subject line to 50 characters

We should definitely strive to keep the summary line as short as possible, but sometimes you happen to be just a few characters short to squeeze a meaningful description in 50 characters. That said, I think the limit should be 72 while 50 should stay for recommended length.

> 3. Start the subject line from a capital letter

... unless you don't prefix it with a subsystem name and semicolon (like "vinyl:"), in which case it's OK to use lower-case IMHO.

> 10. Use your real name and @tarantool.org email

Real name is fine, but I don't think @tarantool.org should be mandatory, because once you're out of the team, your mailbox will probably get abandoned or even deleted making it impossible to get in touch with you. That's why I prefer to use my private e-mail.

**Comment by dedok** [comment]
Each point looks great. But I have say that '10.' should be recommendation. Because Tarantool is open source project, every can do some commits.

**Comment by racktear** [comment]
@Sulverus Yes, it is bad, in particular because most people looking at commit history are not interested in github issue numbers. Thus, it should not show up in summary. If you need it, put it in body.

See https://chris.beams.io/posts/git-commit/

**Comment by rtsisyk** [comment]
> Why?
Implemented <xxx> support in <yyy> gh-xx is bad subject?

@Sulverus I agree with @racktear here.

**Comment by rtsisyk** [comment]
@locker:

>        Limit the subject line to 50 characters
>
>We should definitely strive to keep the summary line as short as possible, but sometimes you happen >to be just a few characters short to squeeze a meaningful description in 50 characters. That said, I >think the limit should be 72 while 50 should stay for recommended length.

Changed to "Try to limit the subject line to **50 characters** or so"

@locker:
>         Start the subject line from a capital letter
>
>... unless you don't prefix it with a subsystem name and semicolon (like "vinyl:"), in which case it's OK to use lower-case IMHO.

Changed to "Start the subject line from a capital letter unless it prefixed with a subsystem name and semicolon"

@locker:

>> Use your real name and @tarantool.org email
>
> Real name is fine, but I don't think @tarantool.org should be mandatory, because once you're out of the team, your mailbox will probably get abandoned or even deleted making it impossible to get in touch with you. That's why I prefer to use my private e-mail.

@dedok:
> Each point looks great. But I have say that '10.' should be recommendation. Because Tarantool is open source project, every can do some commits.

Changed to "Use your real name and real email address. @tarantool.org email is preferred for Tarantool Team members, but not mandatory."

**Comment by rtsisyk** [comment]
@kostja:

> We could have a list of appproved subsystems

Added to the spec, let's add more names later

**Comment by Totktonada** [comment]
Should we specify form of verb in a title: infinitive or -ed? As I see there is no widely-preferred approach and I often saw as `Fix …` as well as `Fixed …` commit titles. Any thoughts?

Of course we should specify it only for commit messages where it’s applicable. The example of case where it doesn’t applicable: `statistics counts foo value` (when some behaviour changed and ‘changed to’ is omitted).

**Comment by racktear** [comment]
@Totktonada The article that I mentioned above suggests to prefer "Fix" over "Fixed". See https://chris.beams.io/posts/git-commit/

**Comment by Totktonada** [comment]
Ouch, this mentioned in the proposal itself, I missed it somehow. Using imperative mood is okay for me. From the other side, should we prohibit ‘description of a commit content’ titles (like ‘More fixes for broken stuff’)?
