### ISSUE TITLE
Layout improvements

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#195]
For LT prototype shared on May 04:

![1](https://cloud.githubusercontent.com/assets/16703423/25697681/8dd87c62-30c4-11e7-9fcb-d6d1964bbe1e.png)
- [x] main menu should be left-aligned, like the frames below
- [x] section header ("Overview" here) should be left-aligned too
- [x] on wide screen, we now get too much white space on the right

**Comment by bigbes** [comment]
Everything on [page](https://tarantool.org/doc/1.7/reference/reference_lua/index.html):

![image](https://user-images.githubusercontent.com/495636/26932539-6ab38d8a-4c6c-11e7-98e5-3dd2ece441ae.png)
Left TOC in documentation doesn't have margins - looks not-so-good.

![image](https://user-images.githubusercontent.com/495636/26932588-9871ec76-4c6c-11e7-9aed-f75ed43a7e1d.png)
In case width is lesser than X there's white strip on the right.

**Comment by lenkis** [comment]
- [ ] content is trimmed in mobile version (portrait orientation; landscape looks ok) 

![img_2017-06-09 14 41 49](https://user-images.githubusercontent.com/16703423/26973970-bfbf6776-4d21-11e7-9881-18bcb3ff8e5a.jpg)

**Comment by lenkis** [comment]
All reported bugs fixed by https://github.com/tarantool/doc/pull/225
