### ISSUE TITLE
Add tarantool 1.8 to download page

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/doc#196]
We plan to release 1.8.0 alpha with SQL support in the next couple days. 
Please add 1.8 version to a combo box on https://tarantool.org/en/download.html. A PackageCloud repository for 1.8 has already been created.

**Comment by bigbes** [comment]
Fixed using https://github.com/tarantool/doc/commit/649870f9f493db6b2b6ff2a9cb253e489c99cb57
