### ISSUE TITLE
[0pt] Name for Cartridge docs in the TOC

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#1996]
## Info

Cartridge docs are under "Cluster" in the table of contents. ORLY? YARLY!

## What's wrong?

> В меню это называется Cluster, а не Cartridge 

https://app.mopinion.com/dashboard/inbox/detail/4441615

**Comment by patiencedaur** [comment]
"Cartridge" confuses new users, while "Cluster" confuses old users. We need to work out a different solution.
