### ISSUE TITLE
Remove absolute links from web-site

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/doc#2]
Why do we use absolute links (http://tarantool.org)? I's annoying when compiling documentation locally.

**Comment by bigbes** [comment]
We use them only in the headers

**Comment by bigbes** [comment]
This will be done, when we'll finish work on migrating [rocks](http://rocks.tarantool.org) into ["new rocks page"](http://tarantool.org/rocks.html) and embedding [try](http://try.tarantool.org) into our web-site.
