### ISSUE TITLE
[1pt] Remove branches 2.2.—2.5 from selector

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#2009]
Do it after https://github.com/tarantool/doc/issues/1923
# Definition of done

- [x] version selector shows only 1.6, 1.10 and latest
- [x] links to 2.x versions are redirected to latest
- [ ] Latest version is shown as "latest (v. 2.x)" in the selector.

**Comment by artembo** [comment]
@NickVolynkin from selector or from website? 
do we need to redirect from the old versions?

**Comment by NickVolynkin** [comment]
@artembo почему эту задачу убрали из спринта?

**Comment by artembo** [comment]
Я спросил у команды, все ли готово к удалению версий, мне сказали, что лучше дождаться тебя
