### ISSUE TITLE
[2pt] Include cartridge-cli/doc files in the build

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#2010]
# What needs to be done

Files under https://github.com/tarantool/cartridge-cli/tree/master/doc aren't included in the documentation. We should copy them in build_submodules.sh and connect to a parent document
**Reviewer:**

# Definition of done

- [ ] copy files in build_submodules.sh
- [ ] connect them via the `toctree` directive

**Comment by patiencedaur** [comment]
Cartridge CLI docs are in the build. Closing.
