### ISSUE TITLE
1.7.4 changelog

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/doc#202]
I will use this ticket to prepare 1.7.4 changelog. Unfortunately, this is the only way to collaborate on a markdown document on GitHub, because Wiki doesn't work as expected.

--------------------

## Tarantool 1.7.4 (RC)

Date: 2017-05-12

Tag: `1.7.4`.

1.7.4 is a release candidate in the 1.7 series. It is backward compatible with 1.6 in binary data layout, client-server protocol and replication protocol.

Vinyl Engine, the flagship feature of 1.7.x, is now feature-complete. All core features were finished and there are no known crashes, bad results or other showstopper bugs. 

## Incompatible changes

- box.cfg() options were changed to add Vinyl support:
   * `snap_dir` renamed to `memtx_dir`
   * `slab_alloc_arena`  (gigabytes) renamed to `memtx_memory` (bytes),
      default value changed from 1Gb to 256MB
   * `slab_alloc_minimal` renamed to `memtx_min_tuple_size`
   * `slab_alloc_maximal` renamed to `memtx_max_tuple_size`
   * `slab_alloc_factor` is deprecated, not relevant in 1.7.x
   * `snapshot_count` renamed to `checkpoint_count`
   * `snapshot_period` renamed to `checkpoint_interval`
   * `rows_per_wal` renamed to `wal_max_size`
   * `logger` renamed to `log`
   * `logger_nonblock` renamed to `log_nonblock`
   * `logger_level` renamed to `log_level`
   * `replication_source` renamed to `replication`
   * `panic_on_snap_error = true` and `panic_on_wal_error = true`
      superseded by `force_recovery = false`
  Until Tarantool 1.8, you can use deprecated parameters for both initial and runtime configuration, but such usage will print a warning in the server log. 
   [#1927](https://github.com/tarantool/tarantool/issues/1927)
   [#2042](https://github.com/tarantool/tarantool/issues/2042)

- Hot standy mode is now off by default. Tarantool automatically detects another running instance in the same `wal_dir` and refuses to start. Please use `box.cfg {hot_standby = true}` to enable the hot standby mode.
  [#775](https://github.com/tarantool/tarantool/issues/775)

- UPSERT via a secondary key was banned to avoid unclear semantics.
  [#2226](https://github.com/tarantool/tarantool/issues/2226)

- `box.info` and `box.info.replication` format was changed to display information about upstream and downstream connections:
   * Added `box.info.replication[instance_id].downstream.vclock` to display
     the last sent row to remote replica
   * Added `box.info.replication[instance_id].id`
   * Added `box.info.replication[instance_id].lsn`
   * Moved `box.info.replication[instance_id].{vclock,status,error}` to
    to `box.info.replication[instance_id].upstream.{vclock,status,error}`
   * all registered replicas from `box.space._cluster` are included in `box.info.replication` output
   * `box.info.server.id` renamed `box.info.id`
   * `box.info.server.lsn` renamed `box.info.lsn`
   * `box.info.server.uuid` renamed `box.info.uuid`
   * `box.info.cluster.signature` renamed to `box.info.signature`
   * `box.info.id` and `box.info.lsn` now return `nil` instead of `-1` during initial cluster bootstrap.
  [#723](https://github.com/tarantool/tarantool/issues/723)

- net.box: added per-request options to all requests:
  * `conn.call(func_name, arg1, arg2,...)` changed to
    `conn.call(func_name, {arg1, arg2, ...}, opts)`
  * `conn.eval(func_name, arg1, arg2,...)` changed to
    `conn.eval(func_name, {arg1, arg2, ...}, opts)`
  * All requests now support `timeout = <seconds>`, `buffer = <ibuf>` options
  * Added `connect_timeout` option to `netbox.connect()`
  * `netbox:timeout()` and `conn:timeout()` are now deprecated
  Please use `netbox.connect(host, port, { call_16 = true })` for 1.6.x-compatible behavior.
  [#2195](https://github.com/tarantool/tarantool/issues/2195)

- systemd configuration changed to support `Type=Notify` / `sd_notify()`.
  Now `systemctl start tarantool@INSTANCE` will wait until Tarantool has started and recovered from xlogs. The recovery status is reported to `systemctl status tarantool@INSTANCE`.
  [#1923](https://github.com/tarantool/tarantool/issues/1923)

- `log` module now doesn't prefix all messages with the full path to tarantool binary when used without box.cfg()
  [#1876](https://github.com/tarantool/tarantool/issues/1876)

- `require('log').logger_pid()` was renamed to `require('log').pid()`.
  [#2917](https://github.com/tarantool/tarantool/issues/2197)

- Removed Lua 5.0 compatible defines and functions:
    - `luaL_reg`  removed in favor of  `luaL_Reg`
    - `luaL_getn(L, i)` removed in favor of `lua_objlen(L, i)`
   - `luaL_setn(L, i, j)` removed (was no-op)
    - `lua_ref(L, lock)` removed in favor of `luaL_ref(L, lock)`
    -  `lua_getref(L,ref)` removed in favor of  `lua_rawgeti(L, LUA_REGISTRYINDEX, (ref))`
    - `lua_unref(L, ref)` removed in favor of `luaL_unref(L, ref)`
    - `math.mod()` removed in favor of `math.fmod()`
    - `string.gfind()` removed in favor of `string.gmatch()`
  [#2396](https://github.com/tarantool/tarantool/issues/2396)

See the full list of incompatible changes since 1.6.9 in [1.7.1](https://github.com/tarantool/tarantool/releases/tag/1.7.1), [1.7.2](https://github.com/tarantool/tarantool/releases/tag/1.7.2) and [1.7.3](https://github.com/tarantool/tarantool/releases/tag/1.7.3) release notes.

## Functionality added or changed

* Vinyl: multi-level compaction
  The compaction scheduler now groups runs of the same range into levels to reduce the write amplification during compaction. This design allows Vinyl to support 1:100+ ram:disk use-cases.
  [#1821](https://github.com/tarantool/tarantool/issues/1821)

* Vinyl: bloom filters for sorted runs
  Bloom filter is a probabilistic data structure which can be used to test whether a requested key is present in a run file without reading the actual file from the disk. Bloom filter may have false-positive matches but false-negative matches are impossible. This feature reduces the number of seeks needed for random lookups and speeds up REPLACE/DELETE with enabled secondary keys.
  [#1919](https://github.com/tarantool/tarantool/issues/1919)

* Vinyl: key-level cache for point lookups and range queries.
  Vinyl storage engine caches selected keys and key ranges instead of entire disk pages like in traditional databases. This approach is  more efficient because the cache is not polluted with raw disk data.
  [#1692](https://github.com/tarantool/tarantool/issues/1692)

* Vinyl: implemented the common memory level for in-memory indexes.
  Now all in-memory indexes of a space store pointers to the same tuples instead of cached secondary key index data. This feature significantly reduces the memory footprint in case of secondary keys.
  [#1908](https://github.com/tarantool/tarantool/issues/1908)

* Vinyl: new implementation of initial state transfer of JOIN command in replication protocol. New replication protocol fixes problems with consistency and secondary keys. We implemented a special kind of low-cost database-wide read-view to avoid dirty reads in JOIN procedure. This trick is not possible in traditional B-Tree based databases.
  [#2001](https://github.com/tarantool/tarantool/issues/2001)

* Vinyl: index-wide mems/runs
  Removed ranges from in-memory and and the stop layer of LSM tree on disk.
  [#2209](https://github.com/tarantool/tarantool/issues/2209)

* Vinyl: coalesce small ranges
  Before dumping or compacting a range, consider coalescing it with its neighbors.
  [#1735](https://github.com/tarantool/tarantool/issues/1735)

* Vinyl: implemented transnational journal for metadata
  Now information about all Vinyl files is logged in a special .vylog file.
  [#1967](https://github.com/tarantool/tarantool/issues/1967)

* Vinyl: implemented consistent secondary keys
  [#2410](https://github.com/tarantool/tarantool/issues/2410)

* Memtx, Vinyl: implemented low-level Lua API to create consistent backups of Memtx + Vinyl data. The new feature provides `box.backup.start()/stop()`  functions to create backups of all spaces. `box.backup.start()` pauses garbage collection and returns the list of files to copy. These files then
can be copied be any third-party tool, like cp, ln, tar, rsync, etc. `box.backup.stop()` resumes the background garbage collection process. Created backups can be restored instantly by copying into a new directory  and starting a new Tarantool instance. No special preparation, conversion  or unpacking is needed. 
  [#1916](https://github.com/tarantool/tarantool/issues/1916)

* Vinyl: added statistics for background workers to box.info.vinyl()
  [#2005](https://github.com/tarantool/tarantool/issues/2005)

* Memtx/Vinyl: reduced the memory footprint for indexes which keys are sequential and start from the first field. This optimization was necessary for secondary keys in Vinyl, but we optimized Memtx as well.
  [#2046](https://github.com/tarantool/tarantool/issues/2046)

- LuaJIT was rebased on the latest 2.1.0b3 with out patches:
   * Added JIT compiler backend for ARM64
   * Added JIT compiler backend and interpreter for MIPS64
   * Added some more Lua 5.2 and Lua 5.3 extensions
   * Fixed several bugs
   * Removed Lua 5.0 legacy (see incompatible changes above)
  [#2396](https://github.com/tarantool/tarantool/issues/2396)

- Enabled a new smart string hashing algorithm in LuaJIT to avoid significant slowdown when a lot of collisions are generated.
  Contributed by Yury Sokolov (@funny-falcon) and Nick Zavaritsky (@mejedi).
  [tarantool/luajit#2](https://github.com/tarantool/luajit/pull/2)

- box.snapshot() now updates mtime of a snapshot file if there were no changes to the database since the last snapshot.
  [#2045](https://github.com/tarantool/tarantool/issues/2045)

- Implemented `space:bsize()` to return the memory size utilized by all tuples of the space.
  Contributed by Roman Tokarev (@rtokarev).
  [#2043](https://github.com/tarantool/tarantool/issues/2043)

- Exported new Lua/C functions to public API:
  * `luaT_pushtuple`, `luaT_istuple`
  * `luaT_error`, `luaT_call`, `luaT_cpcall`
  * `luaT_state`
  [#1878](https://github.com/tarantool/tarantool/issues/1878)
  [#2291](https://github.com/tarantool/tarantool/issues/2291)
  [#2416](https://github.com/tarantool/tarantool/pull/2416)

- Exported new Box/C functions to public API:
  * `box_key_def`, `box_tuple_format`,  `tuple_compare()`,
    `tuple_compare_with_key()`
  [#2225](https://github.com/tarantool/tarantool/issues/2225)

- xlogs now can be rotated based on size (`wal_max_size`) as well as the number of written rows (`wal_max_rows`).
  [#173](https://github.com/tarantool/tarantool/issues/173)

* Added string.split(), string.startswith(), string.endswith(),
  string.ljust(), string.rjust(), string.center() API
  [#2211](https://github.com/tarantool/tarantool/issues/2211)
  [#2214](https://github.com/tarantool/tarantool/issues/2214)
  [#2215](https://github.com/tarantool/tarantool/issues/2215)

* Added `table.copy()` and `table.deepcopy()` functions
  [#2212](https://github.com/tarantool/tarantool/issues/2212)

* Added `pwd` module to work with UNIX users and groups
  [#2213](https://github.com/tarantool/tarantool/issues/2213)

- `box.session.on_connect()/on_disconnect()/on_auth()` triggers now also fired for admin console connections.
  [#1938](https://github.com/tarantool/tarantool/issues/1938)

- Removed noisy "client unix/: connected" messages from logs. Please use box.session.on_connect()/on_disconnect()` triggers instead.
  [#1938](https://github.com/tarantool/tarantool/issues/1938)

- tarantoolctl: `eval`, `enter`, `connect` commands now support UNIX pipes.
  [#672](https://github.com/tarantool/tarantool/issues/672)

- tarantoolctl: improved error messages and added a new man page.
  [#1488](https://github.com/tarantool/tarantool/issues/1488)

- tarantoolctl: added filter by `replica_id` to `cat` and `play` commands
  [#2301](https://github.com/tarantool/tarantool/issues/2301)

- tarantoolctl: `start`, `stop` and `restart` commands now redirect to `systemctl start/stop/restart` when systemd is enabled.
  [#2254](https://github.com/tarantool/tarantool/issues/2254)

- net.box: added `buffer = <buffer>` per-request option to store raw MessagePack responses into a C buffer.
  [#2195](https://github.com/tarantool/tarantool/issues/2195)

- net.box: added `connect_timeout` option
  [#2054](https://github.com/tarantool/tarantool/issues/2054)

- net.box: added `on_schema_reload()` hook
  [#2021](https://github.com/tarantool/tarantool/issues/2021)

- net.box: exposed `conn.schema_version` and `space.connection` to API
  [#2412](https://github.com/tarantool/tarantool/issues/2412)

- log: debug()/info()/warn()/error() now doesn't fail on formatting errors.
  [#889](https://github.com/tarantool/tarantool/issues/889)

- crypto: added HMAC support
  Contributed by Andrey Kulikov (@amdei).
  [#725](https://github.com/tarantool/tarantool/issues/725)

## Bugs fixed

- Dozens of bug fixed in Vinyl engine, see the full list on
  [GitHub](https://github.com/tarantool/tarantool/issues?q=milestone%3A1.7.4+label%3Avinyl)
  for details

- Box: server crashes if checkpoint starts while ddl works
  [#2260](https://github.com/tarantool/tarantool/issues/2260)

- Box:  fixed "SIGINT doesn't stop recovery from snapshot"
  [#2108](https://github.com/tarantool/tarantool/issues/2108)

- Box: fixed "space:truncate() can produce garbage xlog output"
  [#2078](https://github.com/tarantool/tarantool/issues/2078)

- Box: fixed "tarantool crashes on fiber:wakeup()"
  [#2260](https://github.com/tarantool/tarantool/issues/2260)

- Box: fixed box.cfg() without options
  [#2191](https://github.com/tarantool/tarantool/issues/2191)

- Box: fixed a crash in box.error() with invalid arguments
  [#2080](https://github.com/tarantool/tarantool/issues/2080)

- Box: fixed box.session.su() with invalid arguments
  [#2063](https://github.com/tarantool/tarantool/issues/2063)

- Box: fixed login/password disclosure when setting 'replication_source'
  [#1924](https://github.com/tarantool/tarantool/issues/1924)

- Box: fixed double scan of the last WAL file on recovery
  [#1784](https://github.com/tarantool/tarantool/issues/1784)

- Box: fixed `space:upsert()` and `:auto_increment()` in absence of indices
  [#2258](https://github.com/tarantool/tarantool/issues/2258)
  [#2259](https://github.com/tarantool/tarantool/issues/2259)

- Box: fixed space:format()
  [#2391](https://github.com/tarantool/tarantool/issues/2391)

- net.box: fixed space:format()
  [#2402](https://github.com/tarantool/tarantool/issues/2402)

- Fxed inconsistent behaviour of tonumber64() and tonumber()
  [#1963](https://github.com/tarantool/tarantool/issues/1963)

- Fixed "tonumber64() doesn't handle negative numbers properly"
  [#1554](https://github.com/tarantool/tarantool/issues/1554)

- tarantoolctl: fixed "instance_dir ignored on local .tarantoolctl config"
  [#1909](https://github.com/tarantool/tarantool/issues/1909)

- tarantoolctl: fixed invalid strings produced by `play` and `cat`
  [#2262](https://github.com/tarantool/tarantool/issues/2262)

- tarantoolctl: fixed "failed to remove pid file"
  [#2190](https://github.com/tarantool/tarantool/issues/2190)

- tarantoolctl: fixed support for custom logger
  [#1423](https://github.com/tarantool/tarantool/issues/1423)

- Fixed various problems found by Coverity, PVS-Studio and other static analyzing tools.
  [#2035](https://github.com/tarantool/tarantool/issues/2035)

- Fixed all flaky tests

A full list of fixed bugs is available on [GitHub](https://github.com/tarantool/tarantool/issues?q=milestone%3A1.7.4+is%3Aclosed).

**Comment by funny-falcon** [comment]
> Enabled a new smart string hashing... Сontributed by Yury Sokolov (@funny-falcon).

Я думаю, будет справедливо также упомянуть Nick Zavaritsky @mejedi , т.к. он мне довольно хорошо помог.
