### ISSUE TITLE
[4pt] Push translations to Crowdin-branches and pull them back

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#2038]
# What needs to be done

A CI workflow for updating translations, just like in https://github.com/tarantool/tdg-doc/issues/104

# Definition of done

New CI workflow should do the following:

- [ ] push translation sources from PR to a Crowdin-branch
- [ ] pull translations back, commit to the same branch

---

Task changed significantly after success with https://github.com/tarantool/tdg-doc/issues/104

**Comment by artembo** [comment]
Unfortunately, according to [github actions documentation](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule) triggering from cron works only for default branch. 

We have two options:
- trigger manually for 1.10 branch when on demand
- set up external cron which would trigger workflow
