### ISSUE TITLE
[2pt] Localize 1.10 via Crowdin

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#2046]
# What needs to be done

**Reviewer:** @NickVolynkin 

# Definition of done

- [ ] Add config for branch 1.10 
- [ ] Push to branch 1.10 at Crowdin

**Comment by artembo** [comment]
@NickVolynkin do you reckon crowdin branch will work for our purposes? For me the new dedicated project for 1.10 branch is a better choice, because 1.10 and 2.x are too different to be a branch in crowdin.
