### ISSUE TITLE
[Tech debt] Integrate docs and trainings

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#2052]
Integrate Tarantool documentation and trainings:

* Write training instructions in rST/Sphinx, publish via the same pipeline to a closed part of tarantool.io
* Use the same page desing for docs and training instructions
* Translate slides & instructions via Crowdin
* Use verifiable links from trainings to docs
* Add training materials to search results for user with access to them

- [x] https://github.com/tarantool/doc/issues/2805

**Comment by p7nov** [comment]
Closing: out of scope. Trainings have been moved to a separate platform.
