### ISSUE TITLE
Document the effect of backup and replication on snapshot daemon.

### ISSUE THREAD

**Issue by kostja** [tarantool/doc#208]
In 1.7, the snapshot daemon creates a consistent checkpoint across all storage engines - memtx and vinyl. This checkpoint then can be used to bootstrap a replica in a replica set or to make a backup.

It is the snapshot daemon job now to delete write ahead logs which are no longer necessary for recovery or replication, old snapshots and vinyl .run files. It does this automatically in accordance to the guidelines set in snapshot daemon settings.

In particular, the snapshot daemon would never delete  a file which is used in an ongoing backup (i.e. someone started a backup by saying box.backup.begin()), ongoing replica join, or a write ahead log which has not been fed to a replica yet (this is not fixed yet, please track https://github.com/tarantool/tarantool/issues/748.

All these details need to be reflected in snapshot daemon documentation.

**Comment by lenkis** [comment]
Primarily here: https://tarantool.org/en/doc/1.7/reference/configuration/index.html#book-cfg-snapshot-daemon
