### ISSUE TITLE
[5pt] Describe English style to use in release notes

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#2111]
**Epic: [Release notes](https://github.com/tarantool/doc/issues/2570)**

# Describe English style to use in release notes

**Product:** Tarantool (mostly about tarantool, but I guess it is applicable for all products)
**Since:** N/A
**Audience/target:** Tarantool developers and documentarians
**Root document:** Somewhere around our documentation guides
**SME:** @ NickVolynkin, @ Gerold103, @ patiencedaur

# Details

See also: #1285

The discussion was started [here](https://github.com/tarantool/tarantool/pull/5935#discussion_r605901476). I'll cite:

> @Gerold103:
>
> You might notice that we use imperative in all changelog records. Would be good to be consistent.

> @Totktonada:
>
> In the past release notes:
>
> - Imperative mood is used when we start to do X: say, 'Deploy packages for Fedora 32 (gh-4966)'.
> - Past tense is used to describe a past (changed / fixed) behaviour: say, 'Fixed a false positive panic when yielding in debug hook (gh-5649)'.
> - Present tense is used to describe a new behaviour: say, 'Data changes in read-only mode are now forbidden (gh-5231)'.
>
> Unlike using an imperative mood, this approach results in a text that is 'written for a human', like an article about changes. For me, it looks good.
>
> However, I'm not an expert neither in grammar, nor in documentation writting, so it is better to ask @tarantool/doc team.
>
> > You might notice that we use imperative in all changelog records. Would be good to be consistent.
>
> There is no consistency in current unreleased changelog entries, but I hope we'll proof-read them before a next release and adjust to a certain style. We can elaborate some preliminary agreements with the documentation team here.

To be honest, I really don't spin around grammatic rules enough to insist on my vision. However it looks meaningful for me and if we'll agree on another set of rules, I would like to know a reasoning behind.

# Definition of done

- [ ] There is a page with recommendations how to write grammatically correct release notes.
- [ ] @Totktonada understands how to write changelog entries.

# Tentative directions

- [ ] Make a list of the most common problems documentarians *and translators* face with RNs. See #1285
- [ ] Analyze the corresponding sections (if they exist) in Microsoft and Google style guides
- [ ] Read the article [provided as a guideline](https://uxdesign.cc/the-art-of-writing-great-release-notes-6607e22efae1) in #1285
- [x] Outline the contents
- [ ] Start writing :)

---

]Notes from @ lenkis:

Problems with OS Tarantool release notes (RN):

1. No style guide for RN, so writers need to brush up the draft a lot (e.g. RN items are phrased differently).
TODO: Introduce a simple style guide for all RN contributors.

2. No automatic integration of RN into the manual, so writers need to do it manually.
TODO: If we continue mirroring RN in the manual, automate md-to-rst import.

3. Too wordy RN section in the manual, which adds no value beyond RN text at GH.
TODO: Think of making the most of RN as a community communication tool. Here is an article for inspiration: https://uxdesign.cc/the-art-of-writing-great-release-notes-6607e22efae1

---

Draft Notion document with ideas: https://www.notion.so/tarantool/WIP-Release-notes-workflow-b4292dbf8fbd41d58a1983546de4a879

**Comment by patiencedaur** [comment]
I agree with @Totktonada's linguistic suggestions in the description.

I have several more questions/comments about the process:

- Who launches gen-release-notes?
- Let's add links to gh-issues. The doc team does it manually now. Could the developers add these links to the individual changelog lines in .md? We will proofread everything that's in changelogs/unreleased by 28.01.2022, but let's add links as a regular practice from now on.
- Let's put the release notes to the right place in tarantool/doc automatically. I remember seeing a ticket about it somewhere.
- AFAIU, gen-release-notes generates CE notes. What's the status on EE notes---are they compiled manually?
- Help us make a list of pages that change with every new release (and version). One of these pages is [Major features](https://www.tarantool.io/en/doc/latest/release/major-features/) (related issue: https://github.com/tarantool/doc/issues/2571).
- What's the best place for the RN style guide?

**Comment by NickVolynkin** [comment]
```
pandoc -f md -t rst -o changelog.rst changelog.md
sed -i 's,gh-(\d*),:tarantool-issue:`$1`'
```
как-то так

**Comment by patiencedaur** [comment]
1. Кирилл с помощью gen-release-notes генерирует release notes для Tarantool CE и ставит тег. файл лежит в tarantool/changelogs
-- релиз появился на гитхабе --
2. документаторы приходят в папку и вручную оттуда забирают этот файл.
3. выполняют команды выше
4. вручную кладут файл в корень страницы https://www.tarantool.io/en/doc/latest/release/
5. обновляют страницы ниже по уровню
-- прошло 4 дня после релиза --
6. добавляются перекрёстные ссылки
(здесь идёт маркетинг)

Чем полнее документация, тем лучше, но сколько успеем к маркетинговой кампании

В ЕЕ, скорее всего, будет что-то похожее (повторить все действия)
Для TDG повторять шаги 2-5

**Comment by patiencedaur** [comment]
Document not only the verb form, but also formatting rules for cases like the following:

[2.4.0] - 2022-01-28
- disable autocomplete in the role editing form.
- clear the error message in the delete tenant modal.
...

parentheses and dash
ending punctuation
capitalization
