### ISSUE TITLE
[5pt] Update LuaJIT memory profiler description

### ISSUE THREAD

**Issue by Buristan** [tarantool/doc#2113]
# LuaJIT memprof documentation update

**Product:** Tarantool
**Since:** 2.8.1
**Audience/target:** developers
**Root document:** https://www.tarantool.io/en/doc/latest/book/app_server/luajit_memprof/
**SME:** @Buristan, @igormunkin 
**Peer reviewer:** @

# Details

Features introduced in Tarantool 2.8.1:
- More user friendly output (tarantool/tarantool#5811):
Now functions definition line number is hidden. Also, each of the counters has been named. If before output looked like the following:
```
ALLOCATIONS
@true_memleak.lua:6, line 9: 3	144	0
@true_memleak.lua:6, line 8: 2	41	0
```

Now it looks like the following:
```
ALLOCATIONS
@true_memleak.lua:9: 3 events	+144 bytes	-0 bytes
@true_memleak.lua:8: 2 events	+41 bytes	-0 bytes
``` 

- `--leak-only` flag of memprof parser (tarantool/tarantool#5812):

Now parser reports lines of code, that allocates some amount of bytes, which hasn't been freed during profiler recording.
The epilogue added to output has he following format:

```
HEAP SUMMARY:
"@<filename>:<line number> holds <amount of still reachable bytes> bytes: <amount of allocation events> allocs, <amount of deallocation events> frees"
```

With `--leak-only` option only epilogue is shown.

Now profiler parser should be run via the following command:
```bash
$ tarantool -e 'require("memprof")(arg)' - filename.bin
```
And with `--leak-only` option:
```bash
$ tarantool -e 'require("memprof")(arg)' - --leak-only filename.bin
```

Example of `--leak-only` output:
```
@builtin/box/console.lua:574 holds 3216 bytes: 108 allocs, 44 frees
CFUNC 0x403d0448 holds 2995 bytes: 1 allocs, 0 frees
```

# Definition of done

- [ ] Corresponding section is added to the documentation.
- [ ] Example how to parse memprof binary output is updated for 2.8.1+ versions.
- [ ] Structure of the document should be change to keep the description of the system behaviour for both 2.8.1 and 2.7.x

**Comment by veod32** [comment]
@Buristan @igormunkin Guys, 
1. 2.8.1 new features -- are they also present in the 2.7.2 version? 
2. Should we still keep the description of the 2.7.1 profiler behavior in the doc, what do you think? Can you think of some real use case when this 2.7.1 description will be useful for a user?

**Comment by igormunkin** [comment]
@veod32,
>  1. 2.8.1 new features -- are they also present in the 2.7.2 version?

Features -- no. E.g., `--leak-only` is introduced only in 2.8 series.

>  2. Should we still keep the description of the 2.7.1 profiler behavior in the doc, what do you think? Can you think of some real use cases when this 2.7.1 description will be useful for a user?

Yes, since there are difference in output between 2.7.2 and 2.8.1. I guess, we will make an iterative squash, when the old releases reach their EOL.

**Comment by fckxorg** [comment]
Since the documentation section with instructions for parsing memprof results no longer works for Tarantool 2.9.0, it would be great to update the docs

**Comment by Buristan** [comment]
Also, I suggest to add the following example:

Assume we have the following file named <true_memleak.lua>:

```lua
 1 -- For more verbose output.
 2 jit.off()
 3
 4 local ffi = require 'ffi'
 5
 6 -- Avoid GC to be triggered spontaneously.
 7 collectgarbage()
 8 local function fake_new()
 9   local ref = {}
10   local cdata = ffi.new('char[1]')
11   ffi.gc(cdata, function() print('cdata is collected', tostring(ref)) end)
12   ref.anchor = cdata
13 end
14
15 local binfile = '/tmp/memprof_'..(arg[0]):match('([^/]*).lua')..'.bin'
16
17 local st, err = misc.memprof.start(binfile)
18 assert(st, err)
19
20 fake_new()
21 collectgarbage()
22
23 local st, err = misc.memprof.stop()
24 assert(st, err)
25
26 print('exit')
27 os.exit()
```

If one runs it, the output from the script will be the following:
```
exit
```
As you can see cdata is not collected by the GC (see explanation in LuaJIT/LuaJIT#659).

The output of the profiler parser is the following:
```
ALLOCATIONS
@/home/burii/reports/demo_memprof/true_memleak.lua:11: 3 events +192 bytes      -0 bytes
@/home/burii/reports/demo_memprof/true_memleak.lua:10: 2 events +49 bytes       -0 bytes
@/home/burii/reports/demo_memprof/true_memleak.lua:12: 1 events +48 bytes       -0 bytes
@/home/burii/reports/demo_memprof/true_memleak.lua:9: 1 events  +64 bytes       -0 bytes

REALLOCATIONS

DEALLOCATIONS
@/home/burii/reports/demo_memprof/true_memleak.lua:10: 1 events +0 bytes        -32 bytes
        Overrides:
                @/home/burii/reports/demo_memprof/true_memleak.lua:10

INTERNAL: 1 events      +0 bytes        -37 bytes
@/home/burii/reports/demo_memprof/true_memleak.lua:11: 1 events +0 bytes        -48 bytes

HEAP SUMMARY:
@/home/burii/reports/demo_memprof/true_memleak.lua:11 holds 192 bytes: 3 allocs, 0 frees
@/home/burii/reports/demo_memprof/true_memleak.lua:9 holds 64 bytes: 1 allocs, 0 frees
@/home/burii/reports/demo_memprof/true_memleak.lua:12 holds 48 bytes: 1 allocs, 0 frees
@/home/burii/reports/demo_memprof/true_memleak.lua:10 holds 17 bytes: 2 allocs, 1 frees
```

The `HEAP SUMMARY` section shows that all objects referenced by cdata (and itself) are not collected.

**Comment by Buristan** [comment]
Also, I suggest to add the following example in **FAQ**.

**Q**: How can I compare the GC pressure and allocations profile by two different functions via the memory profiler?

**A**: You can create the simple wrapper around memprof:
```lua
local function wrap_memprof(filename, f, ...)
  -- Run full 2 GC cycles to collect all possible objects
  -- and ressurected objects after the first cycle.
  collectgarbage()
  collectgarbage()
  local st, err = misc.memprof.start(filename)
  assert(st, err)

  -- Function to profile.
  f(...)

  -- Run full 2 GC cycles to collect all possible objects
  -- and ressurected objects after the first cycle.
  collectgarbage()
  collectgarbage()
  st, err = misc.memprof.stop()
  assert(st, err)
end
```
and run it for two different functions with different filenames to profiler output.

It is better to do it via independent runs to avoid "objects clashing" (string interning, same table using and resizing, etc.; see the example with `format()` and `concat()` functions).
