### ISSUE TITLE
Document how to troubleshoot slow queries

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/doc#214]
Sometimes Tarantool can work with suboptimal performance due to various reasons (disk problems, CPu-intensive Lua scripts, misconfiguration, etc.). This is often accompanied by "W> too long DELETE: 8.546 sec" messages in Tarantool log. 

Please create a detailed guide how to collect the performance profile from the Tarantool for developers using various tools:

1. "poor man-profiler" using `pstack <pid>`
2. poor man-profiler" `gdb -ex "bt" -p <pid> -q` (use with caution) (see [this article](https://poormansprofiler.org/))
3. gperftools - https://github.com/tarantool/gperftools
4. perf

**Comment by lenkis** [comment]
@rtsisyk please give more details
