### ISSUE TITLE
[1pt] Broken link (SQL protocol)

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#2199]
https://tarantool.io/en/doc/2.1/dev_guide/internals/sql_protocol/

Via https://github.com/tarantool/go-tarantool/issues/70#issuecomment-439744822

It seems now it is on https://www.tarantool.io/en/doc/latest/dev_guide/internals/box_protocol/#box-protocol-sql-protocol

**Comment by NickVolynkin** [comment]
@Totktonada can't find such a link on the box_protocol page.

**Comment by Totktonada** [comment]
Ouch, I had intention to paste a link to my old message, but pasted the link to the new location of the document instead. Edited.

**Comment by NickVolynkin** [comment]
Check: https://www.tarantool.io/en/doc/2.1/dev_guide/internals/sql_protocol/

**Comment by patiencedaur** [comment]
Thanks, it works now! Closing.
