### ISSUE TITLE
Compatibility guarantees for updating Tarantool

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#2218]
**Epic: [Release notes](https://github.com/tarantool/doc/issues/2570)**

Related issues:
[Clarify tarantool update process to a newer major version (#836)](https://github.com/tarantool/doc/issues/836)
[Guide to upgrade from 1.6 to 1.10 (tarantool/#4934)](https://github.com/tarantool/tarantool/issues/4934)

# Compatibility guarantees

Write about compatibility guarantees for updating to the new Tarantool version

- добавить кросс-ссылку с upgrade или из release notes

**Product:** Tarantool
**Since:** 2.x
**Audience/target:** admins, developers, CTO's who decide if they can update Tarantool to 3.x or not
**Root document:** TBA, somewhere around release notes?
**SME:** @Totktonada @kyukhin 
**Peer reviewer:** @NickVolynkin

**Comment by patiencedaur** [comment]
Related issue: https://github.com/tarantool/enterprise_doc/issues/48

**Comment by Totktonada** [comment]
> JFYI: there's also an issue about describing _iterator_ compatibility guarantees tarantool/tarantool#2102

Not exactly: the linked issue is about so called stability guarantees. IOW, it is how the iterator behaves in case of database modifications during traversal using the iterator.
