### ISSUE TITLE
[3pt] Rework "Getting Started"

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#2220]
# Rework "Getting Started" chapter

**Product:** Tarantool
**Audience/target:** novice users
**Root document:** https://www.tarantool.io/en/doc/latest/getting_started/
**SME:** check with @Thorwinz 
**Peer reviewer:** @ documentarian name

# Details

@Thorwinz: в продолжении встречи (от 23.06.2021) с Николаем В., задача:

Модифицировать раздел "Getting started", таким образом, чтобы явно разделить "Установку Tarantool" от "Создания первой БД". В данный момент обе инструкции смешаны.
Наименования страниц, аналогично прописывать в явном виде:

1. "Установка Tarantool"
    a. "Using a Docker image"
    b. "Using a Package manager"
2. "Создание первой БД"

На странице "Установка Tarantool" дать ссылку на "Примечания к версиям Tarantool"(https://www.tarantool.io/ru/doc/latest/release/)

# Definition of done

- [ ] do A
- [ ] do B

**Comment by artur-barsegyan** [comment]
Не понял, зачем в разделе про установку необходимо давать ссылку на примечание к версиям. У пользователя на странице Downloads понятный выбор из текущей актуальной версии и старой.

**Comment by artur-barsegyan** [comment]
И мотивацию про изменение структуры документа я не понял. Тем более, это сейчас уже не главный туториал, а наследие для тех **кто знает, что ему это надо**.
