### ISSUE TITLE
Fix layout at doc 1.6 / 1.8 main page

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#223]
Pages https://tarantool.org/en/doc/1.6/index.html and https://tarantool.org/en/doc/1.8/index.html should look similar to https://tarantool.org/en/doc/1.7/index.html

**Comment by bigbes** [comment]
Well, that means that everything for design should be merged to 1.6 and
then 1.7->1.8

With best regards, Eugene.

2017-06-16 11:39 GMT+03:00 Elena Shebunyaeva <notifications@github.com>:
