### ISSUE TITLE
ошибка в примере с тестовым приложением

### ISSUE THREAD

**Issue by jmenhome** [tarantool/doc#224]
В разделе https://tarantool.org/ru/doc/1.7/book/administration.html#updating-tarantool-in-production есть пример тестового приложения. Непосредственно запуск описан следующим образом:
```
-- load a new version of app and all dependencies
myapp = require('myapp').start({some app options controlled by sysadmins})

```
Но в примере функция start не возвращает instance, т.е. в myapp попадает null. Измените пожалуйста документацию следующим образом:
```
-- load a new version of app and all dependencies
myapp = require('myapp')
myapp.start({some app options controlled by sysadmins})
```
либо добавьте в пример в функцию start возврат инстанса

**Comment by rybakit** [comment]
Еще, похоже, вместо 

```lua
return {
  start = start;
  stop = stop;
  api_for_call = api_for_call;
}
```

должно быть

```lua
return {
  start = start,
  stop = stop,
  api_for_call = api_for_call
}
```

**Comment by lenkis** [comment]
The defect is reported for an outdated version of this procedure.
Please see a new version here: https://tarantool.org/en/doc/1.7/book/admin/upgrades.html

Links to outdated documentation will be redirected to new content soon (https://github.com/tarantool/doc/issues/220).

**Comment by jmenhome** [comment]
New link have same version (1.7) and different content. Original page is about making test applicatin, btu new - about ugrading db. It is not same! Please fix error on pages that show how to create application in tarantool

**Comment by rybakit** [comment]
> It is not same! Please fix error on pages that show how to create application in tarantool

I second that. @lenkis can this issue be reopened?

**Comment by lenkis** [comment]
That's a fair claim. Re-opening the issue. We removed this howto altogether after heavy doc revision. Will soon add a revised version of it.

**Comment by lenkis** [comment]
will be part of gh-92
