### ISSUE TITLE
Left menu defects

### ISSUE THREAD

**Issue by bigbes** [tarantool/doc#229]
Mac OS - Chrome 58.0.3029.110 (64-bit)
* Right margin is 0:
  ![image](https://user-images.githubusercontent.com/495636/27492193-03d15474-584e-11e7-9df8-ad09534065cf.png)
* Arrows are changed and left padding(?) is messed up:
  ![image](https://user-images.githubusercontent.com/495636/27492203-1048bfb2-584e-11e7-8f73-409702aca2d7.png)
* Hyperlink icon overlaps with left menu:
  ![image](https://user-images.githubusercontent.com/495636/27511151-0d7be1f4-5927-11e7-97cc-a073c6db4ad8.png)

**Comment by lenkis** [comment]
Fixed by PT merge https://github.com/tarantool/doc/pull/238.
