### ISSUE TITLE
Behavior changes in SQL

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/doc#2296]
After discussion in https://github.com/tarantool/tarantool/issues/5956
I am adding this list of things that must change in the Tarantool manual
due to changes that have appeared in version 2.9, mostly due to
pushes from @ImeevMA. I will assign to myself if nobody objects
within a few days.

Updated comment: I originally wrote "2.9.0" because that's where the
changes are now. But now I see
https://github.com/tarantool/tarantool/releases/tag/2.10.0-beta1
A comment in isssue #2316 acknowledges this issue but release-note changes described here will only be read.
I continue to assume the rest of the description is necessary. 

In release/2.10.0.rst:

This file has not been created yet.
When it appears, this should be in the SQL section:

**Breaking change**:  NUMBER data type
Arithmetic (+ * - / % & | ~) operations and bit-shift operations (>> <<) are now illegal.
Example:
SELECT number_column + 1 was legal in version 2.8; now it will cause an error.

**Breaking change**: SCALAR data type
Arithmetic (+ * - / % & | ~) operation and bit-shift operations (>> <<) are now illegal.
Concatenation (||) operations are now illegal.
Values in SCALAR columns now have data type 'SCALAR', not the value's data type.
Example:
TYPEOF(CAST(1 AS SCALAR)) was 'integer' in version 2.8; now it will be be 'scalar'.

**Breaking change**: Explicit cast
CAST() between BOOLEAN or VARBINARY and INTEGER or UNSIGNED or NUMBER data types is now illegal.
Example:
CAST(FALSE AS INTEGER) was 0 in version 2.8; now it will cause an error.

**Breaking change**: TYPEOF()
TYPEOF(NULL) will now return 'NULL' if type cannot be determined from context.
TYPEOF(-NaN) will now return 'double'.
TYPEOF(map_column) will now return 'varbinary' instead of 'map'.
Example:
SELECT TYPEOF(NULL); was 'boolean' in version 2.8; now it will be 'NULL'.

**Breaking change**: Implicit conversions
Arithmetic operators must now have numeric operands, string operands are illegal.
Example:
SELECT 1 + '1'; was 2 in version 2.8; now it will cause an error.

**Breaking change**: Operations on SCALAR columns
Since the type of a value no longer determines whether an operation is valid, comparisons and functions which require a specific type will no longer work.
Example: if table T has only one row with a scalar column containing 'a':
UPPER(scalar_column) was 'A' in version 2.8; now it will cause an error.

**Breaking change**: The HEX() function
STRING arguments are no longer acceptable, only VARBINARY arguments are allowed.
Example:
HEX('a') was '41' in version 2.8; now it will cause an error.

**Breaking change**: The POSITION() function
VARBINARY arguments are no longer acceptable, only STRING arguments are allowed.
Example:
POSITION(X'41',X'41') was 1 in version 2.8; now it will cause an error.

In reference_sql/sql_beginners_guide.rst:

I don't see significant problems because we don't mention the changed items.

In reference_sql/sql_user_guide.rst:

Re Literals section:
Currently NULL is considered to be a Boolean literal, but that needs clarification.
The mention of "nan" needs to change.
The sentence beginning "Numeric literals may be quoted ..." is false now.

Re Operand data types section:
"NUMBER is a data type name, but number is a general term."
This illustrates something that will cause huge confusion -- I was sure
that descriptions about numbers would always be okay for all the
numeric data types. But now, for example, what is true for numbers in
general is not true for NUMBER. It will be confusing; some vocabulary
changes will be needed.

Re Operand data types section:
The paragraph beginning "NUMBER values have the same range ..." is false now.
The paragraph beginning "SCALAR can be used ..." is false now.
The sentence beginning "If the data type of NULL ..." is false now.
The sentence beginning "For example, SELECT "flags" FROM "_space"; is false now.
The sentence "In the following list of operators" needs to emphasize NUMBER won't work.

Re Special Situations section:
The mention of -nan needs to change.

Re Comparing and ordering section:
The paragraph beginning "When comparing a number to a STRING:" is false now.

Re Data Type Conversion section:
Mentions of numbers are false now because NUMBER is different.
Mentions of SCALAR are false now.
Among other things, we'll have to add NUMBER and SCALAR in the charts.
The sentence beginning "Since version 2.4.1, the NUMBER type" is false now.

Re Implicit string/numeric cast section:
This entire section is false now, maybe we can discard it but I must test more.

In reference_sql/sql_statements_and_clauses.rst:

Re Column definition – the rules for the SCALAR data type section:
Six of the ten items look okay, 4 look false now. SCALAR needs new explanation.
We may need a "Limitations:" addition for non-intuitive details, for example
SELECT TYPEOF((SELECT CAST('a' AS SCALAR) UNION SELECT CAST('a' AS SCALAR)));
is 'string' although SELECT TYPEOF(CAST('a' AS SCALAR)); is 'scalar'.

Re Column definition - the relation to NoSQL section:
"The rules for that NoSQL type are applicable to the SQL data type" is false now.
The mention of -nan needs to change.
The mention of map needs to change.

Re ORDER BY clause:
For "Sorting order:" we'll need to explain that SCALAR is not separate.

Re Functions clause:
Currently numeric-expression functions are okay but I believe this will change.
TYPEOF() says "Returns the data type of the expression."; now that might be false.
HEX() says the argument can be a byte sequence; now that is false.
POSITION() says the argument can be STRING or VARBINARY; now that is false.

In reference_sql/sql_features.rst:

For E011-04 "Arithmetic operators", and for E011-06 "Implicit casting among the numeric data types", we say "Okay". Now it's impossible to use arithmetic operators with NUMBER columns, or combine NUMBER with INTEGER etc. in some circumstances. So, in order to keep saying "Okay", I'm going to have to be careful to avoid suggesting that NUMBERs are numbers.

**Comment by veod32** [comment]
#2298
