### ISSUE TITLE
update instructions for downloading tarantool

### ISSUE THREAD

**Issue by VitaliyaIoffe** [tarantool/doc#2312]
The new release of tarantool with the tag `2.10.0-beta1` (new release policy) raises a few points, which should be fixed in the instructions for debian/ubuntu/centos/fedora.

This is a `beta` release. Until we don't have updated `installer.sh,` should use full manual instructions with next fixes.

1) Now packages are located `https://download.tarantool.org/tarantool/pre-release/series-2/os/` for beta and `https://download.tarantool.org/tarantool/release/series-2/os/`. Previously, `https://download.tarantool.org/tarantool/release/<version number>/...`. 

2) Gpgkey also has changed location from 'https://download.tarantool.org/tarantool/release/2.7/gpgkey' to `https://download.tarantool.org/tarantool/release/series-2/gpgkey` and `https://download.tarantool.org/tarantool/pre-release/series-2/gpgkey`.

3) For CentOs/Fedora (at the current moment only CentOs), we also should change in instructions on how we create `/etc/yum.repos.d/tarantool_<number>.repo`, because we support now not only x86_64 architecture but also aarch64.

I suggest adding an additional instruction field to set arch:
`ARCH=$(uname -m)`

And then fix creating `/etc/yum.repos.d/tarantool_<number>.repo`

```
rm -f /etc/yum.repos.d/*tarantool*.repo
tee /etc/yum.repos.d/tarantool_<number>.repo<<EOF
[tarantool_<number>]
name=EnterpriseLinux-$release - Tarantool
baseurl=https://download.tarantool.org/tarantool/pre-release/series-2/el/$release/$ARCH/
gpgkey=https://download.tarantool.org/tarantool/pre-release/series-2/gpgkey
repo_gpgcheck=1
gpgcheck=0
enabled=1

[tarantool_<number>]
name=EnterpriseLinux-$release - Tarantool Sources
baseurl=https://download.tarantool.org/tarantool/pre-release/series-2/el/$release/SRPMS
gpgkey=https://download.tarantool.org/tarantool/pre-release/series-2/gpgkey
repo_gpgcheck=1
gpgcheck=0
EOF

```

Please, reach me in case of badly described moments.

**Comment by artembo** [comment]
Resolved in tarantool/installer.sh#5
