### ISSUE TITLE
Document lower bound of memtx_memory config & fix doc examples

### ISSUE THREAD

**Issue by Korablev77** [tarantool/doc#2313]
**Product:** Tarantool
**Root document:** https://www.tarantool.io/en/doc/latest/reference/configuration/#initialization-file
**SME:** @
**Peer reviewer:** @

# Details

`memtx_memory` value can't be lower than 32 mb (33554432 bytes). However examples in docs somewhere contain lower value. For example: https://www.tarantool.io/en/doc/latest/reference/configuration/#initialization-file

Related to https://github.com/tarantool/doc/issues/2299

**Comment by patiencedaur** [comment]
https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_api/modules/cartridge.argparse/#parse
This description contains an invalid value of memtx_memory
However, it looks like nothing changes whether you run this command with a valid or invalid `--memtx-memory` flag value (33554436 or 100 – no difference). Probably there is a typo?

**Comment by patiencedaur** [comment]
Closed via https://github.com/tarantool/doc/pull/3015 and https://github.com/tarantool/cartridge/pull/1867.
