### ISSUE TITLE
[2pt] Wrong end of tuple parameter value

### ISSUE THREAD

**Issue by msiomkin** [tarantool/doc#2325]
## Info
Product: Tarantool
Root document: https://www.tarantool.io/en/doc/latest/tutorials/c_tutorial/#f-c-tutorial-read
SME: @
Peer reviewer: @

## What's wrong?

The following code is incorrect:

```c
  char tuple_buf[1024];      /* where the raw MsgPack tuple will be stored */
  ...
  mp_encode_array(tuple_buf, 0); /* clear */
  box_tuple_format_t *fmt = box_tuple_format_default();
  box_tuple_t *tuple = box_tuple_new(fmt, tuple_buf, tuple_buf+512);
```

The end of tuple parameter value passed to `box_tuple_new` is wrong. And it will surely trigger the assertion `tuple == tuple_end` in the **debug** version of Tarantool:

```c
static inline void
mp_tuple_assert(const char *tuple, const char *tuple_end)
{
	assert(mp_typeof(*tuple) == MP_ARRAY);
#ifndef NDEBUG
	mp_next(&tuple);
#endif
	assert(tuple == tuple_end);
	(void) tuple;
	(void) tuple_end;
}
```

A fix could be the following:

```c
  const char *box_tuple_end = mp_encode_array(tuple_buf, 0);
  box_tuple_format_t *fmt = box_tuple_format_default();
  box_tuple_t *tuple = box_tuple_new(fmt, tuple_buf, box_tuple_end);
```

But we don't need all this stuff. The tuple value is not used. It's overwritten by the subsequent call of `box_index_get`. The example must be much simpler. Just initialize the parameter variable to NULL:

```c
  box_tuple_t *tuple = NULL;
```

**Comment by NickVolynkin** [comment]
@msiomkin we make an assertion on the next line:
```c
assert(tuple != NULL);
```
Setting *tuple to NULL will fail it, right? Should we also remove that line?

**Comment by msiomkin** [comment]
Yes, you are right, this line should be removed.
