### ISSUE TITLE
Updates for C API

### ISSUE THREAD

**Issue by bigbes** [tarantool/doc#235]
Documentation should be copied from `tarantool/module.h` header

For 1.7+:
* `say_verbose` - say module
* `struct fiber_attr`, `fiber_attr_new`/`fiber_attr_delete`, `fiber_attr_setstacksize`/`fiber_attr_getstacksize`, `fiber_self`, `fiber_new_ex` - fiber module
* `coio_close` - coio module
* `luaT_error`, `luaT_cpcall`, `luaT_state` - lua/utils module
* `luaT_pushtuple`, `luaT_istuple` - lua/utils module
* `enum field_type`, `typedef struct key_def box_key_def_t`, `box_key_def_new`, `box_key_def`, `box_key_def_new`/`box_key_def_delete` - box_tuple module
* `box_tuple_format_new`, `box_tuple_format_ref`/`box_tuple_format_unref` - box_tuple module
* `BOX_TRUNCATE_ID` - schema module
* `box_truncate` - box module
* `iterator_direction`, `box_index_key_def` - box_index module
* `box_error_code` - add new error codes - error module

For 1.8+:
* `BOX_TRIGGER_ID` - schema module

**Comment by lenkis** [comment]
(1) Comments for `box_key_def_new()` in `module.h` do not match the implementation: `key_def` is the result, not an argument

```
/**
 * Create key definition with key fields with passed typed on passed positions.
 * May be used for tuple format creation and/or tuple comparation.
 *
 * \param key_def key definition to create
 * \param fields array with key field identifiers
 * \param types array with key field types (see enum field_type)
 * \param part_count the number of key fields
 */
box_key_def_t *
box_key_def_new(uint32_t *fields, uint32_t *types, uint32_t part_count);
```

OK to update?

(2) I found (and documented) some more box_tuple functions in `module.h`, which were not mentioned in the task summary above: `box_tuple_compare()`, `box_tuple_compare_with_key()`

(3) Typo in BOX_TRUNCATE_ID comment in `module.h`:

```
	/** Space if of _truncate. */
	BOX_TRUNCATE_ID = 330,
```

OK to fix "if --> id"?

**Comment by lenkis** [comment]
Committed to branch gh-235-capi-update for review

**Comment by lenkis** [comment]
@rtsisyk pls take over: review branch 'gh-235-capi-update for review' & reply to 3 Qs above

**Comment by rtsisyk** [comment]
> (1) Comments for box_key_def_new() in module.h do not match the implementation: key_def is the result, not an argument
>
>/**
> * Create key definition with key fields with passed typed on passed positions.
> * May be used for tuple format creation and/or tuple comparation.
> *
> * \param key_def key definition to create
> * \param fields array with key field identifiers
> * \param types array with key field types (see enum field_type)
> * \param part_count the number of key fields
> */
> box_key_def_t *
> box_key_def_new(uint32_t *fields, uint32_t *types, uint32_t part_count);
> 
> OK to update?

OK, I'll push a fix.

**Comment by rtsisyk** [comment]
> (2) I found (and documented) some more box_tuple functions in module.h, which were not mentioned > in the task summary above: box_tuple_compare(), box_tuple_compare_with_key()

Yes, please add them too.

**Comment by rtsisyk** [comment]
> (3) Typo in BOX_TRUNCATE_ID comment in module.h:
>
>	/** Space if of _truncate. */
>	BOX_TRUNCATE_ID = 330,
>
> OK to fix "if --> id"?

OK, I'll push a fix.

**Comment by rtsisyk** [comment]
1.7.4-299-g987e8cfde
