### ISSUE TITLE
Document iconv module

### ISSUE THREAD

**Issue by kostja** [tarantool/doc#236]
Document iconv module @GeorgyKirichenko please add details.

**Comment by GeorgyKirichenko** [comment]
Tarantool iconv module
The  iconv module contains a function to convert a sequence of characters in one character encoding to a sequence of characters in another character encoding.
iconv module consists of a function 'convert' and a table 'encodings'.
Function 'convert(TO_ENCODING, FROM_ENCODING)' creates a function object to convert some string from encodinf FROM_ENCODING to TO_ENCODING where FROM_ENCODING and TO_ENCODING are symbolic encoding names (ex. 'UTF-8', 'UTF-16BE', 'WINDOWS1251'). Call this created function with a some string to convert it:
```
iconv = require'iconv'
conv1 = iconv.convert('UTF-16', 'UTF8')
conv2 = iconv.convert('UTF-8', 'UTF-16')
-- convert string from UTF-8 to UTF-16BE and backward
print(conv2(conv1('some string')))

-- do not create separate convert functions
print(iconv.convert('UTF-8', 'UTF-16')(iconv.convert('UTF-16', 'UTF-8')('some string')))
```
Created convert function is reusable.
For unsupported encodings an exception will be raised, for invalid or incomplete string an exception will be raised to.

encodings module table contains all supported encodings
