### ISSUE TITLE
[1pt] Fix a link

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#2387]
https://www.tarantool.io/ru/doc/1.10/reference/reference_lua/box_space/

<img width="785" alt="изображение" src="https://user-images.githubusercontent.com/8015154/138413396-2f57b467-8bdd-4457-a1f7-ae51fb29a111.png">

**Comment by arctic-dreamer** [comment]
Closed via https://github.com/tarantool/doc/pull/2541
