### ISSUE TITLE
Drop error_marshaling_enabled session setting

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#2415]
**Product:** Tarantool
**Since:** 2.10.0-beta1-46-g0cdf5f9be89c
**Root document:**  pages where the ``error_marshaling_enabled`` setting is mentioned:
- https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_error/new/
- https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_space/_session_settings/
- https://www.tarantool.io/en/doc/latest/reference/reference_sql/sql_statements_and_clauses/#set

**SME:** @ locker

# Details

box.session.setting.error_marshaling_enabled was used to enable encoding
errors returned by CALL/EVAL in the extended format (as the MP_ERROR
MsgPack extension). Now, the feature is enabled automatically if the 
connector supports it (sets IPROTO_FEATURE_ERROR_EXTENSION in IPROTO_ID
features).

Requested by @locker in https://github.com/tarantool/tarantool/commit/0cdf5f9be89c5ec71a34968dfa84b4485bf20d14

Related to https://github.com/tarantool/doc/issues/2416

**Comment by Totktonada** [comment]
I'll also highlight that #1676 is still actual.

**Comment by veod32** [comment]
@Totktonada A few questions to estimate the issue:

1. 
>Now, the feature is enabled automatically if the connector supports it
What happens if the connector doesn't support it? Old behavior and usage of ``box.session.setting.error_marshaling_enabled`` is still there and possible in such cases?

2. Since which Tarantool version we have this new behavior?

**Comment by locker** [comment]
> What happens if the connector doesn't support it?

Errors returned from CALL/EVAL (`return box.error(...)`) will be converted to strings, as before.

> Old behavior and usage of `box.session.setting.error_marshaling_enabled` is still there and possible in such cases?

It was dropped. No such setting anymore.

> 2. Since which Tarantool version do we have this new behavior?

```
$ git describe 0cdf5f9be89c5ec71a34968dfa84b4485bf20d14
2.10.0-beta1-46-g0cdf5f9be89c
```
