### ISSUE TITLE
instr() is replaced with position()

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#2424]
Name and order of the arguments has changed for a better ANSI
compatibility:
Before: instr(haystack, needle).
After: position(needle, haystack).

Type checking became more strict: before it was 
possible to call the function with INTEGER arguments
or with arguments of different types. Now both arguments
must have the same type and be either text or binary
strings.

Before the patch collations were not taken into
consideration during the search. Now it is fixed, and 
both implicit (column) collations and explicit
(using COLLATE expression) are used. Single collation which
would be used in function is determined using ANSI
“Type combination” rules.

Requested by @SudoBobo in https://github.com/tarantool/tarantool/commit/896f396cb5bde898e7c5f1e1c712322e3ee1531e

**Comment by Totktonada** [comment]
It is from 2.2.2 / 2.2.1, but I found that the issue was never raised expcilitly. I see that the `POSITION()` function was added into the documentation in 67b32b2fbd695a34223c0ed5a81690ef1852cb65. Filed just in case: someone may want to verify that no details are missed.

Feel free to just close.

**Comment by pgulutzan** [comment]
@Totktonada: The POSITION() documentation
https://www.tarantool.io/en/doc/latest/reference/reference_sql/sql_statements_and_clauses/#position
is correct and there's nothing about instr, but it's superseded in version 2.10, we no longer support POSITION() for varbinary. For what we're going to change regarding this function, see the pull request issue #2350. I suggest that this should be closed with no action.

**Comment by Totktonada** [comment]
Okay, thanks!
