### ISSUE TITLE
vinyl_threads -> vinyl_write_threads

### ISSUE THREAD

**Issue by racktear** [tarantool/doc#246]
vinyl_threads option to box.cfg{} is present in readme, but no longer works for me:

```sh
tarantool> box.cfg {vinyl_threads_read = 2;}
---
- error: 'Incorrect value for option ''vinyl_threads_read'': unexpected option'
...
```

**Comment by lenkis** [comment]
replaced with 2 separate options: vinyl_read_threads + vinyl_write_threads
