### ISSUE TITLE
WARNING: dvisvgm command 'dvisvgm' cannot be run

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#2471]
# What needs to be done

In `make json` logs:

```
WARNING: dvisvgm command 'dvisvgm' cannot be run (needed for math display), check the imgmath_dvisvgm setting
```

Looks like we need an extra dependency in our builder image and a few lines in conf.py

See https://www.sphinx-doc.org/en/master/usage/extensions/math.html

**Reviewer:** @NickVolynkin 

# Definition of done

- [x] no such warning in the build logs
- [ ] imgmath formulas look fine in the docs

**Comment by patiencedaur** [comment]
Closed by https://github.com/tarantool/doc-builder/pull/16.
