### ISSUE TITLE
Bugfixes from @Khatskevich

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#249]
Please verify and integrate to 1.7:
- [ ] https://gist.github.com/Khatskevich/682d311ba610ca222cd3adff671c1a02
- [ ] see these notes:
![doc-bug-report-2](https://user-images.githubusercontent.com/16703423/28063169-f2869c1c-6638-11e7-869a-7711e72ec9c1.jpg)

**Comment by lenkis** [comment]
@Khatskevich please clarify the points from hand-written notes

**Comment by Khatskevich** [comment]
There are 3 issues in hand-written notes, and all of them are related to https://tarantool.org/en/doc/1.8/book/box/data_model.html

1
At the beginning you can find phrase `If you tried to create a database as suggested in our “Getting started” exercises, then your test database now looks like this:` and after this you can see the picture with where space contains indexes 'primary' and 'secondary'.
But, as I saw in “Getting started” only the 'primary' index is created.
2
Next look at the table 'Lua vs MsgPack'. Example of MsgPack 'map' looks like 'table: 0x410f8b10', but I expect to find there something like "{'a'='b','c'=d'}"
3
in table "Indexed field types" is written that 'array' index field type is for msgpack type ''arrays of integers", but if I am not mistaking it is suitable for both double and integer types (like number) (but you better check or ask @alyapunov for more info)

**Comment by Khatskevich** [comment]
A also wanted to say here:
https://gist.github.com/Khatskevich/682d311ba610ca222cd3adff671c1a02
that triggers are persistent by now.
