### ISSUE TITLE
[1pt] формула логарифма отображается некорректно https://www.tarantool.io/ru/doc/latest/book/box/engines/vinyl/

### ISSUE THREAD

**Issue by Satbek** [tarantool/doc#2518]
**Product:** Tarantool
**Root document:** https://www.tarantool.io/ru/doc/latest/book/box/engines/vinyl/

## Details

<img width="769" alt="Screenshot 2021-12-23 at 13 46 52" src="https://user-images.githubusercontent.com/26044679/147229579-44ca1f0e-244a-4c39-850b-a7cabbef34f5.png">

**Comment by patiencedaur** [comment]
Resolved via https://github.com/tarantool/doc/pull/2967
