### ISSUE TITLE
slab_size limitation is wrong

### ISSUE THREAD

**Issue by kostja** [tarantool/doc#254]
Slab size
The maximal size of an allocatable memory unit (slab) is equal to one quarter of memtx_max_tuple_size (by default, approximately 262,000 bytes). To see memory usage statistics broken down by slab size, use box.slab.stats().

Here:
https://tarantool.org/doc/1.7/book/box/limitations.html

It is actually 4*max_tuple_size, not 1/4 * max_tuple_size. but it's not a limitation really, it's an implementation detail. The limitation is max tuple size.

**Comment by pgulutzan** [comment]
Since it's not really a limitation and is internal, it's removed from the manual.
