### ISSUE TITLE
[0pt] Automate changelog review tracking

### ISSUE THREAD

**Issue by patiencedaur** [tarantool/doc#2544]
**Epic: [Release notes](https://github.com/tarantool/doc/issues/2570)**

Helps with https://github.com/tarantool/tarantool/issues/6430.

# Problem

Individual changelog lines are kept in a tarantool/tarantool [directory](https://github.com/tarantool/tarantool/tree/master/changelogs/unreleased), which is constantly updated.
Release notes for every release are compiled from these individual changelogs by a script.

The changelog directory is updated each time a new feature is ready.

We need to proofread each changelog file and keep track of their status.
* There are many files in the dir and three branches to keep track of: 1.10, 2.8., and master. That is, three "instances" of the folder.
* The changelogs are updated without our involvement.

Therefore, it would be nice to automate the process.

# Proposal

Create a script that runs every two weeks and does the following:

* Collects new file names/links from the changelogs/unreleased folder for 1.10, 2.8, and master branches.
* Inserts them in a table:
  - File name
  - Release versions the changelog will be included into
  - Review status ("no" by default, will be updated manually by doc team)
  - Corresponding dev epic (empty by default, will be updated manually by doc team)
  - Corresponding doc issue (empty by default, will be updated manually by doc team)
* (Optional) Notifies about running.

**Reviewer:** @ patiencedaur

**Comment by Totktonada** [comment]
Raw idea: run `git log --stat --since <...> changelogs/unreleased` in a cron job to file tarantool/doc issue every two week.

**Comment by patiencedaur** [comment]
Ideas:
- Record the date of every run.
- Upload the table to Notion.
- Add new lines to the table, not re-record everything.

**Comment by patiencedaur** [comment]
If the content of changelog item changes, mark such an item with `!` or something.

**Comment by patiencedaur** [comment]
`git lg --follow --since="2 weeks ago" -- .`
эта команда показывает коммиты, которые внесли изменения в папку за 2 недели
таких коммитов сейчас 2 штуки

потом название каждого коммита можно загрузить сюда:
`git show --name-only --oneline dacbf7 -- .`
покажет название коммита и название файла

`git lg`:
`git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%C(bold blue)<%an>%Creset' --abbrev-commit"`
