### ISSUE TITLE
[2pt] List of TT commands and their short descriptions

### ISSUE THREAD

**Issue by patiencedaur** [tarantool/doc#2555]
**Epic: [Document TT CLI](https://github.com/tarantool/doc/issues/2553)**
Related dev page: https://github.com/tarantool/tt/issues/8

Product: Tarantool CLI
Since: 2.10
Audience/target: dev, admin
Root document: TBA
SME: @ Totktonada

Like in [Cartridge CLI](https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_cli/).

**Comment by p7nov** [comment]
Fixed by https://github.com/tarantool/doc/pull/2973
