### ISSUE TITLE
[3pt] TT CLI path config section

### ISSUE THREAD

**Issue by patiencedaur** [tarantool/doc#2566]
**Epic: [Document TT CLI](https://github.com/tarantool/doc/issues/2553)**

Product: Tarantool CLI
Since: 2.10
Audience/target: dev, admin
Root document: TBA
SME: @ Totktonada

### Details

We might need pages describing config options similar to [Cartridge CLI](https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_cli):
- [ ] Instance path configuration
- [ ] Global flags

**Comment by p7nov** [comment]
Fixed by https://github.com/tarantool/doc/pull/2973
