### ISSUE TITLE
[3pt] Parsing human-readable date and time strings

### ISSUE THREAD

**Issue by patiencedaur** [tarantool/doc#2576]
**Epic: [Datetime remaining issues](https://github.com/tarantool/doc/issues/2574)**

**Product:** Tarantool
**Since:** 2.8
**Root document:** https://www.tarantool.io/en/doc/latest/reference/reference_lua/
**SME:** @ tsafin

# Input from #2792

We support relaxed ISO-8601/RFC339 date formats. Consider RFC-3339 as a
profile of a strict ISO-8601, not major extension. We use c-dt, which is
ISO-8601 conformant in such way that we accept superset of ISO-8601
strings, with a few reasonable extensions.

Few examples for further clarification:

## Years

| Basic | Extended | ... | ISO-8601? |
|-------|-----------|-----|-----------|
| `20121224` | `2012-12-24` | Calendar date | yes |
| `2012359` | `2012-359` | Ordinal date | yes |
| `2012W521` | `2012-W52-1` | Week date | yes |
| `2012Q485` | `2012-Q4-85` | Quarter date |  |

Modified [`c-dt` parser supports extended years](tarantool/c-dt#1)
values, which are outside of standard [0001 .. 9999] range

| Tarantool extended values |   |
|------------------------------|---|
| `0000-01-01` | `-0001-12-31` |
| `5879611-07-11` | `-5879610-06-22` |

## Time

| Basic | Extended |
|-------|-----------|
| `T12` | N/A |
| `T1230` | `T12:30` |
| `T123045` | `T12:30:45` |
| `T123045.123456789` | `T12:30:45.123456789` |
| `T123045,123456789` | `T12:30:45,123456789` |

The time designator `T` may be omitted. This is exactly how RFC3339 is
## Timezone

We do not (yet) support names for standard time-zones (like `MSK`, or
`EST`, or `America/New_York` or whatever) we only support numeric offsets
at the moment.

In a form

| Basic | Extended |
|-------|-----------|
| `Z` | N/A |
| `+hh` | N/A |
| `-hhmm` | `-hh:mm` |
| `GMT+h` |  |
| `GMT-hhmm` |  |
| `GMT+h:mm | `GMT+hh:mm` |
| `UTC-h:mm` | `UTC-hh:mm` |

And relaxed ISO-8601 format is compositions of all relaxed subformats (i.e.
date, time, and timezone) putting them together as:

> {relaxed-date} ( `[Tt ]` {relaxed-time} ( `' '` {lenient-time-zone})? )?

NO_TEST=documentaton update
Closes #6731
Requested by @tsafin in https://github.com/tarantool/tarantool/commit/9bc059bb3fd9c7b3ce31ee062224a1f16cf6b5c3.

# Input from #2864: tz attribute

Now `tz` attribute is properly handled in datetime value
constructors or `:set{}` method modifiers.

```
tarantool> T = date.new{year = 1980, tz = 'MSK'}
---
...

tarantool> T.tzoffset
---
- 180
...

tarantool> T.tz
---
- MSK
...
tarantool> T = date.new{year = 1980, tzoffset = 180}
---
...

tarantool> T.tzindex
---
- 0
...

tarantool> T.tz
---
-
...

tarantool> T.tzoffset
---
- 180
...

tarantool> T:set{tz = 'MSK'}
---
...

tarantool> T.tz
---
- MSK
...

```
Requested by @tsafin in https://github.com/tarantool/tarantool/commit/7036b55a622faaf7a8d67575ddb38ac09455fb0f.

---

# Input from #2872: datetime :set{} with  tzoffset

The constructor `date.new()` and modifier `date:set()` should always produce
same result for all attribute combinations. Fixed the problem for
`timestamp` with `tzoffset`.

```
tarantool> date.new{tzoffset = '+0800', timestamp = 1630359071}
---
- 2021-08-30T21:31:11+0800
...

tarantool> date.new():set{tzoffset = '+0800', timestamp = 1630359071}
---
- 2021-08-30T21:31:11+0800
...
```
Requested by @tsafin in https://github.com/tarantool/tarantool/commit/d56840d73a5c4696e1058a81ef45529a26afa8e5.

This document might be useful:
https://hackmd.io/@Mons/S1Vfc_axK

Dev. issue: https://github.com/tarantool/tarantool/issues/6751. Note that Olson timebase support is not to be implemented in Q1.

**Comment by tsafin** [comment]
Please use this wiki I created as a basis for external documentation - https://github.com/tarantool/tarantool/wiki/Datetime-Internals
