### ISSUE TITLE
[Epic] Raft: Pre-Vote mechanism

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#2592]
Dev board ref.: https://github.com/tarantool/roadmap-internal/issues/92
PM ref.: https://www.notion.so/tarantool/RAFT-95ae32cc025f465e8f3d25177efcd291

**SME:**  @ sergepetrenko 

# Tasks

- [x] https://github.com/tarantool/doc/issues/2593
- [x] https://github.com/tarantool/doc/issues/2837

# Details

To document the implementation of the new Pre-Vote mechanism in Tarantool automated leader election.

**Comment by patiencedaur** [comment]
Here is a source—a conversation on Raft between @ rosik and @ sergepetrenko: https://hackmd.io/@rosik/2021-08-25-raft-interview
