### ISSUE TITLE
[Epic] Raft: document quorum read (aka linearizable read)

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#2595]
Dev board ref.: https://github.com/tarantool/roadmap-internal/issues/94
PM ref.: https://www.notion.so/tarantool/227f4d71ea004da5b9d33b6915536c29

**SME:** @ sergos , @ sergepetrenko 

# Tasks

- [x] https://github.com/tarantool/doc/issues/2607

# Details

TBD

**Comment by patiencedaur** [comment]
Here is a source—a conversation on Raft between @ rosik and @ sergepetrenko: https://hackmd.io/@rosik/2021-08-25-raft-interview

**Comment by andreyaksenov** [comment]
https://www.tarantool.io/en/doc/latest/concepts/atomic/transaction_model/#linearizable-read
