### ISSUE TITLE
replication: the truncate method called from within a transaction

### ISSUE THREAD

**Issue by arctic-dreamer** [tarantool/doc#2599]
**Since:** 2.10.0-beta2
**Root document:** https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_space/truncate/
**SME:** @ sergepetrenko 
**dev issue**: https://github.com/tarantool/tarantool/issues/6123

# Details

https://github.com/tarantool/tarantool/commit/8be03697f8a1b15098c426bbde7ac8a2b21a29c7

The truncate method could be called from within a transaction. The flag
of GROUP_LOCAL was set in truncate method after statement row had been
being checked on the GROUP_LOCAL. Accordingly, after a local transaction
NOP row was not appended.

**Comment by patiencedaur** [comment]
No need to change anything in the doc. This was a bug, and the bug was fixed. The documentation describes the correct behavior of `space_object:truncate()`. Closing.

**Comment by Totktonada** [comment]
I think that a note like

> Note: This method should not be called within a transaction before tarantool 2.10.0. See https://github.com/tarantool/tarantool/issues/6123 for details.

Would be better resolution of this issue.
