### ISSUE TITLE
Document package manager

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/doc#260]
The new LuaRocks-based package manager has finally landed into 1.7!

Please document this new feature and update all related sections of user/administration guide. See https://github.com/tarantool/tarantool/commit/9e7c421758af156d19a66cebf713e24b42d8654b for the short overview of new commands added to `tarantooctl`.  

This is alpha-quality feature, please feel free to open tickets in tarantool/tarantool for any problems you found.

https://github.com/tarantool/tarantool/issues/2067

**Comment by lenkis** [comment]
done
