### ISSUE TITLE
[5pt] Synchronous replication: document quorum read (aka linearizable read)

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#2607]
**Epic:** https://github.com/tarantool/doc/issues/2595

**Product:** Tarantool
**Since:** 2.10.0
**Dev issue:** 

- https://github.com/tarantool/tarantool/issues/6707
- https://github.com/tarantool/tarantool/issues/6592

**Root document:** https://www.tarantool.io/en/doc/latest/book/replication/repl_sync/ (TBD)
**SME:** @ sergepetrenko 

# Details

[input from dev issue]
As we have a synchronous write for the data, we need the opposite for read.
Currently, we have no mechanism to prevent a client from reading data from a node that is not up to date with quorum write. The trivial solution to read from master can fail also, since master can be elect, still not up to date from limbo - [#6689](https://github.com/tarantool/tarantool/issues/6689) 

We need to elaborate the interface and the machinery behind it to enable the subject.

**TDB**  details of the implementation when it's done

Addition info on the subject: https://pierrezemb.fr/posts/diving-into-etcd-linearizable/

# ToDo

- Write a new section describing the details of the quorum read. The place in the documentation is TBD.

**Comment by veod32** [comment]
Development is still WIP: 
- Estimated date of dev complition is July 8. 
- Estimated doc issue start is July 11.

**Comment by andreyaksenov** [comment]
https://www.tarantool.io/en/doc/latest/concepts/atomic/transaction_model/#linearizable-read
