### ISSUE TITLE
[3pt] vshard: supporting the 'raw args' feature to avoid args decoding on routers

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#2609]
**Epic:** https://github.com/tarantool/doc/issues/2588

**Product:** Tarantool, vshard module
**Since:** 2.10.0 of Tarantool
**Dev issue:** https://github.com/tarantool/vshard/issues/312
**Root document:** https://www.tarantool.io/en/doc/latest/reference/reference_rock/vshard/vshard_router/#router-api-map-callrw
**SME:** @ Gerold103

# Details

Prerequisite: https://github.com/tarantool/doc/issues/2015

**[input from dev issue]** https://github.com/tarantool/vshard/issues/312
The newest Tarantool version has a new function setting takes_raw_args. Instance can create such function in _func and it will take arguments as a raw MessagePack buffer. The function then can decode some first arguments and leave the others not decoded. For instance, to forward them further to another instance.

Also netbox now supports return_raw option - works the same. Result of the remote call is a raw MessagePack buffer. Not decoded into Lua values.

These options together should help to reduce pressure on the router when it is used as a proxy. Router would need to offer a function like vshard.router.callraw(). It would take a MessagePack buffer with the same arguments encoded as vshard.router.call() and return result also as a MessagePack buffer (using return_raw netbox option when talks to the storage).

In order to use it the user would need to register it in _func with takes_raw_args and call it from clients. Router can't do that itself, because it is not supposed to depend on any local spaces.

Details of the implementation below:

## Input from #2707

`vshard.router.map_callrw()` supports `return_raw` option (in the
version of Tarantool which have it at all).

When there was an error, the result is the same as always:
`nil, err, err_uuid`. No changes.

When the call was a success, the result is a map of the format
`{[replicaset_uuid] = msgpack.object}`. The `msgpack.object` here
stores a MessagePack array with the results returned from the
storage's map-function.

The usecase is the same as for when bare netbox is used - to avoid
decoding of the results into Lua land. Helpful when the router is
used as a proxy and the results received from the storage are big.

Example:
```Lua
local res = vshard.router.map_callrw('my_func', args, {..., return_raw = true})

for replicaset_uuid, msgpack_value in pairs(res) do
    log.info('Replicaset %s returned %s', replicaset_uuid,
             msgpack_value:decode())
end
```
However this is just an example. Normally you don't need `return_raw` if you are
calling `:decode()` anyway.

The family of `vshard.router.call` functions also supports `return_raw`, but
their behaviour is the same as with bare netbox - the entire result is just an
`msgpack.object`. The same as if direct netbox call would be done. Nothing to
document here, I think.
Requested by @Gerold103 in https://github.com/tarantool/vshard/commit/91a362360cca1c5237d393ef6c64fa38c63ca18f.

# ToDo

- Describe implementation of the ``return_raw`` option support in vshard.  Perhaps, cross-references to the description of the msgpack.object() can be also helpful.

**Comment by patiencedaur** [comment]
TarantoolBot created a duplicate issue for this: https://github.com/tarantool/doc/issues/2707
