### ISSUE TITLE
Update RU documentation

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#261]
Please upvote this ticket if you need a complete Tarantool manual in Russian again.

**Comment by nucleusv** [comment]
+1

**Comment by lenkis** [comment]
@kostja we're getting upvotes. can we increase priority for this ticket?

**Comment by kostja** [comment]
No.

**Comment by Onvember** [comment]
We are currently updating the documentation in Russian, so there is no need to upvote this issue :)
