### ISSUE TITLE
[Epic] Enabling debug hooks on traces in LuaJIT by default (research)

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#2612]
**Total:** 2pt

Dev board ref.: https://github.com/tarantool/roadmap-internal/issues/105
PM ref.: https://www.notion.so/tarantool/LuaJIT-Tarantool-build-with-debug-hook-01662fab80e94b09a36b1cac0cb3dcbc

**SME:** @ igormunkin

# Tasks

- [ ] TBD

# Details

If the dev research outcome is positive and this functionality is to be implemented, we need to mention it in our documentation or on the site (place -- TBD)

Sync-up with @ igormunkin on March 1, 2022 to figure out the dev research outcome.

**Comment by patiencedaur** [comment]
This is a research task. Nothing is to be added to the doc. Closing.
