### ISSUE TITLE
[2pt] Mention streams autocompletion somewhere

### ISSUE THREAD

**Issue by patiencedaur** [tarantool/doc#2625]
**Epic: [iproto streams follow-ups](https://github.com/tarantool/doc/issues/2589)**

**Product:** Tarantool
**Since:** 2.10.0
**Audience/target:** dev
**Root document:** changelog (most probably)
**SME:** @ EvgenyMekhanik

# Details

Since 2.10.0, streams can be autocompleted in the command line just like connection objects, using Tab.

See how autocompletion is described in [1.7 release notes](https://www.tarantool.io/en/doc/latest/release/1.7/).

**Comment by p7nov** [comment]
Already mentioned in [2.10 release notes](https://www.tarantool.io/en/doc/latest/release/2.10.0/#lua).
