### ISSUE TITLE
[5pt] Constraints

### ISSUE THREAD

**Issue by arctic-dreamer** [tarantool/doc#2627]
**Related dev. issue(s):** https://github.com/tarantool/tarantool/issues/6436

**Product:** Tarantool
**Since:** 2.10.0
**SME:** @ alyapunov 

# Details

https://docs.google.com/document/d/1EtqfFSIMi6fDqj2y-9WgpunkHsszU65p6LfNly5E9Ag/

Space constraints are needed to ensure that tuples in a space satisfy the specified conditions.  Normal constraints define a function that defines the correctness of a tuple. Foreign keys describe the relationship between tables by requiring an external tuple in another spacer with specific fields.

The usual constraints are set for a tuple field or the entire tuple and refer by name to a function from `space _func`. To be safe for now, it's made to be a Lua function, with the body text right in the `_func` space.

Constraints for fields work much faster, constraints for tuples are much more versatile.

# Definition of done

- [ ] describe how constraints for fields work
- [ ] describe how constraints for tuples work

**Comment by pgulutzan** [comment]
@arctic-dreamer: Why is there an sql label? Tarantool issue 6436 appears to be a Lua issue.

**Comment by Totktonada** [comment]
I see nothing about constraints in the API description: https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_schema/space_create/. It is nice to have guides, but an API reference is more important.

**Comment by p7nov** [comment]
> I see nothing about constraints in the API description: https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_schema/space_create/. It is nice to have guides, but an API reference is more important.

You're right, the reference somehow slipped out of this task's scope. And the same for foreign keys (#2628). Thanks for noting this.
However, I think a new issue will be easier to plan and track. I'll file it and link to this one.
