### ISSUE TITLE
[Epic] Move all tarantool modules to the "modules" repositories

### ISSUE THREAD

**Issue by arctic-dreamer** [tarantool/doc#2631]
**Related dev. issue(s):** https://github.com/tarantool/roadmap-internal/issues/75

**SME:** @ LeonidVas 

# Tasks

- [ ] https://github.com/tarantool/tarantool.io/issues/1154

# Details

Input from dev issue:

Earlier, when creating repositories for a new tarantool release, all module packages (last versions) copy-paste from old (for example from `release/2.7/ubuntu/pool/bionic`) to the new one (`release/2.8/ubuntu/pool/bionic`). Now we decided to deprecate this practice and move all modules to separate repositories (release/modules).
As part of this task, it is necessary to do the following:
- update the installation instructions on the website

**Comment by patiencedaur** [comment]
This is not a docs epic but a small task for the DevX team. Closing.
