### ISSUE TITLE
site http://localhost:8081/admin/tutorial/ru/podnimem-http-api-2-minuty

### ISSUE THREAD

**Issue by artemlazarev** [tarantool/doc#2653]
# What needs to be done

**Reviewer:** @ documentarian name

# Definition of done

At the page http://localhost:8081/admin/tutorial/ru/podnimem-http-api-2-minuty
- [ ] Add port information, at the example is 8081, in a more understandable way.
 At this moment tutorial contains url  `http://artpjcvnmwctc4qppejgf57.try.tarantool.io.` that point to the `80` port. Thats not correct.
# Planning checklist

- [ ] Pick a label
- [ ] Estimate complexity in storypoints in the title
- [ ] Add to **Documentation** board → **Backlog**

> Note: issue templates are in beta. Give your feedback in #1869.

**Comment by patiencedaur** [comment]
@artur-barsegyan, just a reminder that we discussed this issue.
