### ISSUE TITLE
Getting Started: Unclear parameter in curl request

### ISSUE THREAD

**Issue by artemlazarev** [tarantool/doc#2654]
Root document: https://www.tarantool.io/ru/doc/latest/getting_started/getting_started_imcp/#writing-data-5-minutes

At the 3 `curl` request at the page `https://www.tarantool.io/ru/doc/latest/getting_started/getting_started_imcp/#writing-data-5-minutes` unclear the parameter for video id.
May bee all of the `curl ` request on page  to rewrite.

**Comment by patiencedaur** [comment]
@artur-barsegyan, please take a look at this.

**Comment by patiencedaur** [comment]
Fixed in #2666
