### ISSUE TITLE
Getting Started: Space-Explorer tab mentioned but missing in the UI

### ISSUE THREAD

**Issue by artemlazarev** [tarantool/doc#2655]
Root document: https://www.tarantool.io/ru/doc/latest/getting_started/getting_started_imcp/#looking-at-the-data-1-minute

## missing  "Space-Explorer" at local instalation
At the page  `https://www.tarantool.io/ru/doc/latest/getting_started/getting_started_imcp/#looking-at-the-data-1-minute`
We must go to the "Space-Explorer" tab at the local console that located at the `localhost` but that menu item missing. 

## How to reproduce 
* install/run tarantool from latest docker image (as described in doc : `tarantool/getting-started` )
* do all as described at the documentation
* Take a look to the left menu bar at the web console

you will not spot "Space-Explorer" at he menu list

**Comment by patiencedaur** [comment]
@artur-barsegyan Please take a look at this. What's the status on the Space-Explorer tab---is it there or not?

**Comment by artur-barsegyan** [comment]
Hi! Actually, a few pictures below mention the limitations of the free version of Tarantool.

I raised the text above the pictures so that it was in view after starting to read this block. should close the question for those readers who run the tutorial locally.
