### ISSUE TITLE
Snapshot files vs checkpoint files

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#266]
Revise the manual for consistency in terms "snapshot files" vs "checkpoint files":
* snapshot files = only .snap files
* checkpoint files = generic term for any files that Tarantool uses for checkpointing (.snap, .vysnap, .run, .index, etc)

**Comment by lenkis** [comment]
@kostja pls confirm the terms usage

**Comment by kostja** [comment]
Correct.
