### ISSUE TITLE
Declare that Russian pages are not supported anymore

### ISSUE THREAD

**Issue by patiencedaur** [tarantool/doc#2662]
**Root document:** all Russian index pages:

- https://www.tarantool.io/ru/doc/
- https://www.tarantool.io/ru/doc/1.10/
- https://www.tarantool.io/ru/enterprise_doc/
- https://www.tarantool.io/ru/tdg/latest/

The doc for TDG 1.6 is not included because it's FSTEC-certified and the original is in Russian.
The doc for Tarantool 1.6 is not included because this version is deprecated (see issue).

# Details

Consider adding a nice panel on top. I think the SME on panels is @ NickVolynkin.
The panel should convey the message: The Russian doc is temporarily unsupported, and contributions are welcome.

## To do

- [x] Consult with @ Katedraw about design
- [x] Consult with @ NickVolynkin and @ kyukhin about the best place for this information
- [x] Up the diplomacy: choose a careful formula
- [x] Create and deploy
- [x] Update the note on the Russian index page:
![image](https://user-images.githubusercontent.com/40490252/153371253-0530121d-422c-44ad-bb74-f4f126f510af.png)

**Comment by NickVolynkin** [comment]
We can replace the release banner. Is it acceptable? 

<img width="1365" alt="Screenshot 2022-02-10 at 15 49 33" src="https://user-images.githubusercontent.com/8015154/153371126-4f2713b3-d3b0-49e0-bac2-f690d1706340.png">

**Comment by NickVolynkin** [comment]
As an alternative, there's this disclaimer which you can edit yourself:

![Uploading Screenshot 2022-02-10 at 15.53.30.png…]()

**Comment by patiencedaur** [comment]
The marketing department suggests:
Поддержка документации на русском языке приостановлена. Стать контрибьютором. Перейти на английскую версию

The last phrase must be bigger than the others.

**Comment by patiencedaur** [comment]
> What's the priority, should we prefer the release policy or deprecation banner?

I think the deprecation banner is more important now. The release is not new anymore, and banners are only acceptable to convey something urgent, IMO.

**Comment by patiencedaur** [comment]
The product team says it's better to remove the Russian language flag altogether and to post the update in the Contributing section.

**Comment by NickVolynkin** [comment]
> Contribute to Russian translation link_to_russian_documentation

but the link does not lead to contribution, just to the docs

**Comment by patiencedaur** [comment]
There will be two links. So the new message, approved by the marketing, is: The Russian documentation (link to Russian documentation) is temporarily unsupported. Translation contributions (link to landing issue) are welcome.

**Comment by NickVolynkin** [comment]
> Remove the Russian flag

That's unclear. Please describe the UX flow. What should be on English and Russian-language pages: a flag without choice, nothing at all?

**Comment by patiencedaur** [comment]
There will be no flag either on English or Russian pages.
However, I think there must remain a way to switch from the Russian doc to the English version. Is there a way of implementing it in the template of all Russian pages besides a banner?

**Comment by patiencedaur** [comment]
New plan: the flag remains, but the user flow changes.

Use cases:

1. The user is on the English page. The user clicks the flag to switch to Russian. A pop-up appears with a button and the following text: The Russian documentation is temporarily unsupported. Translation contributions (link to landing issue) are welcome. The button says: "Continue to the Russian documentation"

2. The user has a link to a Russian page saved in the bookmarks. They follow the link and see a pop-up with the same text. There is a checkbox saying "Don't show this again". If the user clicks "Continue to the Russian documentation", a cookie is saved so the user doesn't see the message again.

**Comment by lastoCHka42** [comment]
And what about: user is on Russian page and goes to Documentation page?

**Comment by patiencedaur** [comment]
Here's the banner design: https://www.figma.com/file/cBXXfF5xAiTSPrh9REC43g/TT_Documentation?node-id=1347%3A2872

**Comment by patiencedaur** [comment]
The task is now passed to @ filonenko-mikhail and the frontend team.

**Comment by patiencedaur** [comment]
New text: "Документация на русском языке поддерживается сообществом. _Стать контрибьютором_" (the latter two words are a link)
New link: https://github.com/tarantool/doc/discussions/2738

**Comment by patiencedaur** [comment]
https://github.com/tarantool/tarantool.io/issues/946 closed, job done.
