### ISSUE TITLE
Sort information about connectors

### ISSUE THREAD

**Issue by patiencedaur** [tarantool/doc#2667]
**Epic: [Restructure Tarantool docs, stage 3](https://github.com/tarantool/doc/issues/3175)**
**SME:** @ LeonidVas

**Root documents:**
https://www.tarantool.io/en/download/connectors
https://www.tarantool.io/en/doc/latest/book/connectors/
https://www.tarantool.io/en/doc/latest/getting_started/getting_started_connectors/

https://www.tarantool.io/en/doc/latest/book/connectors/#index-connector-php
https://www.tarantool.io/en/doc/latest/getting_started/getting_started_php/

doc/getting_started/getting_started_python.rst
doc/book/connectors/__python.rst

doc/getting_started/getting_started_go.rst
doc/book/connectors/__go.rst

...and more.

### Details

It would be great to put all the info on connectors in a single place, removing redundancies and providing cross-links.

### Definition of done

- [ ] See if there are any broken links
- [ ] See that tutorials and instruction are in How-to guides and feature descriptions are in the Dev guide (see https://github.com/tarantool/doc/issues/3175)
- [ ] Provide cross-links between the tutorials and the connector descriptions. Consider adding links to the connector downloads page, too
- [ ] Move translations if needed
- [ ] Fix broken links
- [ ] [Create redirects](https://www.notion.so/5b0e1ab45d0841a3b502cfea89829ef7) if needed

**Comment by andreyaksenov** [comment]
Documentation for connectors now lives in one place: https://www.tarantool.io/en/doc/latest/connector/ (see https://github.com/tarantool/doc/issues/3817).
