### ISSUE TITLE
Readme for C++ connector

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#271]
We need a comprehensive readme here: https://github.com/tarantool/tarantool-cpp

**Comment by lenkis** [comment]
Author's contact info:
* name: Andrey Statsenko
* email: a.statsenko@corp.mail.ru
* telegram: @andrew_statsenko

**Comment by patiencedaur** [comment]
The supported C++ connector is called `tntcxx` and is documented here: https://www.tarantool.io/en/doc/latest/book/connectors/cxx/tntcxx_api/
