### ISSUE TITLE
[2pt] Create a guideline for describing Tarantool configuration parameters

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#2723]
**Root document:** https://www.tarantool.io/en/doc/latest/contributing/docs/examples/

## ToDo

Create a guideline for describing Tarantool [configuration parameters](https://www.tarantool.io/en/doc/latest/reference/configuration/#configuration-parameters) and API function parameters (`:param:`). 

We already have templates for documenting functions, classes, methods, and data. But description of configuration parameters has its own specifics. The following info should be provided for each parameter:
- Since which Tarantool version 
- General description with all the details and examples (if needed)
- Type
- Corresponding environment variable
- Default value
- Dynamic (yes or no)
- Possible errors

**Comment by patiencedaur** [comment]
Do this next: https://github.com/tarantool/doc/issues/2722
