### ISSUE TITLE
Fix documentation layout

### ISSUE THREAD

**Issue by patiencedaur** [tarantool/doc#2742]
# What needs to be done

Implement changes to the documentation site layout.

Layout link: https://www.figma.com/file/cBXXfF5xAiTSPrh9REC43g/TT_Documentation?node-id=133%3A1586
UI kit: https://www.figma.com/file/cBXXfF5xAiTSPrh9REC43g/TT_Documentation?node-id=1486%3A6805
Documentation to the layout: https://katedraw.notion.site/cd7262968e584917b1715e314068df45

**Reviewers:** @Katedraw, @patiencedaur, @NeraverinTarantool

**Comment by usenko-timur** [comment]
https://github.com/tarantool/doc/issues/2742
