### ISSUE TITLE
Document allowed characters in instance names

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/doc#276]
https://github.com/tarantool/tarantool/issues/2552

@dedok and @vstarodub spent a lot of time trying to start a Tarantool instance which contained "-" in its name. Systemd silently ignores names such instances and doesn't start them.

From https://www.freedesktop.org/software/systemd/man/systemd.unit.html:

> Some unit names reflect paths existing in the file system namespace. Example: a device unit dev-sda.device refers to a device with the device node /dev/sda in the file system namespace. If this applies, a special way to escape the path name is used, so that the result is usable as part of a filename. Basically, given a path, "/" is replaced by "-", and all other characters which are not ASCII alphanumerics are replaced by C-style "\x2d" escapes (except that "_" is never replaced and "." is only replaced when it would be the first character in the escaped path). The root directory "/" is encoded as single dash, while otherwise the initial and ending "/" are removed from all paths during transformation. This escaping is reversible. Properly escaped paths can be generated using the systemd-escape(1) command.

Please document using red bold font that instance names must not contain "-", "/" and other special characters. This is a limitation of systemd.

**Comment by lenkis** [comment]
Oops, we need to mention it in tarantoolctl man / --help

**Comment by lenkis** [comment]
+ revise instance names in doc (e.g. in app server)

**Comment by rtsisyk** [comment]
@lenkis we found a solution for  this problem. Could you please revert documentation changes?
