### ISSUE TITLE
[0pt] Find and correct breaking of entity names

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#2782]
## Issue
 
In some tables, columns are too narrow to keep the entity names solid (without unnecessary breaks). For example,
https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_space/create_index/#box-space-index-field-types: the **Index field type** column.

## ToDo

- [ ] Find the most important and/or critical tables with this issue.
- [ ] Correct the issues. 
For instance, the settings of the example table above is the following:
https://github.com/tarantool/doc/edit/latest/doc/reference/reference_lua/box_space/create_index.rst#L197-L199  

  ```
  ..  list-table::
      :widths: 10 45 20 15
      :header-rows: 1
  ```
You can easily correct the issue by changing the width of the 1st column from 10 to 11 or 12 (needs double-checking on the dev environment).

**Comment by patiencedaur** [comment]
Here is another table: https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_index/
Looks like a lot of them are in the Reference section.
