### ISSUE TITLE
Improve the Transactions section

### ISSUE THREAD

**Issue by xuniq** [tarantool/doc#2812]
**Product:** Tarantool
**Root document:** https://www.tarantool.io/en/doc/latest/book/box/atomic/
**SME:** @ Mons

# Definition of done

- [ ] Split the Transactions page into separate sections.
- [ ] Add a separate page with the table of contents in the Transactions section.

Example:
https://www.tarantool.io/en/doc/latest/reference/

**Comment by patiencedaur** [comment]
Related issue:
https://github.com/tarantool/tarantool.io/issues/1275
