### ISSUE TITLE
Decide upon error handling style and add it to lua styleguide

### ISSUE THREAD

**Issue by racktear** [tarantool/doc#285]
There are 2 existing approaches to handle errors in lua:

```lua
local rc, value = foo()

if not rc then
    log.error("error while calling 'foo()': %s", value)
    return false, value
end

bar(value)
```

And

```lua
local value, err = foo()

if err ~= nil then
    log.error("error while calling 'foo()': %s", err)
    return nil, err
end

bar(value)
```

Both of those ways are used across our codebase. I suggest that we pick one, and stick to it. Probably fixing some of our official lua modules for consistency.

**Comment by racktear** [comment]
My proposal:

- Pick the second option
- Ban the usage of exceptions in all cases, except for incorrect function arguments.

Why I'm for this particular way:
- I think it's more natural for the first return value to be the result of function call
- functions that don't return errors, fit well into this framework
- We can see this method used in Go
- It is uses in some other lua modules, like luasocket

**Comment by bigbes** [comment]
@racktear (second method is used by Go. Lua, BTW, is not Go)

The first one is in core of language:

```
local ok, rv1, rv2, ... = pcall(fun, ...)
local ok, rv1, rv2, ... = xpcall(fun, err_cb, ...)
```

This one supports multireturn natively, No confusing in case of function returns nil/msgpack.NULL and some other value.

Summing up: second one is not native to this language and has many restrictions. So my react is a ❤️ to the first one.

**Comment by bigbes** [comment]
And BTW, modified first one:
```
local rc, value = foo()

if not rc then
    log.error("error while calling 'foo()': %s", value)
    return false, value
end

bar(value)
```

**Comment by Totktonada** [comment]
I’m tentative about the choice. Now I using the first approach.

> No confusing in case of function returns nil/msgpack.NULL and some other value.

The second approach checks `err` with `nil`, not an object, so it is not a problem in the both cases.

**Comment by kostja** [comment]
Done.
