### ISSUE TITLE
download page

### ISSUE THREAD

**Issue by bigbes** [tarantool/doc#29]
> Visit the Tarantool repository at GitHub to download the latest source files for version 1.7.

No way. You can't use sources from GitHub, only from Releases page. VERSION file is absent.

>  Please consult with the Tarantool documentation for build-from-source instructions on your system.

build-from-source must lead to https://tarantool.org/doc/dev_guide/building_from_source.html

**Comment by pgulutzan** [comment]
In fact it's easy to use github.com sources, but the second matter is correct. This is about the page https://tarantool.org/download.html.

**Comment by bigbes** [comment]
Peter, problem is an absence of VERSION file. Cmake tries to find it or it tries to use git revision. Git folder is absent, so it fails. 
Maybe it'll be a good idea to use obly major VERSION number, git it's a matter of discussion in tarantool repo, i guess

**Comment by pgulutzan** [comment]
I frequently pull from github source and then say "cmake ." and "make". It does not fail. Perhaps the "matter of discussion" is tarantool/build https://github.com/tarantool/build/commit/c87ff6dff707b0a5e059de8775f2a305d48812ff

**Comment by bigbes** [comment]
Sorry, if my information is obsolete, Peter. I'll check it again soon.
Maybe github link on a download page is a good choice.

20 авг. 2016 г. 17:00 пользователь "Peter Gulutzan" <
notifications@github.com> написал:
