### ISSUE TITLE
Move info about index types

### ISSUE THREAD

**Issue by zloidemon** [tarantool/doc#292]
Please add index types [here](https://tarantool.org/doc/1.7/book/box/box_index.html?highlight=index#module-box.index) from that [page](https://tarantool.org/doc/1.7/book/box/box_space.html?highlight=index#lua-data.space_object.index) always got a lot efforts to find kind of index.

**Comment by lenkis** [comment]
closed with commit https://github.com/tarantool/doc/commit/1c0357e3ef433a50eb4d6b2eb214bbeeada2b874
