### ISSUE TITLE
Remove pre-release version from docs after release

### ISSUE THREAD

**Issue by p7nov** [tarantool/doc#2930]
Descriptions of new features added in pre-release versions (alpha, beta, rc) often contain introductions like "since 2.10.0-beta1". They help us highlight new features, promote them, and stimulate users to try new versions.
After the release version is out, such intros become outdated (we don't expect users to use pre-release versions anymore) and even confusing (users may think that the release version is not available yet).

Taking into account that we have a single doc for all versions of a major release (1.*, 2.*), it's better to leave such intros and just remove the pre-release version postfix. For example:
> Since 2.10.1-beta1 >>> Since 2.10

This will let users know what features are available in their version and can also stimulate upgrades.

**Reviewer:** @ documentarian name

# Definition of done

- [ ] replace mentionings of pre-release versions and accompanying links with the release version.

**Comment by patiencedaur** [comment]
Let's define the scope.

**Relevant mentions of "-beta1":**
```
/doc/doc$grep -nr "-beta1" | grep ".rst"
book/box/atomic/atomic-transactions.rst:10:222:Since :tarantool-release:`2.10.0-beta1`, Tarantool supports streams and interactive transactions over them.
book/box/stream.rst:11:139:Since :tarantool-release:`2.10.0-beta1`, iproto implements streams and interactive transactions.
dev_guide/internals/box_protocol.rst:849:25875:Prior to Tarantool version 2.10-beta1, IPROTO_RAFT_CONFIRM was called IPROTO_CONFIRM.
dev_guide/internals/box_protocol.rst:1329:42692::tarantool-release:`2.10.0-beta1`, allows two things:
reference/reference_sql/sql_statements_and_clauses.rst:274:10591:The rules for the SCALAR data type were significantly changed in Tarantool version :tarantool-release:`2.10.0-beta1`.
```
**Relevant mentions of "-beta2":**
```
/doc/doc$ grep -nr "-beta2" | grep ".rst"
reference/reference_sql/sql_statements_and_clauses.rst:379:15768:Before Tarantool version 2.10-beta2, there were also some Tarantool/NoSQL data types which had no corresponding
reference/reference_sql/sql_user_guide.rst:193:8430:Prior to Tarantool version 2.10-beta2, digits with periods such as .0 were considered to be DOUBLE literals,
reference/reference_sql/sql_user_guide.rst:568:24671:Before Tarantool version 2.10-beta2 there was no literal format for DECIMAL,
reference/reference_sql/sql_user_guide.rst:652:28710:In Tarantool versions before 2.10-beta2,
reference/reference_sql/sql_user_guide.rst:1123:53813:This is a slight change: before Tarantool version 2.10-beta2, it was legal to cast such values
```
Looks like 2sp to me, including edits to the translations.

But there is also the [legacy release policy](https://www.tarantool.io/en/doc/latest/release/legacy-policy/). If we want to strictly remove mentions of anything but the release versions, we have to also consider removing mentions of versions like `*.*.0` and `*.*.1` up to 2.8.1. Do we want to do it?

**Comment by patiencedaur** [comment]
We decided not to mess with the legacy version numbers for now.
