### ISSUE TITLE
[tap] taptest:test seems to be undocumented

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#296]
Source: https://github.com/tarantool/tarantool/blob/9422f1ccb7c325809d8b4bcc8f7f1d05f74bcc93/src/lua/tap.lua#L210
Test: https://github.com/tarantool/tarantool/blob/cc32316f8d42e2aa55fcfe4e7a15e8be483c7421/test/app-tap/tap.test.lua#L67

**Comment by bigbes** [comment]
It's not the only thing, that's undocumented.
https://github.com/tarantool/tarantool/blob/cc32316f8d42e2aa55fcfe4e7a15e8be483c7421/test/app-tap/tap.test.lua#L135-L136

`taptest:like` and `taptest:unlike` isn't documented, too
