### ISSUE TITLE
Create a guideline for illustrations in the doc

### ISSUE THREAD

**Issue by patiencedaur** [tarantool/doc#2988]
**Root document:** https://www.tarantool.io/en/doc/latest/contributing/docs/
**SME:** @ Katedraw

# Details

*   What kind of visual elements do we need in the docs? Tables, diagrams, something else?
*   What are the brand colors? Are there other branding elements to consider?
*   Can we store a UI kit in such a way that it's available to outside contributors?

# Definition of done

- [ ] Non-designers understand the guidelines and don't find them complicated
- [ ] The guidelines are software-independent (can be used with draw.io, GIMP, and any other software)

**Comment by p7nov** [comment]
Miro board with diagram elements and examples from Ekaterina: https://miro.com/app/board/uXjVOnEuEsQ=/?share_link_id=928039843038
(make sure that the arrow color is changed to VK brand blue)
