### ISSUE TITLE
tt install/search/uninstall

### ISSUE THREAD

**Issue by patiencedaur** [tarantool/doc#3002]
**Epic: [Document TT CLI](https://github.com/tarantool/doc/issues/2553)**
Related dev issue: https://github.com/tarantool/tt/issues/12
Related dev epic: https://github.com/tarantool/tt/issues/17

Product: TT CLI
Since: 2.10
Audience/target: dev, admin
Root document: TBA
SME: @ LeonidVas

**Comment by p7nov** [comment]
`tt remove` is renamed to `tt uninstall`
