### ISSUE TITLE
Document /etc/tarantool/instances.{available,enabled}

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#301]
I [tried](https://github.com/tarantool/gentoo-overlay/issues/16#issuecomment-327484813) to answer the question about what are instances.available and instances.enabled in context of Gentoo Linux with OpenRC as an initialization system. That was pretty hard to do. I think a behaviour of tarantoolctl / openrc scripts / systemd unit / old sysvinit scripts (what distros?) need to be described for the following four cases:

* service name passed (sysconfig have / have no instance_dir set);
* service name omitted (sysconfig have / have no instance_dir set).

And maybe changed a bit if cases will be too different.

**Comment by lenkis** [comment]
https://tarantool.org/en/doc/1.7/book/admin/instance_config.html#tarantoolctl-configuration-file ?

**Comment by lenkis** [comment]
let's put all exceptions here:
https://tarantool.org/en/doc/1.7/book/admin/os_notes.html
we already have notes for FreeBSD. feels like we need more
