### ISSUE TITLE
Upgrade plan from 1.6 to 1.10

### ISSUE THREAD

**Issue by Mons** [tarantool/doc#3042]
**Epic: [Tarantool installation and upgrades](https://github.com/tarantool/doc/issues/2572)**

**SME**: @ sergepetrenko

We have a cluster of 1.6 with the following configuration:
- 7 nodes
- full mesh
- one rw, others ro
- rich application with background fibers and network operations (net.box & http)
- rw have background fibers modify data and work with network
- balancer, that routes request traffic to ro or rw depending on instance status and role (in fact, balancers are 1.10)

We know, that application works on 1.10 without any modifications due to compatibility layer, based on `kit`, `config` and `spacer/v1` (from github.com/moonlibs).

We need a guide to perform **live** migration without downtime from 1.6 to 1.10, i.e. we can't stop writes or reads "for some time"

**Comment by Totktonada** [comment]
NB: https://github.com/tarantool/tarantool/wiki/Caveats-when-upgrading-from-tarantool-1.6

**Comment by Totktonada** [comment]
BTW, https://github.com/tarantool/tarantool/wiki/Upgrade-instructions collects all such instructions. Maybe it worth to mention it somewhere in the documentation.

**Comment by patiencedaur** [comment]
Related: https://github.com/tarantool/doc/issues/836
