### ISSUE TITLE
Document string.split()/ljust()/rjust()/

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/doc#311]
https://github.com/tarantool/tarantool/issues/2214

**Comment by sharonovd** [comment]
Looks like the whole string module requires documentation:
local string = require('string')
string.split      = string_split
string.ljust      = string_ljust
string.rjust      = string_rjust
string.center     = string_center
string.startswith = string_startswith
string.endswith   = string_endswith
string.hex        = string_hex
