### ISSUE TITLE
Add page with list of documentation links for Tarantool modules

### ISSUE THREAD

**Issue by hackallcode** [tarantool/doc#3148]
**Product:** Tarantool
**Audience/target:** Tarantool customers, Tarantool developers
**Root document:** https://www.tarantool.io/en/doc/latest/reference/reference_rock/
**SME:** @ hackallcode

Provide links to at least the most popular rocks. This includes links to Cartridge and metrics, because the users can't always find them right away.

# Details

Finding documentation for the Tarantool modules is now quite difficult. When searching by the name of the module in the Tarantool doc, there are dozens of pages in the search results. There is no page on which there will be a list of all Tarantool modules and opposite each one there will be a link to the documentation of the module.

For example, links to documentation for the following modules would be useful to me:

    - crud
    - checks
    - cartridge
    - icu-date
    - space-explorer
    - metrics

Tarantool module registry: https://www.notion.so/tarantool/144028f939df446b8e08b4bad8d285db?v=9a9cd650e2cf42e18d2f6ce76fd96e80

**Comment by artur-barsegyan** [comment]
Maybe the https://www.tarantool.io/ru/doc/latest/reference/ page can be a root document for that purpose.

**Comment by patiencedaur** [comment]
Related:
- https://github.com/tarantool/doc/issues/2757
There is no consensus among developers and product managers on what a "module" is.

**Comment by patiencedaur** [comment]
For now, it was decided to provide links to the 6 rock modules above on the Rocks reference page.
