### ISSUE TITLE
Create the new Developer's guide section

### ISSUE THREAD

**Issue by patiencedaur** [tarantool/doc#3179]
**Epic: [Restructure Tarantool docs, stage 3](https://github.com/tarantool/doc/issues/3175)**

Related issue: https://github.com/tarantool/doc/issues/3180. Do them in a single PR.

## Details

- [ ] Choose a name: "Developer's guide", "Developer guide", "Development" (compare to "Administration")...

Create a top-level menu item with the corresponding title, next to "Concepts" and "How-to guides".
This is the first part of the task where we take top-level sections and put them under the Dev guide umbrella.

- [ ] Move "CRUD operations" to Dev guide. Cross-link from relevant Concepts pages
- [ ] Move "Triggers" to Dev guide (from Concepts). Cross-link in relevant places
- [ ] Move translations
- [ ] Fix links that definitely broke after the changes
- [ ] Add redirects after merge ([instruction](https://www.notion.so/tarantool/5b0e1ab45d0841a3b502cfea89829ef7))

## Desired structure of the Developer's Guide

Menu item order is TBD.

- Tarantool Lua syntax
- CRUD operations
- Triggers
- Internals (provide external link to [tarantool.io/en/dev/core](http://tarantool.io/en/dev/core))
- Developing with Cartridge (temporarily link to Cluster on Cartridge)
- Links (one page, below are the contents)
    - Awesome Tarantool
    - Tutorials
    - Best practices
    - Reference

**Comment by andreyaksenov** [comment]
The `Developing applications` section is going to be reworked: https://github.com/tarantool/doc/issues/3920.
See also: https://github.com/tarantool/doc/issues/3817.
