### ISSUE TITLE
Move pages from Reference

### ISSUE THREAD

**Issue by patiencedaur** [tarantool/doc#3180]
**Epic: [Restructure Tarantool docs, stage 3](https://github.com/tarantool/doc/issues/3175)**

Related issue: https://github.com/tarantool/doc/issues/3179. Do them in a single PR.

## Details

- [ ] Move from Reference to Dev guide: Internals > Binary protocol (related: https://github.com/tarantool/doc/issues/2526 -- "Binary protocol" rewrite), MessagePack extensions, File formats, Replication internals
- [ ] Move from Reference > Internals to How-to guides: "The recovery process"
- [ ] Move from Reference to Dev guide: Limitations
- [ ] Move from Reference to Dev guide: Tips on Lua syntax (rename to Tarantool Lua syntax because this is not a style guide)
- [ ] Move translations
- [ ] Fix links that broke after the changes
- [ ] Provide cross-links to moved documents in relevant places
- [ ] On the top-level page, add introductory text about developing with Tarantool. Add a link to the [Tooling](https://www.tarantool.io/en/doc/latest/reference/tooling/) section
- [ ] Add a page with a list of useful links: [Awesome Tarantool](https://github.com/tarantool/awesome-tarantool#resources), LuaJIT docs (SME: @ igormunkin), best practices and other links as listed below (SME: probably @ Totktonada). Here is a [Notion document](https://www.notion.so/tarantool/Tarantool-6089c83eae4f422cb1371b9548de925c) with some clues.
- [ ] Add redirects after merge ([instruction](https://www.notion.so/tarantool/5b0e1ab45d0841a3b502cfea89829ef7))

## Desired structure of the Developer's Guide

Menu item order is TBD.

- Tarantool Lua syntax
- CRUD operations
- Triggers
- Internals (provide external link to [tarantool.io/en/dev/core](http://tarantool.io/en/dev/core))
- Developing with Cartridge (temporarily link to Cluster on Cartridge)
- Links (one page, below are the contents)
    - Awesome Tarantool
    - Tutorials
    - Best practices
    - Reference

**Comment by andreyaksenov** [comment]
The `Developing applications` section is going to be reworked: https://github.com/tarantool/doc/issues/3920.
See also: https://github.com/tarantool/doc/issues/3817.
