### ISSUE TITLE
Workaround for illegal type names for upgrading to 2.10.4

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#3229]
**Related dev. issue(s):** https://github.com/tarantool/tarantool/issues/7841

**Product:** Tarantool
**Since:** 2.10.4
**Audience/target:** application developers, maybe devops
**Root document:** (not sure)
**SME:** @Totktonada

# Details

* What should we write about?

  @NeraverinTarantool asked me to file an issue to document [the workaround](https://github.com/tarantool/tarantool/wiki/Fix-illegal-field-type-in-a-space-format-when-upgrading-to-2.10.4) for upgrading tarantool instances with illegal field types in space formats to tarantool 2.10.4, which forbids them.

**Comment by p7nov** [comment]
Seems that a link in release notes can help with this.
And maybe a note on a page where we introduce these types.
