### ISSUE TITLE
Fix Install Tarantool on Debian/Ubuntu (1.10, manual)

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#3252]
## Info

**Root documents:**

https://www.tarantool.io/en/download/os-installation/debian/
https://www.tarantool.io/en/download/os-installation/ubuntu/

'Manual repository installation' sections for 1.10 repositories.

## What's wrong?

Pinning origin of all three `tarantool`, `tarantool-common` and `tarantool-dev` packages is essential. Lack of such pinning leads to problems on Debian Bullseye (11) and Ubuntu Jammy (22.04). See https://github.com/tarantool/installer.sh/pull/11, https://github.com/tarantool/tarantool/issues/5429#issuecomment-1336162554 and https://github.com/tarantool/setup-tarantool/issues/36 (starting from words 'tarantoolctl fatal error').

Ubuntu's instruction pins only `tarantool`. Debian's instruction doesn't pin any package. We should adopt the `installer.sh` fix for these manual instructions. Desirable for 2*, essential for 1.10.

## Planning checklist

- [ ] Estimate complexity in storypoints in the title.
- [ ] Add to **Documentation** board → **Backlog (small)**

> Note: issue templates are in beta. Give your feedback in #1869.

**Comment by p7nov** [comment]
Closing: 1.10 is no longer supported
