### ISSUE TITLE
Document the new tarantoolctl rocks and .rocks behavior

### ISSUE THREAD

**Issue by racktear** [tarantool/doc#328]
Recently we've added a `rocks` subcommand to `tarantoolctl` which allows to install/uninstall packages to .rocks directory. This needs to be documented.

Also, package loader has been extended to recursively look for .rocks directory in parent directories, and load lua packages from there.

**Comment by rtsisyk** [comment]
tarantoolctl rocks is already documented.

**Comment by lenkis** [comment]
Documented in detail here: https://github.com/tarantool/rocks#managing-modules-with-tarantool-174 (linked from https://tarantool.org/en/doc/1.7/book/app_server/installing_module.html#installing-a-module-from-a-repository)

And here: https://tarantool.org/en/doc/1.7/reference/tarantoolctl.html#commands-for-managing-tarantool-modules
