### ISSUE TITLE
[Epic] 2.11 IPROTO

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#3373]
**Related dev. epic:** 
**PM ref.:** 
**SME:** @ CuriousGeorgiy @ sergepetrenko @ Gerold103 

## Scope of work

- [x] https://github.com/tarantool/doc/issues/3241
- [x] https://github.com/tarantool/doc/issues/3288
- [x] https://github.com/tarantool/doc/issues/3278
- [x] https://github.com/tarantool/doc/issues/3166
- [x] https://github.com/tarantool/doc/issues/3193
- [x] https://github.com/tarantool/doc/issues/3294
- [x] https://github.com/tarantool/doc/issues/3299

**Comment by xuniq** [comment]
Done
