### ISSUE TITLE
Document fio.mktree/rmtree/copyfile/copytree/listdir

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/doc#340]
These functions are copy-cat of Python API:

- copytree - https://docs.python.org/2/library/shutil.html#shutil.copytree
- copyfile - https://docs.python.org/2/library/shutil.html#shutil.copyfile
- rmtree - https://docs.python.org/2/library/shutil.html#shutil.rmtree
- mkdir - https://docs.python.org/2/library/os.html#os.mkdir
-  listdir - https://docs.python.org/2/library/os.html#os.listdir

Added to upcoming 1.7.7 (branch 1.7-next)

**Comment by rtsisyk** [comment]
https://github.com/tarantool/tarantool/issues/2751

**Comment by Totktonada** [comment]
I propose to mention that `mv` can be implemented as `rename || copytree + rmtree`. Not sure this is right for a regular file.
