### ISSUE TITLE
Download instructions for 1.7 are broken

### ISSUE THREAD

**Issue by aensidhe** [tarantool/doc#342]
Use `ubuntu:xenial` docker image. Try to apply instructions from https://tarantool.org/en/download/os-installation/1.7/ubuntu.html

I'm getting 1.6.7 after them.

Use new container from same image. Apply instructions from https://packagecloud.io/tarantool/1_7. You'll get latest 1.7 build.

**Comment by rtsisyk** [comment]
$release variable has lost in tee <<-EOF.

Let's change snippet to:
```
echo "deb http://download.tarantool.org/tarantool/1.7/ubuntu/ $release main" > /etc/apt/sources.list.d/tarantool_1_7.list
echo "deb-src http://download.tarantool.org/tarantool/1.7/ubuntu/ $release main" >> /etc/apt/sources.list.d/tarantool_1_7.list
```
