### ISSUE TITLE
Reset configuration button not working in try tarantool

### ISSUE THREAD

**Issue by mrpond** [tarantool/doc#3480]
# What needs to be done
Make this button working 
<img width="1007" alt="image" src="https://github.com/tarantool/doc/assets/18654771/722d37c3-d366-4b67-b1d2-b3514f8d0e3a">
refer to issue: 3479
I try starting over because I want to change videos schema. it not working.
ending up doing it in local docker but got no space explorer to see the data.

**Reviewer:** @ documentarian name

# Definition of done

- [ ] do A
- [ ] do B

# Planning checklist

- [ ] Pick a label
- [ ] Estimate complexity in storypoints in the title
- [ ] Add to **Documentation** board → **Backlog**

> Note: issue templates are in beta. Give your feedback in #1869.

**Comment by p7nov** [comment]
Closing: not related to docs, try.tarantool is generally outdated.
