### ISSUE TITLE
Examples for box do not work after field type changes

### ISSUE THREAD

**Issue by smenshikh** [tarantool/doc#35]
After this commit https://github.com/tarantool/doc/commit/1b14b2e93597b73d069e486462f8803c88a0a988 examples with field types for indices do not work. At least in tarantool 1.7.0

**Comment by pgulutzan** [comment]
The new field types were not a feature of Tarantool 1.7.0. Please check whether there is any problem with the current Tarantool version, and indicate what the error message is.

**Comment by smenshikh** [comment]
On a page http://try.tarantool.org/
`tarantool> s = box.schema.space.create('tester')`
`tarantool> s:create_index('primary', {type = 'hash', parts = {1, 'unsigned'}})`
`---`
`- error: 'Can''t create or modify index ''primary'' in space ''tester'': unknown field`
`    type'`
`...`
There is no error if 'NUM' is placed instead of 'unsigned'.

**Comment by kostja** [comment]
Thanks, we need to update try.tarantool.org to version 1.7

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by smenshikh** [comment]
Unknown field type error also occurs in tarantool version 1.7.0-1219-g359d812

**Comment by rtsisyk** [comment]
> Unknown field type error also occurs in tarantool version 1.7.0-1219-g359d812

Please upgrade to the latest 1.7.1

**Comment by smenshikh** [comment]
Well, then I was confused by this page https://tarantool.org/doc/singlehtml.html with the title 'Tarantool **1.7.0** documentation'

**Comment by pgulutzan** [comment]
The manual has been updated and the title no longer is 'Tarantool 1.7.0 documentation'. I apologize for causing confusion.
