### ISSUE TITLE
Tarball link doesn't work

### ISSUE THREAD

**Issue by zloidemon** [tarantool/doc#351]
Hello you, on [page](https://tarantool.org/en/download/os-installation/1.7/building-from-source.html) link to **tarball** doesn't work. I only see message below last month

```
<Error>
<Code>AccessDenied</Code>
<RequestId>JM4xgWyr</RequestId>
<Message>Access Denied</Message>
</Error>
```

**Comment by kostja** [comment]
This is now fixed.
