### ISSUE TITLE
3.0 release notes

### ISSUE THREAD

**Issue by p7nov** [tarantool/doc#3517]
**Product:** Tarantool
**Since:** 3.0
**Audience/target:** all
**Root document:** new page in https://www.tarantool.io/en/doc/latest/release/
**SME:** @ Totktonada @ NeraverinTarantool 

# Details

Write release notes for Tarantool 2.11 in the form of What's New - complete human-readable descriptions of new features with examples and business value (see [What's new in 2.11](https://www.tarantool.io/en/doc/latest/release/2.11.0/) for reference).
Collaborate with the product team to form the final list of features to present in the release notes.

3.0.0-beta1 on GitHub:
- CE: https://github.com/tarantool/tarantool/releases/tag/3.0.0-beta1
- EE: https://github.com/tarantool/tarantool-ee/releases/tag/3.0.0-beta1

# Definition of done

- [x] get the approved list of features to present in the release notes from product managers
- [x] prepare human-readable feature descriptions with examples and links to docs
- [x] link to the release changelog on GitHub
- [ ] link to the 3.0 migration guide (not ready yet, postponed to 3.1)

**Comment by andreyaksenov** [comment]
Draft structure: https://docs.google.com/document/d/17Gfah0bdOPjqxz9yAuyDNRAr2A5eIkDqsx1UbT54a8U/edit?usp=sharing

**Comment by andreyaksenov** [comment]
https://docs.d.tarantool.io/en/doc/3.0/release/3.0.0/
