### ISSUE TITLE
Deprecate msgpack.ibuf_decode

### ISSUE THREAD

**Issue by locker** [tarantool/doc#352]
Mark `msgpack.ibuf_decode` as deprecated. Recommend using `msgpack.decode` or `msgpack.decode_unchecked` instead.

See: https://github.com/tarantool/tarantool/issues/2755

**Comment by lenkis** [comment]
This should go to both 1.7 and 1.8 doc branches.
Peter, please add to 1.7, and I'll merge it further to 1.8.

**Comment by Totktonada** [comment]
The new function variants that accept a string buffer were introduced in https://github.com/tarantool/tarantool/issues/2755: that is the reason of deprecation of the separate `msgpack.ibuf_decode` function. The new variants should be described in the website documentation. Now the [documentation](https://www.tarantool.io/en/doc/1.10/reference/reference_lua/msgpack/) lacks it.

The linked issue has great formal description of the new API. It would be good to have it on the website.

**Comment by pgulutzan** [comment]
The 1.10 [documentation](https://www.tarantool.io/en/doc/1.10/reference/reference_lua/msgpack/) lacks description of some functions that are in the 2.2 [documentation](https://www.tarantool.io/en/doc/2.2/reference/reference_lua/msgpack/); Are those the functions that are supposed to be described? If so, perhaps long ago I pushed a change to the wrong version.

**Comment by pgulutzan** [comment]
There was no reply, and the changes have been copied to the 1.10 documentation, so I have removed the "need feedback" tag and am closing this issue.

**Comment by Totktonada** [comment]
Sorry for reopening this again, but `encode` / `decode` / `decode_unchecked` variants, which reads from or writes to a `char *` buffer, are not described in the docs. See https://github.com/tarantool/tarantool/commit/68c213975a31d0c05b1e5d23e6112417e315f995

**Comment by pgulutzan** [comment]
I looked at the version-2.4 decode_unchecked documentation, here:
https://www.tarantool.io/en/doc/2.4/reference/reference_lua/msgpack/#msgpack-decode-unchecked
I clicked on the word "buffer" in the sentence "For an example see the buffer module."
I ran the example there, which includes decode_unchecked.
The result is what the manual describes (at least in 2.4).
So I am trying to understand why, although it is described in the docs, it is not found.
Perhaps my mistake is that I did not properly link, or did not properly explain when I closed?

**Comment by Totktonada** [comment]
Several points:

* `encode()` may accept a buffer (`buffer.ibuf()` kind) as the second argument. Note also that it returns number of written bytes in the case, not a Lua string with encoded msgpack data.
* `decode()` may accept a buffer (`cdata<char *>` kind) as the first argument and it also changes meaning of the second argument (it becomes the buffer size).
* Re `decode_unchecked()`: `cdata<char *>` or `cdata<const char *>` is not `string`. They are different types in Lua. So current description can be confusing for users.
* Cite:
  > Because checking is skipped, decode_unchecked() can operate with string pointers to buffers which decode() cannot handle.

  I would not say that support of `char *` is consequence of lack of buffer bounds checks.

**Comment by Totktonada** [comment]
(@pgulutzan Feel free to ask me details here or privately if something is not clear or if you think that I missed something.)

**Comment by pgulutzan** [comment]
@Toktonada: Thank you. I made several changes to the version 2.4 manual, but won't close if you think it is still not done.

**Comment by Totktonada** [comment]
> .. function:: decode_unchecked(C_style_string_pointer[, size])
>     Input and output are the same as for
>     :ref:`decode(C_style_string_pointer) <msgpack-decode_c_style_string_pointer>`,
>     except that ``size`` is optional.

decode_unchecked() with C-style-pointed (cdata first argument) does not check size at all (even if it passed). I think we should not see optional `size` in the function arguments.

How to verify:

```
tarantool> msgpack = require('msgpack')
tarantool> ffi = require('ffi')
tarantool> msgpack.decode(ffi.cast('char *', '\x91\x00'), 1)
---
- error: 'msgpack.decode: invalid MsgPack'
...

tarantool> msgpack.decode_unchecked(ffi.cast('char *', '\x91\x00'), 1)
---
- [0]
- 'cdata<char *>: 0x40eb9d82'
...
```

Except this, I don't have objections. Please, update all versions and close the issue finally.

**Comment by pgulutzan** [comment]
Okay, changes pushed in 2.4, 2.3, 2.2, and 1.10.

**Comment by Totktonada** [comment]
Thank you, Peter!
