### ISSUE TITLE
Do not ask for contributions in TDG doc

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/doc#3534]
TDG documentation is solely in Russian (in contrary to core documentation). Yet `/ru/tdg` web pages invite contributors to translate doc from English to Russian, even though we are likely need Russian to English translation here and TDG users are unlikely to participate in community contribution either way.
![image](https://github.com/tarantool/doc/assets/20455996/bbadd3ef-fa3d-477d-ac4f-187b906d1e5e)

I think it would be better to remove this message for TDG doc pages.

**Comment by veod32** [comment]
@lastoCHka42  Можем ли мы убрать этот баннер в отдельно взятой репе -- /tdg-doc ?

**Comment by lastoCHka42** [comment]
Думаю, да
