### ISSUE TITLE
Update description of replication lag/idle

### ISSUE THREAD

**Issue by locker** [tarantool/doc#355]
Since commit https://github.com/tarantool/tarantool/commit/10e11e9b8e5869a50f42005266781af528616e84 replication `lag` and `idle` statistics are updated even if the master is idle. This is done by sending "heartbeat" messages every `box.cfg.replication_timeout` seconds (see https://github.com/tarantool/tarantool/issues/2976). Please update the documentation accordingly.

A proposal by @kostja:

> The primary indicators of replication health are idle and lag parameters:
> idle is the time since this replica received the last event from a master.
> lag is the time difference between the local time at the replica, recorded when the event was received, and the local time at the master recorded when the event was written to the write ahead log on the master. Since lag calculation uses operating system clock from two different machines, don’t be surprised if it’s negative: a time drift may lead to the master clock being consistently behind the replica clock.
> 
> Idle is the primary indicator of replication health. A replica sends heartbeat messages to the master every second, and the master is programmed to reconnect automatically if it doesn’t see heartbeat messages more often than replication_reconnect_interval seconds. Therefore, in a healthy replication setup, idle should never exceed replication_reconnect_interval: if it does, either your replication is lagging seriously behind, because the master is running ahead of the replica, or the network link between the instances is down.

**Comment by lenkis** [comment]
closed with commit https://github.com/tarantool/doc/commit/3854753470a944bf61166addf6d4db631771118b
