### ISSUE TITLE
Installation Tarantool 2.11 on Apple M1

### ISSUE THREAD

**Issue by peterdev80** [tarantool/doc#3571]
In the Tarantool installation documentation, there is an indication "Bleeding edge beta Apple M1 brew install tarantool --HEAD" . This entry may be regarded as an installation under M1, but this is an incorrect version

**Comment by igormunkin** [comment]
@p7nov, this is hardly related to DevX team. What should be done in scope of this issue: one need to update installation instructions for macOS/M1 platforms (unfortunately, I failed to find the dedicated page or section in our docs).

**Comment by p7nov** [comment]
> @p7nov, this is hardly related to DevX team. What should be done in scope of this issue: one need to update installation instructions for macOS/M1 platforms (unfortunately, I failed to find the dedicated page or section in our docs).

I've added this to DevX because the instruction is located outside the docs: https://www.tarantool.io/en/download/os-installation/os-x/. Anyway, we'll help with the content.

**Comment by igormunkin** [comment]
Ouch, my bad then. Thanks for clarification!
