### ISSUE TITLE
Update hot standby instructions

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#358]
This piece was not done within gh-357 (troubleshooting guide).

**Comment by lenkis** [comment]
Blocked by https://github.com/tarantool/tarantool/issues/3002

See text draft here (page 2, "Restarting Tarantool in the hot standby mode"):
https://docs.google.com/document/d/10tHnjXIpMkVCSm0HH8v1g7Xxb-bJrIccSLBvLkAtXFE/edit?usp=sharing

**Comment by Totktonada** [comment]
@patiencedaur Whether it is done or will not be fixed?

**Comment by patiencedaur** [comment]
The contents of the document above are in the troubleshooting guide already: https://www.tarantool.io/en/doc/latest/book/admin/troubleshoot/#problem-insert-update-requests-result-in-er-memory-issue-error
