### ISSUE TITLE
deprecate configuration option `replication_connect_quorum`

### ISSUE THREAD

**Issue by gmoshkin** [tarantool/doc#3642]
**Product:** Tarantool
**Since:** 
**Root document:** 
- https://www.tarantool.io/en/doc/latest/reference/configuration/#cfg-replication-bootstrap-strategy
- https://www.tarantool.io/en/doc/latest/reference/configuration/#cfg-replication-replication-connect-quorum
- https://www.tarantool.io/en/doc/latest/release/2.11.0/#new-bootstrap-strategy

**SME:** @ sergepetrenko

# Details

The newly added `box.cfg.bootstrap_strategy = "legacy"` option is based on the value of `replication_connect_quorum`, which implies that users should specify it. But if you specify both these options, e.g.
```lua
box.cfg { bootstrap_strategy = "legacy", replication_connect_quorum = 2 }
```
A warning is logged saying
```
Deprecated option replication_connect_quorum, please use bootstrap_strategy instead
```

Nowhere in the docs it says that `bootstrap_strategy = "legacy"` is deprecated, so it shouldn't be printing this warning.

**Upd by @sergepetrenko**:
Let's state in the doc that both `botstrap_strategy = "legacy"` and `replication_connect_quorum` are deprecated.

**Comment by sergepetrenko** [comment]
Thanks for the report !
We'll fix the doc.
