### ISSUE TITLE
Document the ability to install a program using commit hash and PR id.

### ISSUE THREAD

**Issue by psergee** [tarantool/doc#3649]
**Related dev. issue(s):** GitHub link(s)

**Product:** TT CLI
**Since:** TBD
**Root document:** https://www.tarantool.io/en/doc/latest/reference/tooling/tt_cli/install/
**SME:** @psergee

# Details

`tt install` now supports installation using commit hash and pull request id. Example:
```
tt install tarantool 00a9e59
tt install tt pr/582
```
Commit hash minimal length must be ≥7.

Describe this functionality on the ``tt install`` doc page and check if it may be mentioned in [Building to contribute](https://www.tarantool.io/en/doc/latest/dev_guide/building_from_source/).

# Definition of done

- [ ]  The `tt install` doc page explains the new installation scenario
- [ ] Building to contribute describes all relevant ways

**Comment by p7nov** [comment]
Additionally: `tarantool-dev` is available for installation (build from local source). See #3568 for details.
