### ISSUE TITLE
Document box.cfg { replication_connect_quorum = x }

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/doc#372]
A new option was added to allow box.cfg { replication = {xx, yy, zz} } without waiting for all replicas available.

 -   box.cfg { replication = {xx, yy, zz}, replication_connect_quorum = 0 } - don't wait replicas (old 1.6 behaviour)
 -   box.cfg { replication = {xx, yy, zz}, replication_connect_quorum = 100500} - wait all replicas (new 1.7 behaviour)
 -   box.cfg { replication = {xx, yy, zz}, replication_connect_quorum = N} - wait N replicas (custom logic)

**Comment by kostja** [comment]
See the original ticket with description: https://github.com/tarantool/tarantool/issues/2958
