### ISSUE TITLE
Document submit policies for patches

### ISSUE THREAD

**Issue by kyukhin** [tarantool/doc#376]
We're trying to introduce new patch review process.
Since 24.01.2018 changes prepared for review should be submitted
to `patches@tarantool.org`.
e-mail messages are prepared using `git format-patch` and
`git send-email`.

Need to formally describe the process in developer guide:
1. Describe what mail thread is and why it is useful
2. When cover letter is needed?
3. What to put in cover letter?
4. Options which should be added to `format-patch` (like `--signed-off`)
5. What prefixes to put in subject?
6. How to refer to git branch and issue (in cover letter)?
7. How to put updated changes derived from rebasing (force-pushing)
into same mail thread

Here's few scripts which might be useful for preparing e-mail messages:
https://gist.github.com/Gerold103/5471a7ddbeec346c0c845930d5bb9df4

**Comment by Totktonada** [comment]
LGTM.
