### ISSUE TITLE
is_nullable is missing in create_index on .io site and incorrect on .org site

### ISSUE THREAD

**Issue by Gerold103** [tarantool/doc#383]
https://tarantool.io/en/doc/1.7/book/box/box_space.html#lua-function.space_object.create_index - I can specify is_nullable in index parts.

https://tarantool.org/en/doc/1.7/book/box/box_space.html#box-space-is-nullable - here is_nullable = true declared as default, but actually is_nullable = false by default.

**Comment by lenkis** [comment]
Docs at .io site are all obsolete at the moment. We're migrating the up-to-date doc content from .org to .io these days. Thanks for reporting anyway.

**Comment by Gerold103** [comment]
But on .org is_nullable is still incorrect - it is not false by default ...

**Comment by lenkis** [comment]
Oops, I missed that when closing the ticket. Sorry. Fixed now.
