### ISSUE TITLE
[Epic] tt CLI 2.0-2.2 Q2

### ISSUE THREAD

**Issue by p7nov** [tarantool/doc#3850]
**Related dev. issue(s):** GitHub link(s)

**Product:** tt cli
**Since:** tt 2.0-2.2
**Audience/target:** all
**Root document:** https://www.tarantool.io/en/doc/latest/reference/tooling/tt_cli/
**SME:** @ psergee 

# Details

Update tt CLI docs according to changes in [releases 2.0.0-2.2.1](https://github.com/tarantool/tt/releases/). See also: [Migration from older versions](https://github.com/tarantool/tt/blob/master/doc/migration_from_older_versions.md).

# Important changes of tt 2.0

Key changes of tt 2.0 were documented in scope of #3996.

# Tasks

23 sp:
- [x] #3932
- [x] #4079
- [x] #4145 
- [x] #3933
- [x] #4078 
- [x] #3828
- [x] `tt replicaset`:
  - [x] #3966 
  - [x] #4088 
  - [x] #4109
  - [x] #4121
- [x] #4032 
- [x] #4026 
- [x] #4222 
- [x] #4249
- [x] #4288
- [x] #4289
- [x] #4290 
- [x] #4291 
- [x] #4188

**Comment by andreyaksenov** [comment]
It would be useful to have a doc page that describes scenarios for working with tt. Here are some of my thoughts on how tt commands can be divided depending on a usage scenario:

```
Prerequisites: install tt

1) Tips and tricks:
version
help
completion

2) Initialize the environment:
init
cfg

3) Install Tarantool:
search
install
uninstall
binaries

4) Developing the app:
create
instances
run
check
build
rocks
pack

5) Admininstration:
- (instances)
start	Start a Tarantool instance
status	Get the current status of a Tarantool instance
connect	Connect to a Tarantool instance
stop	Stop a Tarantool instance
restart	Restart a Tarantool instance
clean	Clean instance files

- (maintenance)
cat	Print the contents of .snap or .xlog files into stdout
play	Play the contents of .snap or .xlog files to another Tarantool instance

- (logs)
logrotate	Rotate instance logs

- (data)
crud	Interact with the CRUD module (Enterprise only)
export	Export data to a file (Enterprise only)
import	Import data from a file (Enterprise only)

6) Debugging:
coredump	Manipulate Tarantool core dumps
```

At least, we can try to group commands on this page instead of the current alphabetical list:
https://www.tarantool.io/en/doc/latest/reference/tooling/tt_cli/commands/

**Comment by andreyaksenov** [comment]
`tt connect` example with SSL:

```
% ls
client.crt      client.key
% tt connect 127.0.0.1:3301 \
           --username admin --password topsecret \
           --sslcertfile client.crt --sslkeyfile client.key
   • Connecting to the instance...
   • Connected to 127.0.0.1:3301

127.0.0.1:3301>
```

Without the cert and key files provided, the following error is thrown:

```
⨯ failed to run interactive console: failed to create new console: failed to connect: failed to dial: SSL errors: SSL routines::sslv3 alert handshake failure
```

Username and password can be also specified using env vars:

```
* TT_CLI_USERNAME - specifies a username
* TT_CLI_PASSWORD - specifies a password
```
