### ISSUE TITLE
SQL documentation plan

### ISSUE THREAD

**Issue by kostja** [tarantool/doc#386]
- [x] in 1.8, you don't have to run box.cfg to run the console; it starts for you automatically; update the docs
- [x] update the tutorial re set delimiter/set language, to show how to switch to SQL mode
-  [ ] extend the tutorial/getting started chapter: QQQ with what? 
- [ ] extend the user guide: QQQ: we need a plan
   - [ ] Introduction -- see https://github.com/tarantool/doc/issues/410
   - [ ] JOIN optimizer what it does (+secondary indexes?)
   - [ ] Triggers (per-stmt, per-row triggers)
   - [ ] Constraints
   - [ ] Foreign keys (+ DEFERRED FKs)
   - [ ] Transactions
- [ ] extend the reference
   - [ ] Common chapters re SQL (what's a table, what's an identifier, what's a collation - defninitions of terms
   - [ ] Language reference
      - [ ] INSERT
      - [ ] UPDATE
      - [ ] DELETE
      - [ ] SELECT
      - [ ] ALTER

**Comment by patiencedaur** [comment]
Tarantool SQL specifics are already covered in the doc. We don't need to go deeper---there is plenty of similar information on the web.

I'm cleaning up issues that are more than 3 years old and/or do not relate to latest or LTS versions. The capacity of our doc team is currently very limited.
