### ISSUE TITLE
Examples are missing

### ISSUE THREAD

**Issue by msiomkin** [tarantool/doc#387]
There are no examples in "Launching a binary program" section of "Launching an application" page (https://tarantool.io/en/doc/1.7/book/app_server/launching_app.html). Several instructions are followed by a colon. So, examples are implied, but they are missing.

**Comment by lenkis** [comment]
Already fixed at tarantool.org: https://tarantool.org/en/doc/1.7/book/app_server/launching_app.html
Will soon be ported to tarantool.io -- doc content at .io is currently outdated. Thanks for reporting!
