### ISSUE TITLE
Delete from _cluster table does not update replicaset vclock

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#389]
See https://github.com/tarantool/tarantool/issues/3109

**Comment by pgulutzan** [comment]
Handled on February 12 but "fixes" was not spelled correctly:
commit 9f806497b55ae737a398f87ffbc08a35bd6f598f
Author: ocelot-inc <pgulutzan@ocelot.ca>
Date:   Mon Feb 12 11:38:59 2018 -0700
    Fies gh-389 Delete from _cluster table does not update replicaset vclock
