### ISSUE TITLE
[Config] Add redirects for moved/removed topics

### ISSUE THREAD

**Issue by andreyaksenov** [tarantool/doc#3912]
Replication tutorials:

- [ ] https://www.tarantool.io/en/doc/latest/how-to/replication/repl_add_instances/ -> `/how-to/replication/repl_bootstrap/`
- [ ] https://www.tarantool.io/en/doc/latest/how-to/replication/repl_remove_instances/ -> `/how-to/replication/repl_bootstrap/`
- [ ] https://www.tarantool.io/en/doc/latest/how-to/replication/repl_sync/ -> `/concepts/replication/repl_sync/`
- [ ] https://www.tarantool.io/en/doc/latest/how-to/replication/repl_leader_elect/ -> `/concepts/replication/repl_leader_elect/`

Main issue: https://github.com/tarantool/tarantool.io/issues/1488

**Comment by lastoCHka42** [comment]
Forwarded from tarantool/tarantool.io#1488, comment by @andreyaksenov 

1. По Картриджу вижу такие 404 страницы сейчас:

tarantool.io/en/doc/latest/book/cartridge
tarantool.io/en/doc/latest/how-to/getting_started_cartridge
tarantool.io/en/doc/latest/book/cartridge
Их и все вложенные страницы можно средиректить на TCM:
tarantool.io/en/doc/latest/reference/tooling/tcm

2. Еще несколько разрозненных топиков:

tarantool.io/en/enterprise_doc/migration
tarantool.io/en/doc/latest/enterprise/admin
tarantool.io/en/doc/latest/enterprise/cartridge-auth
tarantool.io/en/doc/latest/enterprise/dev

Их можно средиректить на tarantool.io/en/doc/latest/enterprise
