### ISSUE TITLE
Add tarantool password recommendations

### ISSUE THREAD

**Issue by LeonidVas** [tarantool/doc#3962]
According to the description [here](https://www.notion.so/tarantool/ece9112295894b01913a48791cce5f2e?pvs=4#d821cbe357fe46f8bca14e0fe6f8c2ee), I think it would be nice to add a recommendation to use a >= 16 length password using `[a-Z0-9]` and special symbols like `[!$&'(|)*+,;=-_~.%]`.

Useful links:
https://jira.vk.team/browse/TNT-848

**Comment by p7nov** [comment]
https://www.tarantool.io/en/doc/latest/book/admin/access_control/#passwords

**Comment by andreyaksenov** [comment]
The example from the `Password policy` section uses all the recommendations:

https://www.tarantool.io/en/doc/latest/concepts/configuration/configuration_authentication/#password-policy
