### ISSUE TITLE
doc: Implement doc publishing from a corporate gitlab repo

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#3972]
**Проблема**: появляются проекты разработки в репозитириях корпоративного gitlab, в которых лежит сорс-контент документации по этим проектам. 

**Задача**: внедрить CI для сборки и публикации документации из таких репозиториев.

В качестве первого пилотного проекта берем репо продукта ATE (Ansible Tarantool Enterprise)
https://gitlab.corp.mail.ru/tarantool/delivery/ansible-tarantool-enterprise

**Reviewer:** @veod32 , @opomuc

**Comment by lastoCHka42** [comment]
Closed in https://gitlab.corp.mail.ru/tarantool/delivery/ansible-tarantool-enterprise/-/merge_requests/21/diffs#587d266bb27a4dc3022bbed44dfa19849df3044c
