### ISSUE TITLE
[Config] Document 'process' configuration settings

### ISSUE THREAD

**Issue by andreyaksenov** [tarantool/doc#4014]
**Related doc. issue(s):** https://github.com/tarantool/doc/issues/4079

**Product:** Tarantool
**Since:** 3.0
**Root document:** 
- A new `process` section in the [Configuration reference](https://www.tarantool.io/en/doc/latest/reference/configuration/configuration_reference/).

**SME:** @ Totktonada

# Details

Options:
- https://github.com/tarantool/tarantool/blob/f58bfc97c627f1838696697339fb3e443c05767a/src/box/lua/config/instance_config.lua#L640

Related topics:
- https://www.tarantool.io/en/doc/latest/reference/configuration/

**Comment by p7nov** [comment]
`process.*` options are added into the config reference with basic (draft) descriptions in scope of #4079 (PR #4169)

**Comment by lenkis** [comment]
Closed with https://github.com/tarantool/doc/commit/d27cd01e551e23eff0460cc021c3505b440db4ce
