### ISSUE TITLE
[Config] Document 'console' configuration settings

### ISSUE THREAD

**Issue by andreyaksenov** [tarantool/doc#4016]
**Product:** Tarantool
**Since:** 3.0
**Root document:** 
- A new `console` section in the [Configuration reference](https://www.tarantool.io/en/doc/latest/reference/configuration/configuration_reference/).

**SME:** @ Totktonada

# Details

Options:
- https://github.com/tarantool/tarantool/blob/f58bfc97c627f1838696697339fb3e443c05767a/src/box/lua/config/instance_config.lua#L688

**Comment by lenkis** [comment]
Closed with https://github.com/tarantool/doc/commit/d27cd01e551e23eff0460cc021c3505b440db4ce
