### ISSUE TITLE
[Config] Document 'fiber' configuration settings

### ISSUE THREAD

**Issue by andreyaksenov** [tarantool/doc#4017]
**Product:** Tarantool
**Since:** 3.0
**Root document:** 
- A new `fiber` section in the [Configuration reference](https://www.tarantool.io/en/doc/latest/reference/configuration/configuration_reference/).

**SME:** @ Totktonada

# Details

Options:
- https://github.com/tarantool/tarantool/blob/f58bfc97c627f1838696697339fb3e443c05767a/src/box/lua/config/instance_config.lua#L702

Related topics:
- https://www.tarantool.io/en/doc/latest/concepts/coop_multitasking/
- https://www.tarantool.io/en/doc/latest/reference/reference_lua/fiber/

**Comment by lenkis** [comment]
Closed with https://github.com/tarantool/doc/commit/60a8acf154fa87c1649e8747b86c3801604c682f
