### ISSUE TITLE
SQL UG: Intro

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#410]
- [ ] Language history in brief
- [ ] SQL dialects: few examples, state there's no pure ANSI SQL (maybe except DB2)
- [ ] Language structure: literals, identifiers, reserved words, comments
- [ ] The basics of SQL type system
- [ ] SQL concepts: a scalar, a row, a relation, a view
- [ ] The 3 ways to look at a relation: a type, a variable and the current value
- [ ] DML. Transforming relation values
- [ ] Why does one need more than one relation? The principles of normalization
- [ ] How does one restore from the normalized state? Introduce JOINs, views.
- [ ] Representing missing info. LEFT & RIGHT + INNER JOIN. NULLs and three-value logic
- [ ] Extracting info from data, creating reports. GROUP BY, HAVING, ORDER BY (aggregates)

Part of https://github.com/tarantool/doc/issues/386

**Comment by pgulutzan** [comment]
There was a discussion about this in 2018. There is documentation of Tarantool/SQL. This is a request for description of SQL in general, that is, not documentation of Tarantool/SQL but of what is in every textbook about databases. I have suggested that it is sufficient that we now have a beginners' guide and a tutorial and a chart about SQL compliance.

**Comment by patiencedaur** [comment]
I don't believe there is a need for a general SQL user guide in the Tarantool documentation. Tarantool SQL specifics are covered in the doc, but we don't need to go deeper---there is plenty of similar information on the web.

I'm cleaning up issues that are more than 3 years old and/or do not relate to LTS versions. The capacity of our doc team is currently very limited.
