### ISSUE TITLE
TCS: Installation guide

### ISSUE THREAD

**Issue by p7nov** [tarantool/doc#4104]
**Product**: Tarantool Column Store 
**PM ref.:** https://www.notion.so/tarantool/Tarantool-Column-Store-3f73c27b39a6495da1aebbd5b7a5c60a?pvs=18
**SME:** @ Galiev-Ruslan , @ spozdeevvk 

## Details

Write a in installation guide for Tarantool Column Store

**Comment by veod32** [comment]
В качестве Installation Guide используется документ по АТЕ + часть по предварительной настройке серверов внесена в Admin Guide TCS
