### ISSUE TITLE
TDB (resp): how to merge TDB (iproto) and TDB(resp) docs

### ISSUE THREAD

**Issue by xuniq** [tarantool/doc#4138]
Epic: https://github.com/tarantool/doc/issues/4127
**Product:** Tarantool DB
Source: https://github.com/tarantool/tdb-redis/tree/master/
**SME:** @ a1div0 @ Galiev-Ruslan @ LeonidVas

# Details

Как работаем с докой в репозитории tdb-redis?
Варианты:
- подтянуть в репозиторий tarantooldb в качестве сабмодуля
- скопировать контент
- отдельный репозиторий?

## Предполагаемая структура

TarantoolDB - мультипротокольная БД
Поддерживаются следующие протоколы:
1) iproto
2) RESP (Redis)

Book I. (iproto) - repo Саши Кленова
Installation
User Guide
Admin Guide
...

Book II. (resp - redis) - репо Лени Васильева
Installation
User Guide
Admin Guide
...

**Comment by veod32** [comment]
Not needed
