### ISSUE TITLE
[doc] [TCF]: implement CI for doc building and publishing

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#4160]
В репозитории разработки продукта TCF https://github.com/tarantool/cluster-federation
настроить CI для:

- [x] сборки документации из исходников в формате .md (плагин myst)
- [x] публикации на тестовый сайт https://docs.d.tarantool.io/ 
- [x] публикации на основной сайт https://www.tarantool.io/ru/clustersfederation/doc/latest- через отдельный пункт основного меню Documentation:
   - Заголовок (общий для англ и русской версии): **Tarantool Clusters Federation**
   - Англ описание: **Cross data center replication (xDCR) module**
   - Русское описание: **Модуль межкластерной репликации данных (xDCR)**
- [x] настройка выгрузки в PDF из ветки master

**Comment by andreyaksenov** [comment]
Draft PR: https://github.com/tarantool/cluster-federation/pull/136
