### ISSUE TITLE
Clarify that the centralized configuration cannot contain the 'config.etcd' and 'config.storage' sections

### ISSUE THREAD

**Issue by andreyaksenov** [tarantool/doc#4190]
**Product:** Tarantool
**Since:** 3.0
**Root document:**
- https://www.tarantool.io/en/doc/latest/reference/configuration/configuration_reference/#config-etcd
- https://www.tarantool.io/en/doc/latest/reference/configuration/configuration_reference/#config-storage

**SME:** @ totktonada

**Comment by Totktonada** [comment]
The title is a bit misleading. It is OK to have `config.context` in the centralized configuration storage. However, that's true that `config.etcd` and `config.storage` in the centrilized storage have no much sense.

See also https://github.com/tarantool/tarantool-ee/issues/644, where the actual check was implemented.

**Comment by andreyaksenov** [comment]
> The title is a bit misleading. It is OK to have `config.context` in the centralized configuration storage. 

Totally agree. Created the issue before understanding the full context. Will fix.
