### ISSUE TITLE
[vshard] Document vshard

### ISSUE THREAD

**Issue by Gerold103** [tarantool/doc#420]
Vshard (https://github.com/tarantool/vshard/) is the new sharding, that strongly differs from https://github.com/tarantool/shard/.
I think, that this is the good place for vshard documentation https://tarantool.io/en/doc/2.0/reference/reference_rock/index.html.

I am open for any questions about vshard architecture, implementation details, options.

**Comment by lenkis** [comment]
Original doc ticket: https://github.com/tarantool/vshard/issues/43
