### ISSUE TITLE
TCS: https support

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#4208]
**Related dev. resources:**
* TCS roadmap: https://www.notion.so/tarantool/TSC-933d545852824f5abefa189881a801a8#add621ee191e438d91bb27bf19638159
* TCS releases Q2-Q3: https://www.notion.so/tarantool/TCS-Q2-Q3-2024-2844bf3db1184e7c939686e2ea0c9362

**Product:** TCS
**Since:** product version
**Audience/target:** who will read it and for what task?
**Root document:** where to add or update documentation
**SME:** @ Galiev-Ruslan 

## Details
- [ ] конфиги для aggregator и scheduler
- [ ] поддержка шифров

Цель: Реализовать поддержку подключения к TCS с шифрованием
- все запросы к сервисам ходят по https
    - внешние запросы ходят по https
    - внутрикластерные запросы ходят по https
        - от шедулера к etcd
        - от шедулера к стораджу

Фича еще в разработке, поэтому прочитать пока негде, user-facing API уже стабилизировалось.

Настройка HTTPS производится в конфигурационных файлах для aggregator и scheduler, набор параметров у них одинаков:

- `transport` — возможные значения `plain` или `tls`, по умолчанию `plain`. В первом случае входящие сообщения будут приниматься по HTTP,  во втором — по HTTPS.
- `tls_cert_file` — путь к TLS-сертификату в формате PEM
- `tls_ca_file` — путь к TLS-сертификату удостоверяющего центра в формате PEM (опционально, если не используется самоподписанный сертификат)
- `tls_key_file` — путь к приватному ключу от сертификата
- `tls_ciphers` — список шифров для версий TLS до 1.2, шифры разделяются `:`
- `tls_ciphersuites` — список шифров для TLS 1.3, шифры разделяются `:`

Если выбран `transport: tls`, то обязательно должны быть указаны `tls_cert_file` и `tls_key_file`. Если иные настройки не указаны, то по умолчанию используются рекомендации по настройке TLS на сервере Mozilla Intermediate v5.

Для scheduler эти параметры указываются на самом верху конфигурационного файла, для aggregator — в разделе `aggregator` каждого инстанса в `instances.yml`.  Если необходимо, позднее могу прислать примеры конфигураций.

Scheduler умеет ходить в aggregator только по HTTP, поэтому, когда он используется, в конфигурации aggregator должен быть указан `transport: plain`.

И aggregator, и scheduler поддерживают шифры ГОСТ TLS. В случае с aggregator никаких дополнительных действий делать не надо, кроме указания шифров в `tls_ciphers/tls_ciphersuites`. В случае с scheduler, пользователь должен установить криптографический движок себе в систему и подключить его в OpenSSL

**Comment by lenkis** [comment]
Closed by https://github.com/tarantool/tcs-doc/commit/cc55219439f7376656f6ed5e48127d460e9ee80e
