### ISSUE TITLE
Update documentation for metrics

### ISSUE THREAD

**Issue by a1div0** [tarantool/doc#4256]
**Related doc issue:** https://github.com/tarantool/doc/issues/3674

**Product:** Tarantool
**Since:** 3.0
**Root document:** 

- Add configuration reference for metrics: [Configuration reference](https://www.tarantool.io/en/doc/latest/reference/configuration/configuration_reference/), a new `metrics` section (https://github.com/tarantool/doc/issues/3674).
- Add a new section in the [Built-in modules reference](https://www.tarantool.io/en/doc/latest/reference/reference_lua/)
- Update [Monitoring](https://www.tarantool.io/ru/doc/latest/book/monitoring/) section: it should include only content related to administration.
- TCM metrics: https://www.tarantool.io/en/doc/latest/reference/tooling/tcm/tcm_cluster_metrics/

**SME:** @ a1div0

# Details

Раздел про метрики подходит для 2.x и не подходит для 3.x. Для 3.х есть отличия. Сейчас этот раздел опубликован и для тройки тоже. А надо раздел переписывать.

Ещё надо будет при переработке не забыть упомянуть, что **metrics**, в отличие от классических built-in модулей, можно ставить отдельно, и внешний **metrics** будет перекрывать внутренний, что можно использовать для того, чтобы на условно "старом" тарантуле обновить только метрики, не дожидаясь полного релизного цикла самого тарантула.

См также: https://github.com/tarantool/metrics/releases/tag/1.2.0, https://github.com/tarantool/grafana-dashboard/releases/tag/3.1.0

Также появилось две новых странички на сайте Grafana с дашбордами для Tarantool 3. Дашборд включает в себя поддержку метрик из новых metrics 1.2.0.

- https://grafana.com/grafana/dashboards/21474-tarantool-3-dashboard/
- https://grafana.com/grafana/dashboards/21484-tarantool-3-dashboard/

Роль `metrics-export-role`: https://github.com/tarantool/metrics-export-role

**Comment by andreyaksenov** [comment]
https://github.com/tarantool/roadmap-internal/issues/331#issuecomment-2220212093
