### ISSUE TITLE
Lack github reference on tarantool.org

### ISSUE THREAD

**Issue by kyukhin** [tarantool/doc#436]
Each and every open-source project has a reference to its source-code repo.

Please, put reference to Tarantool's github repo on tarantool.org web-site.

**Comment by lenkis** [comment]
We have a link to GH at .io, but now it's provided as a "download" option. Here's the click-flow:
1. From "Developers" main page, you click "Community Edition > Download".
2. From "Downloads" page, you click "Packages" (or "Learn more" for your auto-detected OS).
3. From "Packages" page, you click "Building from source" and see a link to GH.

Do you insist it should come at "Developers" main page?

**Comment by Totktonada** [comment]
Just note: some developer-friendly websites have 'fork me on github' badge at the right-top corner, like the following: http://flask.pocoo.org/ . I think there is expectation from developers to have such link in some visible palce of the website.

**Comment by lenkis** [comment]
Done. See icons here: 
https://tarantool.io/en/developers/
