### ISSUE TITLE
[1pt] Launchpad mentions seem to be obsoleted

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#448]
On 1.9 branch.

doc/1.9/dev_guide/c_style_guide.rst
33:please be warned: Launchpad silently deletes posts from non-subscribed members,

doc/1.9/dev_guide/developer_guidelines.rst
21:Patches for bugs should contain a reference to the respective Launchpad bug page or

**Comment by lenkis** [comment]
@kostja Please confirm that info about Launchpad is obsolete.

**Comment by kyukhin** [comment]
It is obsolete. 1.9 is dead and buried.

**Comment by Onvember** [comment]
done in #1692
