### ISSUE TITLE
Use "latest" URI to link to Tarantool sources

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#453]
In 2.0 docs, use some placeholder (e.g. "latest") to denote the latest Tarantool version (in text, URIs, code blocks).

**Comment by lenkis** [comment]
This will save us 50% effort when we create a new doc branch (e.g. 2.1) based on the current "latest" branch (e.g. on 2.0) -- we do not need to replace 2.0 with 2.1 in this case.

However we'll still need to replace all the occurrences of "latest" in the old branch URIs. We need a more unique word, not "latest", to facilitate search/replace for the old branch.

**Comment by lenkis** [comment]
Implemented

**Comment by Totktonada** [comment]
Thanks!
