### ISSUE TITLE
[vshard] Proofread and update readme

### ISSUE THREAD

**Issue by kostja** [tarantool/doc#461]
https://github.com/tarantool/vshard documentation contains spelling errors and missing parts - please read the russian version of the enterprise manual to see which parts. 
Please proofread and complete the docs.

**Comment by Gerold103** [comment]
Both English version on github and Russian version in an Enterprise manual have errors, and deprecated parts. I recommend to send new docs to me on review.

**Comment by lenkis** [comment]
part of https://github.com/tarantool/doc/issues/420

**Comment by lenkis** [comment]
Done. Published:
https://tarantool.io/en/doc/1.9/reference/reference_rock/vshard/index.html
