### ISSUE TITLE
add git to dependencies

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/doc#465]
Here is a dependency list for Debian-like systems
```
apt install -y build-essential cmake coreutils sed \
      libreadline-dev libncurses5-dev libyaml-dev libssl-dev \
      libcurl4-openssl-dev libunwind-dev libicu-dev \
      python python-pip python-setuptools python-dev \
      python-msgpack python-yaml python-argparse python-six python-gevent
```
I was creating docker image and caught the following error durinc cmake:
```
CMake Error at CMakeLists.txt:175 (message):                             
  Unable to retrive version from git or /var/tarantool/docker-build/VERSION                                                                        
  file.
```
Installing `git` fixes the issue.

**Comment by Khatskevich** [comment]
I have been building Tarantool inside of debian:unstable-slim docker image.
I believe it `git` can be simply added to requirement lists for `Debian/Ubuntu`,  `RHEL/CentOS/Fedora`, `FreeBSD`. Not sure about `Mac`.

It is minor though because basically `git` is preinstalled or already installed by user.

**Comment by lenkis** [comment]
@llelik8 please add git to all OS-specific installation scripts here:
https://tarantool.io/en/doc/1.9/dev_guide/building_from_source.html
