### ISSUE TITLE
Document fio.open() numeric permissions

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#471]
Proposed to document the suggestion to use `tonumber('644', 8)` to express permissions as octal numbers.

**Comment by lenkis** [comment]
The idea behind this ticket is that in C the general practice is to set permissions in the octonary notation (like 0755), while in Lua 0755 == 755.
The solution is to use tonumber(). The Lua function fio.open() takes it and passes "as is" to the C function open() .

**Comment by pgulutzan** [comment]
In places where we describe permissions -- for umask and chmod -- we already have examples of tonumber(..., 8). I'll guess that this is merely a request to add another example in fio.open.

**Comment by Totktonada** [comment]
Missed that. Yep, it would be good to have such example in fio.open.

**Comment by pgulutzan** [comment]
Fixed by commit 5f4f8122c411c8399fffe5a3044acf6f5c2f8d31
