### ISSUE TITLE
Add MacOS hints re python 2.7 to build instructions

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#472]
Alec Larson, [Mar 22, 2018, 7:29:33 PM]:
make test is failing, what am I missing?

env: python2: No such file or directory
make[3]: *** [test/CMakeFiles/test] Error 127
make[2]: *** [test/CMakeFiles/test.dir/all] Error 2
make[1]: *** [test/CMakeFiles/test.dir/rule] Error 2
make: *** [test] Error 2

I ran sudo pip install -r test-run/requirements.txt first

python --version returns Python 2.7.10

Alexander Turenko, [Mar 22, 2018, 7:34:06 PM]:
env: python2: No such file or directory

which python2 will give you the answer what is going on.

Alec Larson, [Mar 22, 2018, 7:34:45 PM]:
ok thanks

Alexander Turenko, [Mar 22, 2018, 7:35:24 PM]:
Maybe you need to create symlink python → python2 or python2.7 → python2.

Alec Larson, [Mar 22, 2018, 7:43:08 PM]:
Done. Do I need to use a specific version of Pip? I used pip 9.0.1 which comes with Python 3.5. And make test is now complaining about missing gevent

I think the answer is obvious. heh

Alexander Turenko, [Mar 22, 2018, 7:44:17 PM]:
test-run written on python 2, so you need to create virtualenv like so:

virtualenv -p python2.7 ../env-2.7

pip install gevent
pip install tarantool
pip install pyyaml
pip install six

Alec Larson, [Mar 22, 2018, 7:45:19 PM]:
Oddly, I have no pip for Python 2

Alexander Turenko, [Mar 22, 2018, 7:46:57 PM]:
Inside virtualenv?

Alec Larson, [Mar 22, 2018, 7:47:46 PM]:
I don't have a virtualenv command on macOS High Sierra 10.13, but I'm going to run https://bootstrap.pypa.io/get-pip.py with Python 2.7 and that should give me pip2.7

Alexander Turenko, [Mar 22, 2018, 7:49:02 PM]:
Okay, I don’t know mac os specific things.

Alec Larson, [Mar 22, 2018, 7:56:12 PM]:
MacOS "system integrity protection" made "pip2.7 install -r test-run/requirements.txt" fail.

But "pip2.7 install --user -r test-run/requirements.txt" worked good. Maybe that should go in README.MacOSX

**Comment by Onvember** [comment]
We don't use python2.7 now and this instruction has been updated recently. See https://github.com/tarantool/doc/pull/1989
