### ISSUE TITLE
Tuple:tomap() is not described in the doc

### ISSUE THREAD

**Issue by sharonovd** [tarantool/doc#473]
See https://github.com/tarantool/tarantool/issues/2821

**Comment by Gerold103** [comment]
Please, do not forget to describe the `names_only` option. See https://github.com/tarantool/tarantool/commit/5ad26fe286121607694b3c077d40c3122dbd4b2e

**Comment by Gerold103** [comment]
Please, describe a `names_only` option, as I asked in the comment above.

**Comment by pgulutzan** [comment]
I made a change that affects version 2.0 only: the names_only option.
https://github.com/tarantool/doc/commit/168767de5e0117b504e2287f2f0b5e33786335f9
