### ISSUE TITLE
[vshard] Document new sync_timeout option

### ISSUE THREAD

**Issue by Gerold103** [tarantool/doc#474]
In the patch for this ticket https://github.com/tarantool/vshard/issues/84 a new option was introduced:
`sync_timeout` - this option is a non-negative number, that specifies how long an old master must syncs with slaves before demotion.
(List of all options: https://github.com/tarantool/vshard/blob/master/vshard/cfg.lua#L165)

**Comment by lenkis** [comment]
Already there:

https://tarantool.io/en/doc/1.9/reference/reference_rock/vshard/index.html#cfg-basic-sync-timeout

**Comment by lenkis** [comment]
Closed by commit https://github.com/tarantool/doc/commit/e4d1c1513d96b71bdced00632cef7f30700fe680
