### ISSUE TITLE
Mistakes in socket module documentation

### ISSUE THREAD

**Issue by rosik** [tarantool/doc#475]
https://tarantool.io/en/doc/1.9/reference/reference_lua/socket.html#socket-bind
```socket_object:bind(host[, port])
    Return:
    a socket object on success
```

but
```
tarantool> sock:bind('0.0.0.0', 12345)              
---                                            
- true                                         
...  
```

**Comment by rosik** [comment]
Also:
https://tarantool.io/en/doc/1.9/reference/reference_lua/socket.html#socket-sendto
```
socket_object:sendto(host, port, data)
    Return: the number of bytes sent.
    Return type: number
    Possible errors: on error, returns status, errno, errstr.
```

But

```
tarantool> s:sendto('1.2.3.4.5', 3305, 'x')
---
- null
...
```

**Comment by lenkis** [comment]
Please check with the core team (@kyukhin as the entry-point contact) if this should also apply for 1.7.

**Comment by pgulutzan** [comment]
This also applies for Tarantool version 1.7, that's established by doing the requests with a version-1.7 server.

**Comment by pgulutzan** [comment]
This also applies for Tarantool verson 1.7, as established by running the same requests with that version. There is some question whether simply returning null for sendto() is appropriate, but the description is correct.
