### ISSUE TITLE
space_object:bsize() - not enough details

### ISSUE THREAD

**Issue by sharonovd** [tarantool/doc#483]
Right now doc does not give any details re space_object :bsize() method.

Most common question is - do it count indices, or only raw tuples? (answer: only tuples).

**Comment by aleclarson** [comment]
It should also clarify if `bsize` is computed on-demand or stored, which I assume is the latter.

**Comment by pgulutzan** [comment]
Yes, I believe if you look (for example) in memtx_space.c at the memtx_update_bsize statements, you might see that memtx_space->bsize is updated by the difference between old and new tuple sizes, and that's what memtx_space_bsize returns. I'm not enthusiastic about including an implementation detail in the manual -- it can become false without warning. But okay, we'll say bsize is stored.
