### ISSUE TITLE
Should contributors guidelines be splitted by tarantool versions?

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#485]
Consider 'Contributors guidelines' section: [1]. It contains:

* C API reference.
* Internals.
* Build and contribute.
* Guidelines.

The first two seems to be dependent on a tarantool version, but the last two are not. I think it would be good to eliminate unnecessary copies of documents of the last two sections.

[1]: https://tarantool.io/en/doc/2.0/dev_guide/index.html

**Comment by lenkis** [comment]
"Build and contribute" includes version-specific info for both tarantool and doc (branch names, paths).
So, this question is valid only for "Guidelines".

We don't maintain version-agnostic documentation now: the current approach is to generate a complete docset for each version. Taking out a piece (particularly, the guidelines) means adding a new location where the main doc should link to. This adds extra navigation/linking/publication efforts, while keeping 3-4 copies of guidelines for 1.7-2.0 versions only costs us a few auto merges in case of changes. I don't feel the split is worth that.

**Comment by Totktonada** [comment]
Hmm, I think it was filed because I saw some inconsistence btw versions in 'developer guidelines'. Maybe it was my mistake, now it looks good. If you consider current maintenance effort small enough, I don’t mind. So, closing the issue. Thanks!
