### ISSUE TITLE
Installation instructions for Ubuntu are not straightforward

### ISSUE THREAD

**Issue by isopov** [tarantool/doc#492]
At https://tarantool.io/en/download/os-installation/1.9/ubuntu.html there are following lines:
```
sudo rm -f /etc/apt/sources.list.d/*tarantool*.list
echo "deb http://download.tarantool.org/tarantool/1.9/ubuntu/ xenial main" > /etc/apt/sources.list.d/tarantool_1_9.list
```
From the first line it seems that we have not rights for /etc/ folder and use sudo to access it. But second line  does not use sudo:
```
$ echo "deb http://download.tarantool.org/tarantool/1.9/ubuntu/ xenial main" > /etc/apt/sources.list.d/tarantool_1_9.list
bash: /etc/apt/sources.list.d/tarantool_1_9.list: Permission denied
```
This problem can be fixed like:
```
echo "deb http://download.tarantool.org/tarantool/1.9/ubuntu/ xenial main" | sudo tee /etc/apt/sources.list.d/tarantool_1_9.list
```

**Comment by Totktonada** [comment]
Now I don’t see the fix: https://tarantool.io/en/download/os-installation/1.9/ubuntu/

**Comment by lenkis** [comment]
This was a build/deploy bug at our website. The update is now present both in source and at website.
