### ISSUE TITLE
Wrong documentation for msgpuck.decode return

### ISSUE THREAD

**Issue by rosik** [tarantool/doc#494]
Documentation says:
https://tarantool.io/en/doc/1.9/reference/reference_lua/msgpack.html#msgpack-decode
```
Return:
   ...
   the number of bytes that were decoded.
```

But

``` console
tarantool> require('msgpack').decode('\xc0') -- nil
---
- null
- 2
...
```

> Eugine Blikh, [17.04.18 13:12]
> [In reply to Eugene Leonovich]
> отставить панику, возвращается новая позиция, по которой должен проходить декод
> 
> Eugine Blikh, [17.04.18 13:13]
> там возвращается кол-во распарсеных байт + 1
> 
> Eugine Blikh, [17.04.18 13:14]
> все становится на свои места, когда вспоминаем что в луа отсчет идет с 1 🙂
>

**Comment by lenkis** [comment]
msgpack.decode() returns the new position to resume decoding from, which is the **total** number of parsed bytes + 1 byte. The + 1 byte is due to the fact that Lua is 1-based rather than 0-based.
