### ISSUE TITLE
Explain what happens when 2+ tuples are "equal" within an index

### ISSUE THREAD

**Issue by aleclarson** [tarantool/doc#504]
[This section](https://tarantool.io/en/doc/1.7/book/box/box_index.html#overview) or [this section](https://tarantool.io/en/doc/1.7/book/box/data_model.html#index) is probably a good spot to explain what happens when 2+ tuples exist where their indexed parts are equal.

> If two or more tuples have the same values for their indexed parts, the order is undefined. You may choose to use a "created_at" field as the last indexed part if you want to ensure a predictable order. The "created_at" field would need to be set manually.

**Comment by pgulutzan** [comment]
It's undocumented, but is this advice actually good? Try this:
box.space.t:drop()
box.schema.space.create('t',{engine='vinyl'})
box.space.t:create_index('i1')
box.space.t:create_index('i2',{unique=false,parts={2,'scalar'}})
box.space.t:insert{1,'A'}
box.space.t:insert{77,'A'}
box.space.t:insert{11,'B'}
box.space.t:insert{54,''}
box.space.t:insert{2,'A'}
box.space.t:insert{2000,'A'}
box.space.t:insert{1000,'A'}
box.space.t:insert{3000,'A'}
box.space.t.index.i2:select()
Notice that, wherever the i2 keys are equal, they are in order: by primary key. In other words, there is a predictable order, and it doesn't require a "created_at" field. Perhaps we should document that fact instead?

**Comment by aleclarson** [comment]
@pgulutzan Very interesting. Yes, that is critical knowledge when using indexes.

> For non-unique indexes, two or more tuples may have equal values when comparing their indexed fields. In that scenario, the "equal" tuples are ordered by their primary keys, which guarantees a consistent and predictable order.

**Comment by pgulutzan** [comment]
Nobody has complained, so okay, we mention that there can be a secondary primary-key order.
