### ISSUE TITLE
modules index needs update

### ISSUE THREAD

**Issue by alg1973** [tarantool/doc#506]
Some modules should be removed.
Some modules should be added.
vshard module should be added.
Every module section should contain link to documentation.
Link to the repository should be added to some text from the description. Link from the small picture on the right side  is not enough. 

Sentence "Want your module listed here?" should be corrected.

https://tarantool.io/en/download/rocks.html

**Comment by lenkis** [comment]
Fixed by commit https://github.com/tarantool/doc/commit/e0af007776b65f426ecadcb485efca3297007b15
