### ISSUE TITLE
Tarantool manual section about connectors needs restructuring 

### ISSUE THREAD

**Issue by alg1973** [tarantool/doc#507]
Tarantool docs connectors section should be in consistent state for every section:

Every section should have similar structure:
1.That is it 
2 Download and install
3 download and build from sources
4 Good example
5 Further  reading (link to documentation)

Every item should contain appropriate links (Download, repo, etc).

https://tarantool.io/en/doc/1.9/book/connectors/index.html

**Comment by lenkis** [comment]
@veod32 please help make this part look neat

ask @artur-barsegyan to help with review as an open-source advocate

**Comment by artur-barsegyan** [comment]
@lenkis after the brief discussion with @veod32 we need to reassign this task on somebody else. Let's discuss our priorities on Monday?

**Comment by patiencedaur** [comment]
It is [done](https://www.tarantool.io/en/doc/latest/book/connectors/). Closing this.
