### ISSUE TITLE
Update rocks page

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#519]
Check against tarantool/rock, some modules are missing at the site.

**Comment by lenkis** [comment]
+ see https://github.com/tarantool/doc/issues/506

**Comment by LapaevPavel** [comment]
Fixes are implemented in https://github.com/tarantool/doc/issues/506

This ticket is to be closed when 506 is closed.

**Comment by lenkis** [comment]
Fixed by commit https://github.com/tarantool/doc/commit/e0af007776b65f426ecadcb485efca3297007b15
