### ISSUE TITLE
Add Ubuntu Artful and Bionic to the installation instructions

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#536]
https://tarantool.io/en/download/os-installation/1.9/ubuntu.html

The instructions will be quite similar to other ones, but having they explicitly allows copy-paste.

Alternatively we can (I think) squash it into the one instruction by replacing precise / trusty / wily / xenial / artful / bionic with `${release}` (which is already defined in the instructions as `lsb_release -c -s` result).

**Comment by kostja** [comment]
@LapaevPavel please get in touch with me or @Totktonada about this issue. I have hit it myself recently.

**Comment by lenkis** [comment]
Done.
