### ISSUE TITLE
[vshard] Vshard.router.route wrong retval type

### ISSUE THREAD

**Issue by Gerold103** [tarantool/doc#544]
Here https://tarantool.io/en/doc/1.9/reference/reference_rock/vshard/index.html it is wrote that `route()` returns netbox object, but it is not correct. It returns replicaset object, that has three methods: `call, callro, callrw`.

**Comment by lenkis** [comment]
Closed by commit https://github.com/tarantool/doc/commit/e4d1c1513d96b71bdced00632cef7f30700fe680
