### ISSUE TITLE
Connectors - protocol

### ISSUE THREAD

**Issue by eaglemoor** [tarantool/doc#548]
In this page https://tarantool.io/en/doc/1.9/book/connectors/index.html#protocol we have some details about iproto, but it's not not enough. Please add in this page link to more powerful details page https://tarantool.io/en/doc/1.9/dev_guide/internals_index.html#tarantool-s-binary-protocol

**Comment by LapaevPavel** [comment]
Closing the issue. The link to the target page is already present on the source page.
