### ISSUE TITLE
http.client documentation bugs 

### ISSUE THREAD

**Issue by kyukhin** [tarantool/doc#559]
Pasto of https://github.com/tarantool/tarantool/issues/3286

https://tarantool.io/en/doc/1.9/reference/reference_lua/http.html?highlight=http%20client#module-http.client doesn't contain a lot of details. the docs are very sketchy. @hypersolid has more info

**Comment by Onvember** [comment]
@hypersolid please give more information about what to add or change

**Comment by Totktonada** [comment]
As we discussed in #975, one of tasks belong here is to provide description of `cookies` return value of `:request()` method.
