### ISSUE TITLE
Document box.NULL

### ISSUE THREAD

**Issue by Gerold103** [tarantool/doc#561]
I have been surprised but our documentation still has no a description of such a vital thing as `box.NULL`. For many users it is a big problem to distinguish `box.NULL` from Lua `nil` and how to use them to insert into a space, to check a condition like `if value == nil` or `if value` or `value ~=/== box.NULL`.

Here I was not able to find anything: https://tarantool.io/ru/doc/1.9/search/?q=box.NULL

**Comment by lenkis** [comment]
This was part of a cumulative update (pending since April) on nulls and field formats, which I was drafting in spring. To be finalized now.

**Comment by Totktonada** [comment]
Let's update Lua style guide with proper recommendations for different usual cases.
