### ISSUE TITLE
Fix ToC links in net.box reference

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#571]
https://tarantool.io/en/doc/2.0/reference/reference_lua/net_box/

Some links in ToC references the another page ( say, https://tarantool.io/en/doc/2.0/reference/reference_lua/net_box_1.6/#conn-select ) that let browser to reload the page when a user navigating using the ToC.

I don’t check other reference pages, maybe it is worth to check them all.

**Comment by lenkis** [comment]
The bug is not in the doc, it's a problem caused by incorrect site deployment. Delegated to LT.
