### ISSUE TITLE
Mobile version: bugs

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#58]
- [x] Fonts in body text varies (e.g. text in lists, both bulleted and numbered, is considerably larger than elsewhere on the page. Example:
       https://tarantool.org/doc/book/box/atomic.html
       http://staging.tarantool.org/doc/book/box/index.html
- [ ] Some (too multi-column?) tables are split row-wise into separate tables. Examples:
       http://staging.tarantool.org/doc/book/box/authentication.html#users-and-the-user-space
       http://staging.tarantool.org/doc/book/box/index.html#data-types
       http://staging.tarantool.org/doc/book/box/box_schema.html
       https://tarantool.org/en/doc/book/connectors/index.html#packet-example
- [x] Vertical paddings in paragraphs are too large, esp. in the following places:
    - after code snippets
    - inside note/warning admonitions
    - before subsection headings
    - between q&a sections in faqs
    - in function descriptions (after "Return" and "Parameters"), e.g.:
       http://staging.tarantool.org/doc/book/box/triggers.html#lua-function.box.session.on_disconnect
    - in popup toc, after the final item in every expanded list

**Comment by mejedi** [comment]
*Some tables are split row-wise into separate tables.*

Looks like a feature to me. There's absolutely no way such a table can fit a tiny screen, hence laying it out in this way is the only reasonable option.

**Comment by bigbes** [comment]
Yes, it's a feature.

**Comment by lenkis** [comment]
Well, this feature makes many tables absolutely unusable/unreadable.

Maybe, we could put such tables inside scrollable containers, like we do for code snippets?

**Comment by lenkis** [comment]
Re tables: agreed to make 2 containers for tables, scrollable and not.
