### ISSUE TITLE
Add tarantoolctl rocks pack/unpack

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#585]
`tarantoolctl rocks pack/unpack` is now in 1.10.

https://github.com/tarantool/tarantool/pull/3586

Konstantin Nazarov, [31.07.18 16:51]
tarantoolctl rocks install packagename version

Konstantin Nazarov, [31.07.18 16:52]
tarantoolctl rocks pack packagename version

Konstantin Nazarov, [31.07.18 16:52]
проверил - это работает

Konstantin Nazarov, [31.07.18 16:52]
$ tarantoolctl rocks install luarapidxml-scm-1.macosx-x86_64.rock 
luarapidxml scm-1 is now installed in /Users/knazarov/dev/tarantool/luarapidxml/.rocks (license: BSD2)

**Comment by sofiayem** [comment]
Closed by 
https://github.com/tarantool/doc/pull/644
