### ISSUE TITLE
tarantool.io/en/doc: wrong link or invalid page?

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#588]
https://github.com/tarantool/migrate#see-also links to https://tarantool.io/en/doc/ , which looks as on the screenshoot below.

![image](https://user-images.githubusercontent.com/92749/43667631-87443e3e-9781-11e8-9405-71c3ef72e3ca.png)

I think we need to fix the link or the page.

BTW, 'Tests' link can be changes from bigbes/migrate to tarantool/migrate (however it redirects properly).

**Comment by lenkis** [comment]
Link target fixed.
Created an issue to update/proofread the readme at tarantool/migrate:
https://github.com/tarantool/doc/issues/603
