### ISSUE TITLE
Strange description of update in on-line docs

### ISSUE THREAD

**Issue by kyukhin** [tarantool/doc#593]
Here [1]
It is stated:
```
In the update: 
box.space.tester:update(999, {{'=', 2, 'B'}}) 
The first argument is tester, that is, the affected space is tester. The second argument is 999, that is, the affected tuple is identified by primary key value = 999. The third argument is =, that is, there is one operation — assignment to a field. The fourth argument is 2, that is, the affected field is field[2]. The fifth argument is 'B', that is, field[2] contents change to 'B'. Therefore, after this update, field[1] = 999 and field[2] = 'B'.
```

But at first look first argument is 999, not tester.
My misunderstanding? If not - need to fix around the doc.

[1] - https://tarantool.io/en/doc/1.9/book/box/box_space/#box-space-update

**Comment by Totktonada** [comment]
`t:func(arg1, arg2)` is the alias for `t.func(t, arg1, arg2)`. So it should not be confusing for lua programmers.

**Comment by lenkis** [comment]
@kyukhin ok to close after Sasha's comment?

**Comment by lenkis** [comment]
@veod32 please double-check with the server team

**Comment by kyukhin** [comment]
Sure, closing.
