### ISSUE TITLE
Doc to 1.7 specifies presence of 'fio.mktree'

### ISSUE THREAD

**Issue by VifleY** [tarantool/doc#599]
Actually fio.mktree() is specified in docs on 1.7 (http://www.tarantool.io:8090/ru/doc/1.7/reference/reference_lua/fio/#fio-mktree)
But I am still unable to call it (using official docker image 1.7.6):

```
/opt/tarantool # tarantool
Tarantool 1.7.6-0-g7b2945d6c
type 'help' for interactive help
tarantool> require('fio').mktree
---
- null
...
```
Is it my setup problem or documentation?
Can make pull request if needed

**Comment by lenkis** [comment]
@kyukhin what's the youngest version where we intend to deliver fix.mktree()?

**Comment by Totktonada** [comment]
It was commited in 1.7.7-27-gd7135403a.

**Comment by kyukhin** [comment]
I removed `need feedback` label. However I guess we do not support 1.7 anymore and this can be simply closed.
