### ISSUE TITLE
Fix markup in functions to include them in search results

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#6]
Functions that are documented without '.. function::' directive are not included in search results.

E.g. On this page, here are 2 functions with "base64" in their names:
http://tarantool.org/doc/reference/digest.html?highlight=base64
But they are not retrieved when you try to find them with "Search the manual = base64":
http://tarantool.org/doc/search.html?q=base64&check_keywords=yes&area=default

Function descriptions should be revised to make sure that they all are documented using '.. function::'.

**Comment by bigbes** [comment]
Must be fixed by now
