### ISSUE TITLE
Confusing example in `Transaction control` chapter

### ISSUE THREAD

**Issue by kyukhin** [tarantool/doc#601]
It contains:
```
	Threads, fibers and yields
How does Tarantool process a basic operation? As an example, let’s take this query:

tarantool> box.space.tester:update({3}, {{'=', 2, 'size'}, {'=', 3, 0}})
This is equivalent to an SQL statement like:

UPDATE tester SET "field[2]" = 'size', "field[3]" = 0 WHERE "field[1]" = 3
```

This is unclear, why PK  is `field[1]`.

There's some explanation later in text, but this confusing at first look.

**Comment by lenkis** [comment]
Please revise the story flow here:
https://www.tarantool.io/en/doc/1.7/book/box/atomic/#threads-fibers-and-yields

**Comment by sofiayem** [comment]
Closed by 
https://github.com/tarantool/doc/pull/653
