### ISSUE TITLE
Describe explicit create/drop privileges in doc

### ISSUE THREAD

**Issue by sharonovd** [tarantool/doc#605]
Konstantin Osipov, [23.08.18 18:48]
box.schema.user.grant('username', 'create', 'function')

This functionality is introduced in 1.10, but not described.

Also, examples from here https://www.tarantool.io/en/doc/2.0/book/box/authentication/ 
do not work anymore.

**Comment by pgulutzan** [comment]
We now have corrected description for 'create' and 'alter' in that section. For 'drop' we continue to say that it exists but has no effect (because the people who can drop an object are the owner and admin).
