### ISSUE TITLE
Implement doc start page based on sphinx

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#61]
The new design of tarantool.org/doc.html is currently implemented similarly to download.html. 
Please re-implement it using sphinx (to enable automatic toc update, avoid incorrect linking from doc header and gets the doc link properly updated at /try).

**Comment by kostja** [comment]
Why not merge doc/index.html and doc/doc.html along the way? What is the reason for two different pages?

**Comment by bigbes** [comment]
Pushed
