### ISSUE TITLE
Cannot move from Russian to English replication manual

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#614]
I'm push 'en' link on [1], the page reloads to the Russian version again.

[1]: https://www.tarantool.io/ru/doc/1.9/book/replication/repl_remove_instances/

**Comment by vpotseluyko** [comment]
там html формочка которая должна субмитить на какой-то служебный адрес. Этого не происходит с safari & firefox, в хроме все ок

**Comment by lenkis** [comment]
Fixed now. Thanks for reporting & troubleshooting!
