### ISSUE TITLE
Russian section of documentation contains russian headers and english texts

### ISSUE THREAD

**Issue by aensidhe** [tarantool/doc#63]
[Example](https://tarantool.org/doc/ru/book/box/box_session.html)

I tested it in incognito mode - same result. Windows 10, stable chrome.

![image](https://cloud.githubusercontent.com/assets/3948027/18845057/c2933378-8428-11e6-8444-92e85219b64e.png)

**Comment by bigbes** [comment]
Well, it's ok, documentation translation is still in progress.

**Comment by bigbes** [comment]
@lenkis can you confirm it?

**Comment by aensidhe** [comment]
@bigbes please add some disclaimer about it into pages, because otherwise lots of users will report this issue to you.
