### ISSUE TITLE
Document 2x buckets for the future 2.1 beta release tarballs & packages

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#647]
We don't push more to 2.0 buckets (and don't have 2.0 branch on github). Now we push tarballs and packages from 2.1 branch into 2x bucket (because 2.1 will be beta release). Stable releases like 2.2 will have its own 2.2 bucket.

https://packagecloud.io/tarantool/2x
https://download.tarantool.org/tarantool/2x/src/

**Comment by lenkis** [comment]
To deploy in late November.

**Comment by Totktonada** [comment]
We awaiting for saturation the bucket with packages of tarantool itself and modules before actually switch 2.0 to 2x.

**Comment by Totktonada** [comment]
It is not more blocked. Please, proceed with it on this week, because it is planned to cut off 2.1 beta release soon.

**Comment by lenkis** [comment]
Done: linke from "tarball" here https://www.tarantool.io/en/download/os-installation/2.2/building-from-source/ goes to http://download.tarantool.org/tarantool/2x/src/

**Comment by Totktonada** [comment]
BTW, https://download.tarantool.org/tarantool/2.1/src/ aliases https://download.tarantool.org/tarantool/2x/src/ now (the same for rpm/deb repositories).
