### ISSUE TITLE
[socket] Seems that `read` api contain mistake

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/doc#657]
https://tarantool.io/en/doc/1.10/reference/reference_lua/socket/#lua-function.socket_object.read

```
socket_object:read(limit[, timeout])
socket_object:read(delimiter[, timeout])
socket_object:read({limit=limit}[, timeout])
socket_object:read({delimiter=delimiter}[, timeout])
socket_object:read({limit=limit, delimiter=delimiter}[, timeout])
```

source of read api  usage

https://github.com/tarantool/tarantool/blob/2.1/src/lua/socket.lua#L721

`limit` have to be replaced with `chunk`

**Comment by Totktonada** [comment]
I don't see any reason to retain mistakes in 1.9 documentation. @lenkis, I think this would be good to cherry-pick the fix to 1.9 too.
