### ISSUE TITLE
Grant role syntax is not properly described

### ISSUE THREAD

**Issue by sharonovd** [tarantool/doc#670]
All doc examples regarding box.schema.user.gran('My_user', 'my_role') syntax do not contain info how I should pass the 'if_not_exists' option. I had to deduce it from source code:

box.schema.user.grant('replicator', 'replication',nil, nil, {if_not_exists=true})

**Comment by pgulutzan** [comment]
@sharonovd The box.schema.user.grant syntax is described here:
https://tarantool.io/en/doc/2.1/book/box/box_schema/#box-schema-user-grant
It does describe {if_not_exists=true}.
I don't understand, what do you think is wrong?

**Comment by sharonovd** [comment]
And in example on https://tarantool.io/en/doc/1.10/book/box/box_schema/#box-schema-user-grant as well:

```box.schema.user.grant('Lena', 'Accountant', nil, nil {if_not_exists=true})``` => ```box.schema.user.grant('Lena', 'Accountant')```

**Comment by pgulutzan** [comment]
After getting advice from Konstantin Osipov, I changed so that the manual does not recommend granting 'execute' on a role and removed that syntax in the first example that sharonovd refers to. but we will use the shortest way in both examples.
