### ISSUE TITLE
Not all Linux flags are supported in fio.open

### ISSUE THREAD

**Issue by olegrok** [tarantool/doc#671]
https://tarantool.io/ru/doc/2.1/reference/reference_lua/fio/#lua-function.fio.open

In documentation:
```
* O_LARGEFILE (allow 64-bit file offsets),
```
```
Tarantool 2.1.1-21-ga693de508
type 'help' for interactive help
tarantool> fio = require('fio')
---
...

tarantool> fio.open('123.txt', { 'O_CREAT', 'O_LARGEFILE' })
---
- error: 'builtin/fio.lua:182: Unknown flag: O_LARGEFILE'
...
```

**Comment by Totktonada** [comment]
https://github.com/tarantool/tarantool/blob/071918421f48bd2520ddcf591adf8bb992ca1dc4/src/lua/fio.c#L783

**Comment by olegrok** [comment]
Ok. I use MacOS and according `man 2 open` it doesn't support `O_LARGEFILE`. So, I think that there will have to be some notes in documentation that some of this flag are supported only in Linux.
