### ISSUE TITLE
Add docker run command to download instruction

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#673]
https://tarantool.io/en/download/os-installation/1.10/docker-hub/

Here we have just link to docker hub. But I think it would be convenient to provide copy-pasteable command to run tarantool in docker: `docker run -it tarantool/tarantool:1.10.2`. The same for another versions.

tarantool/tarantool:2.1 is blocked by https://github.com/tarantool/docker/issues/74 for now.

**Comment by Totktonada** [comment]
Now it is `docker pull tarantool/tarantool:2.5`, but I think it should be `docker run`, IMHO.

**Comment by Onvember** [comment]
done
