### ISSUE TITLE
Convert SQL reference to ReST markup

### ISSUE THREAD

**Issue by llelik8** [tarantool/doc#677]

**Comment by pgulutzan** [comment]
I think this is obsolete. The SQL Reference was converted to .rst files when it was moved from docs.google.com to the official manual. Does anybody object that this issue should remain open? If not, I hope to close it in a week or two.

**Comment by pgulutzan** [comment]
Nobody objected that this issue should remain open, so, due to thinking it is obsolete, I am closing it now.
