### ISSUE TITLE
Wrong SQL_INFO and ROW_COUNT codes

### ISSUE THREAD

**Issue by rybakit** [tarantool/doc#697]
On https://tarantool.io/en/doc/2.1/dev_guide/internals/sql_protocol/ stated that `SQL_INFO = 0x43` and `ROW_COUT = 0x44`, but it's no longer the case since [this change](https://github.com/tarantool/tarantool/commit/785ee69dd4274e4cd73e0d25fe07704bd3b711b9).

Related (closed) ticket: https://github.com/tarantool/doc/issues/479

**Comment by ImeevMA** [comment]
In addition to the SQL_INFO_ROW_COUNT code mentioned above, the new SQL_INFO_AUTOINCREMENT_IDS code appeared after issue [2618](https://github.com/tarantool/tarantool/issues/2618) was closed by this [commit](https://github.com/tarantool/tarantool/commit/ef67de414f5dc21a4b1c01d5a068e3a7604a6f17)

**Comment by pgulutzan** [comment]
Okay, although it's odd to have a name SQL_INFO_AUTOINCREMENT_IDS when the SQL keyword is AUTOINCREMENT.

**Comment by Totktonada** [comment]
Just for the record: SQL_INFO was changed from 0x43 to 0x42 [here](https://github.com/tarantool/tarantool/commit/680b47a49ff17afe9e5271705964e1d69611b87e).
