### ISSUE TITLE
Propose fixes for http.client keepalive options description

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#700]
> * `keepalive_idle` - delay, in seconds, that the operating system will wait while the connection is idle before sending keepalive probes. See also [CURLOPT_TCP_KEEPALIVE](https://curl.haxx.se/libcurl/c/CURLOPT_TCP_KEEPALIVE.html)
> * `keepalive_interval` - the interval, in seconds, that the operating system will wait between sending keepalive probes. See also [CURLOPT_TCP_KEEPALIVE](https://curl.haxx.se/libcurl/c/CURLOPT_TCP_KEEPALIVE.html)

https://tarantool.io/en/doc/1.10/reference/reference_lua/http/

`keepalive_idle` sets [CURLOPT_TCP_KEEPIDLE](https://curl.haxx.se/libcurl/c/CURLOPT_TCP_KEEPIDLE.html), `keepalive_interval` sets [CURLOPT_TCP_KEEPINTVL](https://curl.haxx.se/libcurl/c/CURLOPT_TCP_KEEPINTVL.html). I think that these curl options should be linked from the documentation of our options instead of CURLOPT_TCP_KEEPALIVE.

It also would be good to mention that when these options set, we also set http keepalive headers: `Connection: Keep-Alive` and `Keep-Alive: timeout=<keepalive_idle>`. We send `Connection: close` instead by default (when these optioans are not set).

**Comment by pgulutzan** [comment]
I did not understand the sentence beginning "It would also be good ..." but assumed other readers will understand so I simply copied it.

**Comment by Totktonada** [comment]
Minor correction: the http headers are set when both keepalive_idle and keepalive_inverval options are set (as I see by the [code][1]).

[1]: https://github.com/tarantool/tarantool/blob/6666db8d5b5736abcfc5b71d1f7e1ac3dd34e730/src/httpc.c#L222-L235

**Comment by pgulutzan** [comment]
Okay. I am assuming that there will be no need for more change when https://github.com/tarantool/tarantool/issues/3955 is done.

**Comment by Totktonada** [comment]
I think that there will be another issue re documentation after https://github.com/tarantool/tarantool/issues/3955
