### ISSUE TITLE
Describe jip.p profiling tool 

### ISSUE THREAD

**Issue by rosik** [tarantool/doc#716]
LuaJIT has built-in module `jit.p`, which can be used in addition to [gperftools](https://tarantool.io/en/doc/1.10/book/admin/server_introspection/#gperftools). It would be nice to mention it in documentaion.

http://www.luatex.org/svn/trunk/source/libs/luajit/LuaJIT-src/doc/ext_profiler.html

**Comment by lenkis** [comment]
Belongs here: https://tarantool.io/en/doc/1.10/book/admin/server_introspection/#profiling-performance-issues

**Comment by pgulutzan** [comment]
There is a sentence earlier in the chapter: "Most of these tools – except fiber.info() – are intended for generic GNU/Linux distributions, but not FreeBSD or Mac OS." I did not change that sentence.
