### ISSUE TITLE
reader should be able to suggest any change 

### ISSUE THREAD

**Issue by nekufa** [tarantool/doc#732]
It will be good, if we can provide readers to fix documentation. 

Usually, it is implemented this way - user selects text part and press ctrl+enter (we can show tooltip on selection) and after that a popup with form is displayed. Form should contain selected text and textarea where user can suggest an improvement.
For ui example you can see jquery.textmistake plugin

p.s. In addition, backend can create pull request to documentation repository using github api.
More powerful tool can show any other proposals for selected text area with links to github, so reader can vote for pull request accept.

**Comment by lenkis** [comment]
We have this functionality our test env right now. To be published in the near future, when we resolve usability bugs.

**Comment by Totktonada** [comment]
I'll start with really simple frontend + backend and will see what will going on :)

**Comment by Totktonada** [comment]
Done. Select a text and hit Ctrl+Enter (or Cmd+Enter). On a touchscreen device a button will appear after selecting a text.
