### ISSUE TITLE
[2pt] Use standard epel-release package on CentOS 7

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#738]
Now the installation instruction for CentOS 7 provides the following methods to install the EPEL repository:

```
# Enable EPEL repository
yum -y install http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
sed 's/enabled=.*/enabled=1/g' -i /etc/yum.repos.d/epel.repo
```

At least on CentOS 7.5 this can be done just as `yum install epel-release`. Don't sure about CentOS 6, need to check.

**Comment by lenkis** [comment]
Please double-check with Sasha and update the download instructions at tarantool.io.
Page sources are in gitlab, @artembo will help to locate them.

**Comment by Onvember** [comment]
Done
