### ISSUE TITLE
Poor "table" documentation

### ISSUE THREAD

**Issue by olegrok** [tarantool/doc#746]
Our doc https://tarantool.io/ru/doc/1.10/reference/reference_lua/table/ contains only description of table.deepcopy function and link to official lua documentation. However Tarantool use LuaJIT that has extensions: table.new and table.clear. I suggest to describe this useful functions that are faster than standard table.insert

**Comment by pgulutzan** [comment]
I have made that section less "poor" by adding more links to other documents, and adding a few words about most of the functions. I am reluctant to add a statement that a function which we don't control will be faster, unless I can point to proof.

**Comment by olegrok** [comment]
I found small piece of information about table.new - https://github.com/LuaJIT/LuaJIT/blob/f0e865dd4861520258299d0f2a56491bd9d602e1/doc/extensions.html#L218

```
This creates a pre-sized table, just like
the C API equivalent lua_createtable(). This is useful for big
tables if the final table size is known and automatic table resizing is
too expensive.
```
