### ISSUE TITLE
Update procedure of publishing a minor release

### ISSUE THREAD

**Issue by kyukhin** [tarantool/doc#749]
subj

**Comment by lenkis** [comment]
@kyukhin please provide details

**Comment by kyukhin** [comment]
We have a google doc with algorithm. I can provide it in private. Let's simply publish it.

**Comment by Totktonada** [comment]
The [existing](https://www.tarantool.io/en/doc/2.5/dev_guide/release_management/#how-to-make-a-minor-release) instruction looks outdated.

**Comment by Totktonada** [comment]
I would polish our internal instructions a bit more privately (during several release cycles). I propose to drop 'How to make a minor release' section from the website for now.
