### ISSUE TITLE
Document new box.execute() method

### ISSUE THREAD

**Issue by kyukhin** [tarantool/doc#751]
We've replaced box.sql.execute() w/ box.execute().

Need to update documentation.

**Comment by lenkis** [comment]
@pgulutzan Please add `box.execute()` to box reference, too.

**Comment by pgulutzan** [comment]
Consider: box.rollback, box.on_rollback, box.upgrade,
box.snapshot, box.on_commit, and probably a few others.

These functions are not closely related to each other,
the fact that they were dumped in 'box' doesn't mean anything.
So until now we have avoided putting them in the 'box' chapter,
instead we describe within appropriate sections.

Why should box.execute be different?
