### ISSUE TITLE
wal_mode no longer a dynamic parameter 

### ISSUE THREAD

**Issue by baltazor5000** [tarantool/doc#758]
>Dynamic: yes

But I can not change this parameter dynamically

box.cfg.wal_mode='none' - change parameter, but log still writes.

or

box.cfg{wal_mode='none'}
---
- error: Can't set option 'wal_mode' dynamically
...

get error.

**Comment by lenkis** [comment]
it's a bug in the manual. This parameter has never been dynamic. Sorry for confusion.
