### ISSUE TITLE
incorrect reference to vinyl_timeout from index_object::compact()

### ISSUE THREAD

**Issue by kostja** [tarantool/doc#765]
https://www.tarantool.io/en/doc/2.1/book/box/box_index/#lua-function.index_object.compact says:

There is a scheduler for reclaiming space automatically based on the timeout configuration parameter.

Indeed there is a scheduler for reclaiming space, but it is not bsaed on the timeout configuration parameter. The constraint vinyl scheduler is driven by are lsm shape (level_size_ratio, run_count_per_level), space amplification (i.e. the total amount of garbage), but not query timeout, which vinyl_timeout essentially is for.

**Comment by pgulutzan** [comment]
Re the words "lsm shape (level_size_ratio, run_count_per_level)" -- although we mention level_size_ratio elsewhere in the manual, it does not exist and vinyl_level_size_ratio does not exist. So I will be more vague, I will mention lsm shape and amplification and then point to the vinyl-related section.
