### ISSUE TITLE
Automatically replace -- with &ndash;

### ISSUE THREAD

**Issue by mejedi** [tarantool/doc#77]
Automatically replace `--`, `"` and `...`  with —, typographical quotes and &hellip;

**Comment by lenkis** [comment]
Works bad for source code quoted in refs, like here:
https://tarantool.org/doc/reference/configuration/index.html#hot-standby

On replace, we get engine = ‘vinyl’ displayed in inverted quotes. I would disable quotes conversion for the manual altogether (but keep other replacement rules).

**Comment by bigbes** [comment]
I don't get it, it's problem in inline source code directives?

**Comment by lenkis** [comment]
Agreed to take it as normal behavior: text on white background is not intended for copy-paste as it's not source code. Leaving replacement rules as they are.
