### ISSUE TITLE
console=true is deprecated for net.box.connect

### ISSUE THREAD

**Issue by printercu** [tarantool/doc#770]
https://www.tarantool.io/en/doc/2.1/reference/reference_lua/net_box/#lua-function.net_box.connect says that it's required to use `{console=true}` to be able to call `:eval()`.

Calling `.connect` with `{console=true}` gives warning:
`Netbox console API is deprecated since 1.10, please use require('console').connect() instead`

Also support of `user & password` options is not documented.

**Comment by lenkis** [comment]
Please check if this applies to 1.10 as well.

**Comment by pgulutzan** [comment]
Yes the deprecation warning also occurs in version 1.10, I added "Deprecation notices" in whats_new.rst for 1.10.3. The decision to not document user and password was made long ago and was deliberate, the idea was that users should only be encouraged to use them in the uri.

**Comment by printercu** [comment]
@lenkis yes, it appeared in 1.10.3. 1.10.2 gives no warning:

```
tarantool> require('net.box').connect('127.0.0.1', 3000, {console=true})
Netbox console API is deprecated since 1.10, please use require('console').connect() instead
```

@pgulutzan issue is about outdated docs. Please consider reopening.

BTW.

> users should only be encouraged to use them in the uri

I think this way is error-prone and less convenient. While there is no example in `net.box` of "the right way", the uri module works not as expected and lacks docs too:

```
tarantool> require('uri').format({host = '127.0.0.1', port = 3000, user = 'cluster', password = 'test'})
---
- 127.0.0.1
```

I think that it could be better if there was one more interface `net_box.connect({uri_options} [, {options}])`.
