### ISSUE TITLE
RFC: Persistent Lua functions in Tarantool

### ISSUE THREAD

**Issue by kshcherbatov** [tarantool/doc#779]
# Persistent Lua functions in Tarantool

* **Status**: In progress
* **Start date**: 10-05-2019
* **Authors**: Kirill Shcherbatov @kshcherbatov kshcherbatov@tarantool.org, Vladimir Davydov @locker vdavydov.dev@gmail.com, Konstantin Osipov @kostja kostja@tarantool.org
* **Issues**: [#4182](https://github.com/tarantool/tarantool/issues/4182), [#1260](https://github.com/tarantool/tarantool/issues/1260)

## Summary
Persistent Lua functions in Tarantool are such Lua functions that are the part of data schema and are also available after restart.

## Background and motivation
Now Lua functions defined in Tarantool are a part of the runtime environment and must be defined again after program restart.
We need to introduce a machinery to persist them (make them a part of snapshot). This is a useful feature itself and moreover it is a dependency for functional indexes:
all index definition must be a part of database schema.

### Extend schema with some new fields
Let's store function definition in _func and automatically load/define function on bootstrap (as well as replicate it).
We need to extend _func:format with some new fields:
```
| id                  | unsigned  | Unique routine id                                         |
|-------------------  |---------- |---------------------------------------------------------  |
| owner               | unsigned  | The object owner                                          |
| name                | string    | Routine name                                              |
| stuid               | unsigned  | This makes Tarantool treat the function’s                 |
|                     |           | caller as the function’s creator.                         |
| language            | string    | 'LUA’ or ‘C’                                              |
| body                | string    | Function body                                             |
| returns             | string    | Type of the returned value.                               |
| is_determinitstic   | boolean   | Whether the routine is deterministic (can produce         |
|                     |           | only one result for a given list of parameters) or not.   |
```
```
code = [[function(a, b) return a + b end]]
box.schema.func.create('sum', {body = code, is_deterministic = true, returns = 'any'})
```
User may specify is_deterministic = true to mark whether the routine is deterministic (can produce only one result for a given list of parameters) or not. The routine is not determinstic by default. User may specify 'returns' argument - the type of returned value (any by default).

This information would be usefull in future because we may use only deterministic functions for functional indexes (in future).

Persistent Lua function object must be assembled just on insertion (in contrast with C functions are imported from .so that are loaded on demand) to export call pointer in 'persistent' table (see ###Part3) and to safelly construct a sandbox(see ##Part 2), statically analyze function body for 'callability'. Anyway the function may be invalid, indeterminate(important for functional indexes implementation); but there's nothing we can do about it.

### Sandboxing
Persistent Lua functions mustn't refer to runtime environment objects like global variables or Lua modules. To protect user from doing such harmful things, let's use **unique** sandbox for each persistent function via setfenv.
The sandbox provides an access to this functions and modules:
```
assert, error, type, unpack, pairs, ipairs, pcall, xpcall,
print, next, select, string, table, tonumber, math, utf8
```

As it was already mentioned, each sandbox must be unique to prevent user from monkey-patching sandbox modules:
```
function func_monkey() math.cos = print end
function func_cos(num) return math.cos(num) end
func_monkey()
func_cos(0) ---> 1
```
*This means that all persistent functions are stateless.*

### User access to a persistent Lua functions
Despite the fact that this feature is introduced mainly for system purposes, user access for such object is welcome (at least, it would be useful to test routine that was created).
1) Make persistent function available to be called via netbox connection :call method
```
    box.schema.user.grant('guest', 'execute', 'universe')
    lua_code = [[function(a, b) return a + b end]]
    box.schema.func.create('sum', {lua_code = lua_code, is_deterministic = true, returns = 'integer'})
    conn:call("sum", {1, 3})
```
2) There is a new box.func folder that represents all registered functions metadata. The persistent functions have .call pointer that allows to execute them.
 box. 'persistent' folder that exports all persistent functions and their metadata:
```
    lua_code = [[function(a, b) return a + b end]]
    box.schema.func.create('sum', {lua_code = lua_code})
    box.func.sum
    ---
    - call: 'function: 0x4016b6a0'
      returns: integer
      is_deterministic: true
      id: 2
      language: LUA
      name: sum
      is_persistent: true
      setuid: false
    box.func.sum.call(1, 2)
    ---
    - 3
    ...
```

### Privileges
Persistent Lua function use the same security model that their predecessors in _func space did.
The user must have execute privilege to run such routines.

**Comment by kostja** [comment]
* Kirill Shcherbatov <notifications@github.com> [19/05/17 16:27]:

Please send a pull request against the server, doc/rfc directory,
not a docs ticket.


-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32

**Comment by kshcherbatov** [comment]
> * Kirill Shcherbatov <notifications@github.com> [19/05/17 16:27]: Please send a pull request against the server, doc/rfc directory, not a docs ticket.
> […](#)
> -- Konstantin Osipov, Moscow, Russia, +7 903 626 22 32

@kyukhin asked me to create an issue to share link with community.

**Comment by Gerold103** [comment]
You could push it into doc/rfc and share a link to the file on the branch. tarantool/doc is not a place for RFC.

**Comment by kshcherbatov** [comment]
Kirill Y. asked me to do exactly what I did. 
--
Отправлено из Mail.ru для Android воскресенье, 19 мая 2019г., 21:52 +03:00 от Vladislav Shpilevoy  notifications@github.com :

**Comment by lenkis** [comment]
This is an important feature. Will be released within a few days. I'll update the labels when ready for testing/documenting.

**Comment by pgulutzan** [comment]
I pushed a change. I assumed that the appropriate version of the manual is 2.1. I left out several things which did not correspond to what is currently done for issue#4182, for example there is no returns option. A few other variations are due to recent email correspondence.
