### ISSUE TITLE
log: it is possible to pass Lua table as a first argument

### ISSUE THREAD

**Issue by opomuc** [tarantool/doc#807]
https://www.tarantool.io/en/doc/1.10/reference/reference_lua/log/
![image](https://user-images.githubusercontent.com/8739816/59753606-2af11f00-928d-11e9-8231-845453b63003.png)

**Comment by rosik** [comment]
The fact it is possible doesn't mean it should be used

**Comment by lenkis** [comment]
Perhaps we need to document this, but with a use-with-caution note?

**Comment by printercu** [comment]
Downvoters, do you have any other suggestion for dev-time debug logging?

If this change is approved, then there should also be a note that this call modifies input table and does not log several fields, so it's better to use `log.info({obj = table_to_log})`.

**Comment by rosik** [comment]
Yes. Use `log.info('%s', json.encode(obj))`

And join discussion here: https://github.com/tarantool/tarantool/issues/3853

**Comment by printercu** [comment]
This is madness! One need to know and pass every time some specific options to be able to log tables with cdata fields (error: unsupported lua type 'cdata').

This is essential operation and should be available out of the box.

**Comment by opomuc** [comment]
> Yes. Use log.info('%s', json.encode(obj))
@rosik this is hardly a better idea. There are `function` and `cdata` that are not encoded if not specified explicitly with `json.cfg`. Also, `json.encode` is called BEFORE `log_level` check, which means high cpu load on logging

**Comment by rosik** [comment]
> > Yes. Use log.info('%s', json.encode(obj))
> 
> @rosik this is hardly a better idea. There are `function` and `cdata` that are not encoded if not specified explicitly with `json.cfg`. Also, `json.encode` is called BEFORE `log_level` check, which means high cpu load on logging

Your point about `log_level` check is the most valuable, I think. Never thought about it before.
