### ISSUE TITLE
Rubberise main layout

### ISSUE THREAD

**Issue by mejedi** [tarantool/doc#83]
Currently, the main column width is fixed (like 800px).

It would be nice if it could expand, taking available space (with a `max-width` to prevent from growing too wide).

Related: #9 

Depends on: update header / footer layout; TOC grey background is implemented using a background image in `body`.

**Comment by bigbes** [comment]
We needed to have rubberized layout for documentation: 1220px width max (previously - 800-900px):
300px for TOC (Tree of Contents)
20px  for delimiter (for now it wont have any functional meaning. later it'll help fold/unfold TOC)
900px(max-width) --down to--> 600px(min-width) for Content

Before:
<img src="https://cloud.githubusercontent.com/assets/495636/24661860/372e58e8-195c-11e7-9ad3-0c56b9e70453.png" width="500"></img>

After (ignore "hideable" in TOC, for now):
<img src="https://cloud.githubusercontent.com/assets/495636/24661851/328c9192-195c-11e7-8a6d-fea64bbe3d5d.png" width="500"></img>
