### ISSUE TITLE
[0pt] Clarify tarantool update process to a newer major version

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#836]
Our guarantee is that Nth major version can be upgraded to (N+1)th one, but we does not guarantee the same for (N+2)th version.

Say, to update 1.7 to 2.1 we need to update it first to 1.9, then to 1.10 and only then to 2.1.

We should clarify also what is a major version of tarantool: 1.7, 1.9, 1.10, 2. The way to enumarate versions was changed since 2.*.

**Comment by lenkis** [comment]
we need to revise the entire release policy doc then: https://www.tarantool.io/en/doc/2.1/dev_guide/release_management/#release-policy

**Comment by printercu** [comment]
Actually upgrading to 1.9 is not required, 1.7 -> 1.10 -> 2.1 works fine.

It's quite easy to migrate using docker
```
$ docker run --volume /path/to/workdir:/tnt -it tarantool/tarantool:1 sh
  sh> tarantool
    tnt> box.cfg{work_dir = '/tnt'}
    tnt> box.snapshot()
$ docker run --volume /path/to/workdir:/tnt -it tarantool/tarantool:2.1 sh
  sh> tarantool
    tnt> box.cfg{work_dir = '/tnt'}
    tnt> box.snapshot()
```

**Comment by Totktonada** [comment]
I would add to the Max's message: using `box.snapshot()` is important here. Otherwise you can receive the following errors:

```
E> ER_ACCESS_DENIED: Usage access to universe '' is denied for user 'admin'
F> can't initialize storage: Usage access to universe '' is denied for user 'admin'
```

**Comment by Totktonada** [comment]
The issue related to `ER_ACCESS_DENIED`: https://github.com/tarantool/tarantool/issues/4606.

**Comment by veod32** [comment]
If we are not going to revise the entire release policy process and documentation, then the estimation of the issue can be 8pt.
