### ISSUE TITLE
Make each function a link 

### ISSUE THREAD

**Issue by kostja** [tarantool/doc#842]
https://www.tarantool.io/ru/doc/2.1/reference/reference_sql/sql/#functions is a link to all functions, but it's impossible to get a link on individual function

**Comment by lenkis** [comment]
@izmalk Now that you added all labels, please make sure we make use of them in refs throughout the manual.

**Comment by v-izmalkov** [comment]
I have failed to find any reliable evidence that they are ever used in our manual. All search results are false-positive or contain only pages [SQL](https://www.tarantool.io/en/doc/2.2/book/sql/) - a table with SQL standard features and [SQL statements and clauses](https://www.tarantool.io/en/doc/2.2/reference/reference_sql/sql/) - an initial reference page with the labels i supposed to add links too.
Please advice
