### ISSUE TITLE
Add more info about connectors

### ISSUE THREAD

**Issue by RepentantGopher** [tarantool/doc#850]
We should provide more information about Tarantool ecosystem in this doc https://www.tarantool.io/en/doc/2.1/book/connectors

For example there are plenty python connectors:
- default https://github.com/tarantool/tarantool-python
- with asyncio support https://github.com/igorcoding/asynctnt
- another one with asyncio support https://github.com/shveenkov/aiotarantool
- with gevent support https://github.com/shveenkov/gtarantool

Also there are some tools for php https://github.com/tarantool-php

**Comment by izmalk** [comment]
The last two for python are rather outdated imho. 
Is it a good idea to add those two?

**Comment by Totktonada** [comment]
Are they in working state? Are they have its strengths?
