### ISSUE TITLE
No information about msgpack.cfg

### ISSUE THREAD

**Issue by akudiyar** [tarantool/doc#859]
The page about msgpack (neither for 1.10 on https://www.tarantool.io/en/doc/1.10/reference/reference_lua/msgpack/, nor for 2.2) does not contain any information about the usage of `msgpack.cfg` function/property.

This property is important, for example, for serialization settings like encode_max_depth and decode_max_depth. An example is needed on how to set these values.

**Comment by Totktonada** [comment]
See also: https://github.com/tarantool/tarantool/blob/6277f48ad8a7213d73e280d5046c5b5872f74e25/src/lua/msgpack.h#L47-L52

**Comment by Totktonada** [comment]
See also: https://github.com/tarantool/tarantool/issues/4434

**Comment by pgulutzan** [comment]
Actually the msgpack did mention configuration, it said: "Also, some MsgPack configuration settings for encoding can be changed, in the same way that they can be changed for JSON." with a link to the JSON page. But we've added an example. More can be added but it's not clear what actually works.

**Comment by Totktonada** [comment]
I think it is important that box serializer can be configured using msgpack module (see the comment in the code linked above).

Consider the example:

```lua
box.cfg{}
box.schema.create_space('s')
box.space.s:create_index('pk')
t = {a = {b = {c = {d = {e = {f = {g = {h = {i = {j = {k = {l = {m = {n = {o = {p = {q = {r = {s = {t = {u = {v = {w = {x = {y = {z = {a = {b = {c = {d = {e = {f = {g = {h = {i = {j = {k = {l = {m = {n = {o = {p = {q = {r = {s = {t = {u = {v = {w = {x = {y = {z = 42}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}
box.space.s:insert({1, t}) -- inserts a cropped table
msgpack = require('msgpack')
msgpack.cfg{encode_max_depth = 1024}
box.space.s:insert({2, t}) -- inserts the entire table
```

**Comment by pgulutzan** [comment]
I said "More can be added but it's not clear what actually works"; I was thinking of giving an example with encode_max_depth but decided that was premature because it doesn't work properly.
You observed problems yourself -- truncating instead of producing an error, and saying it is 32 even after it is changed to 1024. If we documented with an example such as that, we would have to change it soon (as soon as you fix it), and that would be a change in documented behaviour.

**Comment by Totktonada** [comment]
I didn't got initially that you said about this feature, sorry. Okay, this way to handle it seems reasonable to me.
