### ISSUE TITLE
Show language selector in main menu

### ISSUE THREAD

**Issue by mejedi** [tarantool/doc#86]
![lang](https://cloud.githubusercontent.com/assets/1164291/19193500/efbac4b4-8cb2-11e6-9b43-36aae5a2042c.png)

This change will require directory layout change, ex. `/doc/ru` to `/ru/doc`.

Show a notice `translation in progress` on resources sans Russian translation.

Depends: #67, #68

**Comment by bigbes** [comment]
Also depends on #66
