### ISSUE TITLE
Сonfusing wording in box.backup page

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/doc#869]
> box.backup.start() informs the server that some activities that might interfer with backup should be suspended – suspend checkpointing, suspend Tarantool garbage collection, and effectively enter read-only mode.

It doesn't mean that instance turned into `read_only` mode by it self. It means that Tarantool snapshot garbage collector will not remove any checkpoints.

It can also be noted that the creation of checkpoints in this case will occur by schedule.

**Comment by izmalk** [comment]
Suggested fix in English - please review.
Also this issue might be mentioned in other parts of documentation: for example the very previous chapter has following text - 
"Put all nodes in read-only mode and disable checkpointing with box.backup.start(). "
And in Russian -
"Переключите все узлы в режим только для чтения и отключите командой box.backup.start() создание контрольных точек."

**Comment by artur-barsegyan** [comment]
Reviewed – read comments

**Comment by izmalk** [comment]
> Reviewed – read comments.
> 
> > Also this issue might be mentioned in other parts of documentation: for example the very previous chapter has following text -
> > "Put all nodes in read-only mode and disable checkpointing with box.backup.start(). "
> > And in Russian -
> > "Переключите все узлы в режим только для чтения и отключите командой box.backup.start() создание контрольных точек."
> 
> My point at this ticket is `box.backup.start()` doesn't put a node in `read_only` mode and doesn't disable checkpointing.

I understand that and agree with your point, but my quote was an example of the same problem in other part of the documentation. I am suggesting we use this ticket to check all documentation for the same issue.
But i feel like i need a permission to do that from @lenkis.

**Comment by artur-barsegyan** [comment]
Ok, I got it. It's really important issue and we should fix this mistake anywhere
27 авг. 2019 г., 10:46 AM +0300, izmalk <notifications@github.com>, писал:

**Comment by lenkis** [comment]
Please check all entries of read-only throughout the manual. Changes may be required.

**Comment by v-izmalkov** [comment]
I searched doc.po for all box.backup.start() mentions and checked them - made 2 adjustments to clarify the documentations. Applied all changes to Russian version too.
