### ISSUE TITLE
Make mobile main menu consistent with the desktop

### ISSUE THREAD

**Issue by mejedi** [tarantool/doc#87]
![burger](https://cloud.githubusercontent.com/assets/1164291/19193820/4db13a34-8cb4-11e6-8c39-05b63c767ce5.png)
![lang](https://cloud.githubusercontent.com/assets/1164291/19193855/6c6b36a0-8cb4-11e6-91cc-25960449e11e.png)

**Comment by lenkis** [comment]
More issues:

[ ] Size of the body text varies, let's make all body text be of the same size (e.g. https://tarantool.org/doc/book/box/atomic.html)

[ ] Vertical paddings in paragraphs are too large, esp. in the following places:
    - after code snippets
    - inside note/warning admonitions
    - before subsection headings
    - between q&a sections in faqs
    - in popup toc, after the final item in every expanded list

[ ] some (too multi-column?) tables are displayed row-wise, as if split into separate tables (e.g. https://tarantool.org/en/doc/book/connectors/index.html#packet-example)

**Comment by lenkis** [comment]
Lang switcher is in mobile version's expanded site menu. We have no space for it in mobile menu header. Let's leave as is.
