### ISSUE TITLE
Update by field names

### ISSUE THREAD

**Issue by Gerold103** [tarantool/doc#877]
It is possible now to use field names instead of numbers in update operations. It affects all update and upsert functions, such as of space, tuple, index, netbox connector - everything. Note, that field names are valid for update operations, not for update key. You still can't insert a map directly into box. An example:
```Lua
box.cfg{}
format = {}
format[1] = {'id', 'unsigned'}
format[2] = {'field', 'unsigned'}
s = box.schema.create_space('test', {format = format})
pk = s:create_index('pk')
s:replace{1, 1}
s:update({1}, {'+', 'field', 1})
```
```YAML
---
- [1, 2]
...
```

Introduced by me in https://github.com/tarantool/tarantool/commit/9ee5cf82ae579d62543a4bb335dd1e99b00dacf6.

**Comment by Totktonada** [comment]
Note that it also affects the binary protocol.

**Comment by pgulutzan** [comment]
I tried "s:update({1}, {{'+', 'field', 1}})" with tarantool-2.2 today and the result was: - error: Illegal parameters, field id must be a number. No error with tarantool-master i.e. version 2.3. But we do not have a version-2.3 manual.

**Comment by Gerold103** [comment]
Yes, this feature is in the master branch. So what a problem? We can't create tickets on visible changes in the master?
