### ISSUE TITLE
Improve documentation design

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#9]
Suggestions:
- [ ]  Make TOC hide/show on demand + let the main text occupy more screen width
- [x] Include all subsections in TOC (for convenience, maybe add expandable nested sections to the TOC, like in tarantool-c doc)
- [x]  Increase font size in func descriptions, both in text and auto-generated labels like "Parameters" (make it = general body text) - e.g. see the bug in https://tarantool.org/doc/reference_lua/msgpack.html?highlight=msgpack#module-msgpack
- [x]  Make vertical paddings before some paragraphs narrower:
  - before the first item in a bullet list
  - before parts of a func description (parameters, rtype, etc)
- [x] Multiple functions definitions with one name - normal display
- [x] Refactor `.. varfunc::` -> italic in {}
- [x] Center images in `App D. Vinyl`
- [x] Cookbook - Every example must have links. Break it into chapters.

**Comment by bigbes** [comment]
- [ ] Multiple functions definitions with one name - normal display
- [ ] Refactor ``.. varfunc::`` -> italic in {}

**Comment by lenkis** [comment]
comments to `fix-markup` branch:

1) can we decrease the lower padding after intro paragraphs before bullet lists? see green on the screenshot:

![screen shot 2016-08-09 at 18 25 37](https://cloud.githubusercontent.com/assets/16703423/17522333/b00d9e96-5e67-11e6-9b46-00a3f3563d03.png)

2) text in function descriptions is now smaller than body text, can we increase it to match body text? here's a screenshot to illustrate my concern:
![screen shot 2016-08-09 at 18 26 41](https://cloud.githubusercontent.com/assets/16703423/17522397/e89ed45a-5e67-11e6-9982-86933b3928fc.png)

**Comment by bigbes** [comment]
Probably done. ("Make TOC hide/show on demand + let the main text occupy more screen width" was moved to its own ticket gh-138)
