### ISSUE TITLE
vshard error codes

### ISSUE THREAD

**Issue by Gerold103** [tarantool/doc#910]
VShard has quite a rich set of errors. One of them is important to know about, and people keep asking about it. I think, the error `vshard.error.code.TRANSFER_IS_IN_PROGRESS` should be documented explicitly.

That error happens when a request tries to make an action not applicable to a bucket whose relocation is in progress. That error can be returned by any `vshard.router.call*`, `vshard.router.route():call*` `vshard.storage.bucket_pin`, `vshard.storage.bucket_ref`, `vshard.storage.bucket_refrw`, `vshard.storage.call`. Actually, by any function accessing buckets. Perhaps it makes little sense to mention this error everywhere. I think, it would be enough to pay attention to it in the rebalancing section.

**Comment by lenkis** [comment]
@Gerold103 Vlad, since which tarantool version does this work?

**Comment by Gerold103** [comment]
Since 1.9.

**Comment by v-izmalkov** [comment]
@Gerold103 is that good enough? Or should we make its description more formal?
Also, what is the default behaviour for a developer to work around this error message? Wait and retry?

**Comment by Gerold103** [comment]
Looks good, I think. Default behaviour for a developer - retry the request until it succeeds.
