### ISSUE TITLE
msgpack.NULL is not nil!

### ISSUE THREAD

**Issue by msiomkin** [tarantool/doc#927]
https://www.tarantool.io/en/doc/2.2/book/box/data_model/#lua-vs-msgpack

This table maps msgpack.NULL to Lua nil. It's wrong. I think there should be cdata type.

**Comment by lenkis** [comment]
@msiomkin @kyukhin let's agree on this. what exactly do we want here?

**Comment by msiomkin** [comment]
As I already said I think it should be cdata. @kyukhin right?

**Comment by lenkis** [comment]
+ to add explanations as suggested in https://github.com/tarantool/doc/issues/561

**Comment by Totktonada** [comment]
The table shows msgpack and lua types and also has a colon that shows examples of a Lua value. [msgpack nil][1] type has the only value: `0xc0`.

Let's verify Lua -> msgpack mapping:

```
tarantool> msgpack.encode(nil):hex()
---
- c0
...

tarantool> msgpack.encode(box.NULL):hex()
---
- c0
...
```

Let's verify msgpack -> Lua mapping:

```
tarantool> msgpack.decode('\xc0')
---
- null
- 2
...

tarantool> type(msgpack.decode('\xc0'))
---
- cdata
...
```

So, yep, box.NULL (msgpack.NULL) is symmetric here, but I don't think that it would be wrong to give nil value as an example.

Anyway, Mike asks to add a type (cdata) to the column with values examples. I don't understood a motivation of this request. It at least would not be consistent: some examples would be types, some would be values.

@msiomkin Am I missed something?

[1]: https://github.com/msgpack/msgpack/blob/master/spec.md#nil-format

**Comment by msiomkin** [comment]
> some examples would be types, some would be values
> @msiomkin Am I missed something?

@Totktonada "Lua type" column contains types, not values. "bin" and "array" MsgPack types map to "cdata". Why not also map msgpack.NULL to "cdata" if `type(require("msgpack").NULL)` equals to `cdata` and not `nil`?

**Comment by kyukhin** [comment]
I guess, @msiomkin proposes to document this:
```
tarantool> type(msgpack.decode('\xc0'))
---
- cdata
...
```

I.e. state it clearly, that `box.NULL/msgpack.NULL` have type `cdata`.
