### ISSUE TITLE
Enrich LuaJIT related docs with more info about FFI semantics

### ISSUE THREAD

**Issue by igormunkin** [tarantool/doc#943]
We have several issues with FFI misusage in our queue:
* [one](https://github.com/tarantool/tarantool/issues/4089)
* [two](https://github.com/tarantool/tarantool/issues/1555)
* [three](https://github.com/tarantool/tarantool/issues/3956)

Let's update tarantool docs with more info about FFI 64-bit integer semantics to be found [here](http://luajit.org/ext_ffi_semantics.html).

**Comment by lenkis** [comment]
2 of 3 dev tickets are not closed yet (let's wait for them to be closed), and the 3rd one is rejected as wontfix.

**Comment by Totktonada** [comment]
Nothing blocks documenting of cdata numbers semantic / pitfalls and reasoning under this. There was the decision that we'll not change it.

@igormunkin Can you share your slides from the architecture meeting? I found them as the good stuff for understanding the existing pitfalls.

**Comment by pgulutzan** [comment]
This is now handled with a big "warning: ..." in the section that has the most to say about LL and ULL and tonumber64(), and other sections refer to it.

**Comment by igormunkin** [comment]
> @igormunkin Can you share your slides from the architecture meeting? I found them as the good stuff for understanding the existing pitfalls.

[Here](https://hackmd.io/@imun/SkLPEnj1P#/) it is: I removed all unrelated parts and published the slide via hackmd.io (so it can be freely updated/extended by demand).
