### ISSUE TITLE
Tutorial bugs

### ISSUE THREAD

**Issue by Onvember** [tarantool/doc#954]
There is a bug in tutorial.
Here it shlould be 
_"Enter three first lines to the prompt to create a loop and type Enter, then type the last line to print the result of the loop_" instead of **"Take all four lines and enter them below after the  "tarantool>" prompt, then type Enter."**
(Screen #3)

**Comment by lenkis** [comment]
The problem is with the online try console. Opened https://github.com/tarantool/tarantool/issues/4584
