### ISSUE TITLE
Update mailing list links

### ISSUE THREAD

**Issue by kyukhin** [tarantool/doc#959]
We've deprecated mailing lists on freelists.org and moved on own hosting here https://lists.tarantool.org/mailman/listinfo/tarantool-patches
Please, update development manual here https://www.tarantool.io/ru/doc/2.2/dev_guide/developer_guidelines/

**Comment by olegrok** [comment]
![image](https://user-images.githubusercontent.com/8830475/68742632-b1721880-0601-11ea-91c3-ea3aab0860bf.png)

https://www.tarantool.io/en/doc/2.2/dev_guide/developer_guidelines/

Still freelist.

**Comment by olegrok** [comment]
However, it seems that there is a lag between our site and git for all last fixes.

I hope it will be updated a bit later, because fix seems to be correct.
