### ISSUE TITLE
blog.tarantool.org

### ISSUE THREAD

**Issue by kostja** [tarantool/doc#96]
Create an aggregator for all our technical content. Either do it the way planet.mysql.com or http://www.planet-php.net/ or simply run a blog engine and copy-paste the content from other sources (preserving the author).
Add a link into the main menu, i.e. the blog is part of the main site.

**Comment by racktear** [comment]
I've installed wordpress on tarantool.io. I can make it into tarantool.io/blog

**Comment by rtsisyk** [comment]
I suggest to use Medium.com with our domain name (it's completely free).

**Comment by lenkis** [comment]
Which sources do we want to aggregate? I'd suggest different sources for Eng/Rus site versions.

For the English site version:
- Medium / Hackernoon (all articles with #tarantool tag)
- Facebook (selected posts from TarantoolDatabase group)
- Twitter (selected English posts with #tarantool tag)
- manually added content (like English press-releases from corp.mail.ru)

For the Russian site version:
- Habrahabr (all articles with #tarantool tag)
- Twitter (selected Russian posts with #tarantool tag)
- manually added content (like Russian press-releases from corp.mail.ru)

Dennis Anikin also makes posts about Tarantool at LinkedIn, but they all are duplicated at Facebook, so imho no need to keep special track of LinkedIn.

**Comment by lenkis** [comment]
@kostja we'll most probably abandon the blog idea for the current .org site; let's consider it for the upcoming site version

**Comment by kostja** [comment]
Postponed.
