### ISSUE TITLE
net.box: connect triggers are missed

### ISSUE THREAD

**Issue by olegrok** [tarantool/doc#963]
net.box connection allows to use on_connect, on_disconnect and on_schema_reload triggers (https://github.com/tarantool/tarantool/blob/master/src/box/lua/net_box.lua#L1070), they are used in e.g. vshard (https://github.com/tarantool/vshard/blob/master/vshard/replicaset.lua#L110)

But they are not documented - https://www.tarantool.io/ru/doc/2.2/reference/reference_lua/net_box/

Please, fix it

**Comment by lenkis** [comment]
I'm not sure since which tarantool version these triggers are available (2.2 or earlier). Please check.

**Comment by olegrok** [comment]
@lenkis 1.7.6

https://github.com/tarantool/tarantool/commit/40a7b0e2c134a194642420aa73d493e53bd95a7b#diff-a9dd9be71f8af749f288abb6304a5185
