### ISSUE TITLE
httpc: new 'follow_location' option

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#970]
When the option is set to `true` (which is default) and a response has
3xx code the http client will automatically issue another request to a
location that a server sends in 'Location' header. If the new response
is 3xx again, the http.client will issue a next request and so on in a
loop until a non-3xx response will be received. This last response will
be returned as a result.

Setting this option to `false` allows to disable this behaviour. In this
case the http client will return a 3xx response itself.

See https://curl.haxx.se/libcurl/c/CURLOPT_FOLLOWLOCATION.html

Requested by @norguhtar in https://github.com/tarantool/tarantool/commit/daf1ced88de6c78aa630b942afafbc2deb542235 ( via https://github.com/tarantool/tarantool/pull/4119 )

**Comment by lenkis** [comment]
Nat, please check with @Totktonada which Tarantool versions this will belong to.

**Comment by Totktonada** [comment]
It is easy to check using a commit message header:

```sh
$ (needle="httpc: allow to don't auto-follow redirects"; git fetch; for branch in 1.10 2.1 2.2 master; do printf "${branch}\t"; (git log --oneline "origin/${branch}" | grep -F "${needle}" || echo "(not found)"); done)
1.10	(not found)
2.1	df87154ff httpc: allow to don't auto-follow redirects
2.2	daf1ced88 httpc: allow to don't auto-follow redirects
master	daf1ced88 httpc: allow to don't auto-follow redirects
```
