### ISSUE TITLE
Incorrect example for `create_index` func

### ISSUE THREAD

**Issue by vpotseluyko** [tarantool/doc#995]
https://www.tarantool.io/en/doc/2.2/book/box/box_space/#box-space-create-index

Example: 
```
tarantool> s:create_index('primary', {unique = true, parts = {field = 1, type = 'unsigned', field = 2, type = 'string'}})
```

Should be:
```
tarantool> s:create_index('primary', {unique = true, parts = { {field = 1, type = 'unsigned'}, {field = 2, type = 'string'}}})
```

Cause `parts` is array

**Comment by olegrok** [comment]
Also this lines should be fixed:
https://github.com/tarantool/doc/commit/795ea7c1bc15c4fa1968e7b1d813e1830a459b80#diff-8583f3bb3d64f923c5a871d250d3ad08R623
https://github.com/tarantool/doc/commit/795ea7c1bc15c4fa1968e7b1d813e1830a459b80#diff-8583f3bb3d64f923c5a871d250d3ad08R636
https://github.com/tarantool/doc/commit/795ea7c1bc15c4fa1968e7b1d813e1830a459b80#diff-8583f3bb3d64f923c5a871d250d3ad08R677
https://github.com/tarantool/doc/commit/795ea7c1bc15c4fa1968e7b1d813e1830a459b80#diff-8583f3bb3d64f923c5a871d250d3ad08R1434 (to `parts = {{field = 1, type = 'unsigned'}, {field = 2, type = 'string'}}`)
https://github.com/tarantool/doc/commit/795ea7c1bc15c4fa1968e7b1d813e1830a459b80#diff-c13f38cb71ee4972f2e915c204f2d9b6R98
https://github.com/tarantool/doc/commit/795ea7c1bc15c4fa1968e7b1d813e1830a459b80#diff-c13f38cb71ee4972f2e915c204f2d9b6R844
https://github.com/tarantool/doc/commit/795ea7c1bc15c4fa1968e7b1d813e1830a459b80#diff-c13f38cb71ee4972f2e915c204f2d9b6R868
