### ISSUE TITLE
Describe fiber.wakeup

### ISSUE THREAD

**Issue by olegrok** [tarantool/doc#997]
![image](https://user-images.githubusercontent.com/8830475/69340470-a0b44900-0c78-11ea-96ec-373799830a76.png)

But our doc doesn't contain this information - https://www.tarantool.io/en/doc/2.2/reference/reference_lua/fiber/

**Comment by olegrok** [comment]
Introduced: https://github.com/tarantool/tarantool/commit/4e9bde25ae8c74dfebc6aa22b9db4db56d8ae9c8#diff-4e0d42778e8d31a719f17915c918f427R572 and https://github.com/tarantool/tarantool/commit/96946b6768a830ebd7487c7fe0be84be866df45a#diff-4e0d42778e8d31a719f17915c918f427R522

**Comment by kostja** [comment]
fiber.wakeup() is not part of public api and should not be relied upon, it may disappear in a future release. Basically, use at your own risk.

**Comment by olegrok** [comment]
Then close the issue
