### ISSUE TITLE
Document "serpent" module

### ISSUE THREAD

**Issue by RunsFor** [tarantool/doc#998]
There is a module builtin into tarantool, which is not yet documented.

https://github.com/tarantool/serpent

**Comment by olegrok** [comment]
Initially introduced here: tarantool/tarantool@6d56829

Since 2.2 it's a built-in module

**Comment by Totktonada** [comment]
@cyrillos Should it be part of public API?

**Comment by olegrok** [comment]
This is already a public module

![image](https://user-images.githubusercontent.com/8830475/69351481-740a2c80-0c8c-11ea-8ec1-d22857731078.png)

**Comment by Totktonada** [comment]
If we'll follow this logic, then `internal.argparse` is also public? The question is about our commitments about the API stability. That is why I asked Cyrill explicitly. I don't know how mature things are at the moment, so I'm unable to say anything here.

**Comment by cyrillos** [comment]
Well, I think this should not be an API. We use serpent simply to provide Lua output mode, but it is internal engine. Moreover there is no guarantee that we won't switch to some other engine, or even write our own. So, NAK, this should not be documented or mentioned anywere.

**Comment by Totktonada** [comment]
Can we register it as `internal.serpent`?

Will we provide our own API to serialize lua values to a string rather then to a console output?

**Comment by cyrillos** [comment]
> Can we register it as internal.serpent?

I'll take a look but iirc there was some problems with registering it this way (to be honest don't remember the details though).

> Will we provide our own API to serialize lua values to a string rather then to a console output?

I don't know if we have such plans at all. And I don't get why we need it.

**Comment by cyrillos** [comment]
My conclusion:

1) We need to stabilize our lua serializer first (we already know that there are some problems in output of nested tables);
2) We need to adjust our test engine and provide tests in lua mode;
3) Only after that we might consider if we need to provide some API for external users;
4) For now all this serpent internals should be hidden.

**Comment by Totktonada** [comment]
> I don't know if we have such plans at all. And I don't get why we need it.

To answer the questions like 'I see, you're support lua serializing in a console, can I serialize my data in this way to a file'? Such separation looks logical: say, we have yaml output and it is based on `yaml` module, which encodes lua values as strings.

Anyway, this is another discussion. I should possible file an issue about that.

**Comment by cyrillos** [comment]
Yes, please.

**Comment by Totktonada** [comment]
Filed https://github.com/tarantool/tarantool/issues/4644
